@startuml

sprite $Activity1 [80x80/16z] {
vDG7agmm38JXDZYMaVh-ftrnSp22wOhx7U2V0IHXBUKwfZd_S9kZveJxSZT-OZtZZdtmMsF7HTMuP1KNDESfRmZAnX3B24YJOJFXJ75Uu0LhWnSDBAI3bntf
-vpn1likk3blyGrVISwRF2qULlN81nzmn0Rb_jWKFgW4liNzRpBvi8bNcG8PBum2XcUDPzp-SAurF76UgP4PSFnNUMgBz5YZRsyWr3FyjGTENAp7FR9fri8x
DF075qhUBktasInVtV4CT6Ml0wRi6H9NUljdY_QOCWDgk9UhjbU7jZUcjZTDspFNzfpQ7dzQJ_qzrFEYdcVrlgdlWVfU9MqlmPGz0xgoru6ix6K0oXx-69GP
-6Edp8w_Z2A6Vwhsh05E2SUJHedskpKx4000000Gv6-TH1XtxeNTCxctTW_cNiqzdNj_UqJsakmvsPkoXsMl-vxulVDxxFVYxzdVs_yFsBy2
}

sprite $Activity2 [80x80/16z] {
hDPNWiCW30HGOMJAOcdkVzhjFSc0dBpF5BcW9bpIqeSv0BYDNZJ9UTeC5wofd94xRkfPWeg1iY81rJ7bLHQfOOcfB4W3oqQIcTqHuBjm7K5TY7GWx4YtmnbE
i5i1DySfliaroN6If_33nX_vm1sEMAB4qsR7dVR0MSJFPE1kGtue7a3bc-41JBvKS6xZm5oLJmx2s_OvwHeubmy5n9Fys0QeCdzxBPAc9czof8uQc3ohjCjE
PDEgcz-U7e0NcJuDCCdbyZj4NKW6vMya_Uba2wNP-0kHDmcVyhoncQJryz_dsOgaB5v-K_yUTWMZ1SlatHEOqh6ghioPFe8ZPmCrBBXM353ckC3QJ0RdM5B8
IX9dEHnkgQMgum4g6pFn5wYXlTeDN8xjrJP0xS5rQVILjMaxiAWNC2cwQXPTkBtIVnbWDF73kAHW4kltBj5uHkVH2CThzFiUZgTqdjTmF9ggSPssoBZCLfmu
e_jaN67xRfm76cMeyRwqPWS2000008ByhPC8uqwzi7iczzRkmTohkQTpxs-Fo5wIFITxK_Qmx7NV4xztVe_zNlmz-tlx_m7xLm
}

sprite $Activity3 [80x80/16z] {
hDTPUiKW20LWZ0Or2cV_g-qyjn58yp_Vpv4SkRIM2lSX2W0getD9T5rfWb-a5ReYTvpgcO9Oi2HC0LLXqafEHU0YXHpIWDj8PDaL0RhJMaTGfuKq4JRJ-N22
2-Him4rnYMxqbwIuI5Dui_4jJ_p3Z1LAl6ns_DCUk8ludGpysw1F1JSez45m0_cCJnXqJDWglL4iA6_qBEK3Qqgl60izqOSyiCJswN6aweMUvKXQ2bQoCQT-
T0aRlThihmxdscTgI_R4Xb7BvSiGwZd1GjHmBdqzNxQB0Mrzmjz6Q8uW4ahB1k3PyMrz5Kkfm6kZPmUM2iEfEke5u0u7cRtuWh8Fs7P_hpGaCbw3HJGo7cN5
cWRVhemRpDvvCxOSremm3pjS5QDmysnO1UTQVIPuaps1CCpuwz_7OwoCZXE_4oyv0hKpplLl4J0yWS_5Vg3tRpqebafoj3YvZeDzVMSYSVHWxkzDZ7fgiVSS
pUhzQkoVPp4FUEP8p-xvbNRUorwFwUpoCswJ7MSSxtWPD-5x8rAT_NZinNzipGu4000000JvMoSHnlrwOVTCxgtTWxbNSq_dtjyUaRqaUqxsfknXsUk-9txl
_1xxlVXxzlVs_mFshm
}

sprite $Activity4 [80x80/16z] {
jDO7bkmW34JHmiWO1akr_zN-d0EKQUOku7K0T8InPALr3v8CxwrOmZghphzuDQp8ZV_LCXugpY4lUE0AJiK5aJabRX2aJbbFc3c33yI9iSQ76WRIpSVkzF-S
Su7_BtW4byI1Vqd1HP7a7xl-as--uDOkolgrEVcYKpYBzJFfV5d7JyOD33yuDt1yTt6B2z-4V7oL0u6lYl9d2pqM-Tyxf9xZiyof2gd7hBqqXzXh0C0fKti4
ODfXcDGpe4g7SLvIhm8kNTFGUeua7KQbrcCovJ0IrPuLZhq1m9lSAurZ2K2ct6jTE0pNUztdXr6ezppcXn4FUZ4_Z4Qz9np6mMsz0W1zN-y0aEfN6PzPhPDa
J7f_6-TyRy_xtbvlUtkjyF_k_jE9pyxUEqUAKQ7FgxItb-0xUmxKdRqAsCwU0TZPqpTxVSlFt2Oh-vhEfNrILvHzLnVljOz_RCqE10000004-Lid4SQTUc7t
JEwjtOEvLtDFvzxV7f6z97jEzgRiOTdhlYT-x_mU-xtuU_Rtzly3zgy
}

sprite $Activity5 [80x80/16z] {
jDPdmlGW20HWN0cnmTp_j5ylxnP5Kvx_wHC66WiikQe1W6dDme6EuwHueudfY9ZHbICj4iMG2YtO3IxRQH8hfYZJX50nhGRoR8O5jj5Ong9C0w5XMGlK4nG7
QE-43yCXzg1FWk4W2-x3dd_aXXEQ5vIpiTbmqkPyYtFVfEAqIlynBi3qZ-82Id_jkCHEVnYwTdvHq6Nqcw3lGIyI-iH_U_GgkMymei-MpeVe_MbjxNoPVi10
eHyUwOk64I_BwUbx-TXv05aSFSdvDtXnCYe5m8kVOLvWx_rI0D1ARfZ10Yz-iSK__LVXaeo1jhoCv8g1ijofLRtuFMECgS4V685b2tCzQ1CZVBElqn8dv5ra
a-T6L3WM-w7WAc6cR0pJuiGcORfQi88HhUYhvITxxgQCaPhT7MT_xfA6aIpk4lPuhcl3YB2VaFthlYCOuW2_pRcq8lIRUPbIzEbQNGBg5kgpwFSHOoGjdGxi
3WmJ-YjaU6RgLKlQ8czxWoix3x4gtZBH11TnChhAxjh7lxTc1m800000WlojamZZJhsmUoRtrkx1tAkvftFlRu_8Nf8z9tjJzh3iTTyJltT-Z_rU_3txU_l_
0VjN
}

sprite $Activity6 [80x80/16z] {
hDTd6kGW20PWAwDH-Ev_sktkasb0oli_ZMg2BXRgWmK0X4Ud4iDvfJ7US2lXZDpnLS_X86AecC813u597kwmCLpO5SWuu3RiR5V10LA3hkEWhdxhn64pVhyT
umJ-TiCaE4NIvxSJd2JH_DZhdpnnmRGAvMhPL5nKZLnSoyd0PMC_KN23tRHXt833ye1EvjO7m_9_m8fljES9bQnT0KtpJsvoH8-UHuOZWjbwEt_TPwlJvlfG
MXjtCxlExgB4QuPOBxXgMSyOxneWMZNTpEYjygpbDp72pMOBCTnOV__rXNwn6FMq0inmAOJljd_jCslwdUKwOA9kfgEri10iVPW38-xxZQ4RxElT9KF7uhfV
piuzA9xPGll983YDdcPACmQ2hJs_KJAMWtFfv-Tqr_C17Cytw8uHBMps6pstIuQ61nJFoxuvldTqS-N7vs7TeEa4nRQ_WtZgXGeq-zDIyKp34ZqLJTlioTLl
CV2XatQ2YgtuZl1ic1rLeDhSjrinzl-L5eR1TRBdHYMNsiNNy1ctoPvzxSUkhUL7dX7k9xxp-E8_Z_zipGu4000000JvMoSHnfrwOVTCxgtTWxbNSq_dtjyU
aRqaUqxsfknXsUk-9txl_1xxlVXxzlVs_mFshm
}

sprite $Activity7 [80x80/16z] {
hDQ7jUmm20HGiB5MMXcc_sf_VDbfyEeMe0Xpa7DgfNKF00ZlhPZAVLOT6rvDxfWR3hLPaehZb1T9U0GknKD8vg2u2K4xQ5tboX98Y4NEDIGrEQ4hqbOzNivn
WnyjE0LkYKdsQE2cqFHbyrTUyO8rLoZvibdmeYNn5_a_wNXPbq-60Km-E0Rmp_Z441y16zXNR8_ZGCX_1GSc-Oil_7BnUjdrNFwQCMezp9jEIw-txJeSMkPl
firrDZArx7eTkYPIGPg8qgzyRonChBaeE4ykrjH02JBMhF3XmRnrQOdRJhZKEXZAfcvt42gTkXuWA9swmGTbmI2nILt2WDVBDUuJb61d4r32SQLa1XBlk9AQ
bteZhnkWjCBzxWHECIvP5d1CXpuVL9oQSbPw9geZlwEA69Ea0Zx6cUzLSFYdvgVy6SFCJExoNCO6Rv6XoHk_MxC30G0008P1_jP9PF7rlSTpB-oUoRsrUp3t
QkxftFlR8xANPC_9tfGzB7lTzyJldTzZlnT_p_xU_l-0_LS
}

sprite $Activity8 [80x80/16z] {
jDTbOZGX30RW0861WUIz_sa_QTSbWPNdJnsFb6o1I-kY0A3IM-50h-Cgk2ELwHMfuQcMQ54HcAJGWatXqeqciM2AC4q87TDw84zMBD1CjeP5ZGnXODa8puSJ
l42U3HWLBz58ZmJ5YpIuctr_omDl6Dv3UVVPPBmfEtVntfrqlAtJ6UC3c4u47o1qjC6XOoXS6nqeB3KT2ag5JUbNWM6FT19sc8f_UfMkR1Cdc5RYgCEIl4WB
Xuqo7p_peyv_e_Nmk_u2dRTSB--hJ9mW4rKtoCVbMJ9WBq3SyVJoUMNdXeDxljVhgp05Xc7Sdz-0YGiiyP2xJskDi9KsKnTYpd6kohGEKr_i7xguIUX2WKSK
5cMwaXGsXHVWrn9S_cRZBh8dDsFv3hNvgiA-NVIluutsrm-mN6S0dhXZ5RUYbhlX3TATsrqShpSybzVtsufVtEImbPdxAEm7Br_r9m8B1pzTKQYzrp3LEWLp
lh7Qj8kJmBUrUexg5wnBiK_qW9ZEM1MUcSvUzfeJRwthNC0dV4noNjGYSQh2gkBqkulKwJfNRT_wV-5lQtOW00000238tpg9CExKCxctTW_cNiqzdNj_UqJs
akmvsPkoXsMl-vxulVDxxFVYxzdVs_yFsBy2
}

sprite $Activity9 [80x80/16z] {
hDTNeZCX20LW6ClOuEn_jN-zATu2cidtb9uu7i2GZMEkNHG0L7hDaUbriGY-a1Bf5Q7YHpNGfYmmIQODfyAb9osAWYKIQG5tBEjCdgJOe8bi5Pig6NXWss3w
2GjU83zzuA5uYHxq7LQyIDbTxFKb3rmmlA1SZKt2HSdPYsjxqd5PfuU8DuXq9tW3ePiJ3cbjA3mdVL1Opezo2WqslSqA6CQnNaBPltfbfvy9_HMS44mKbk1L
scsn8TpgoAywVxNdqyKPi3XPddxJURjZPxgu2PtYmB0KStVRl5_9hoKXTYzVclDVOE7ezhJpoySROdRpdkQx4PPStIOUy27SxXfgzwVCcEuTi7Jn6qRGMqFt
0oEwC6Iuj9QOFi2YsuEVBm-PMS0LbUakENdPEu5oQokJN-6HTiQOsosE6HOLkERwRR18nxAmqF5xXM7yCwNxWAbckEEZFYytmvIZFr3vEOe2K-I5E8ScuxpD
VXkJE0kUgNicAZi5t64hNlsCzO-xdG6N_-OcWMVbPAybXoEa8ekd_82t2KwaDecJgLtP2TKcNJgFx_QptwtPWG00002087_h9CAuNo_idiczjNimzshkwTpx
soEobsJFoTwKFInxtVV4xvtVOxyNVy_-tlv_mFuL
}


!define Activity1(_alias) ENTITY(rectangle,CRIBL_BORDER_COLOR,Activity1,_alias,Activity1)
!define Activity1(_alias, _label) ENTITY(rectangle,CRIBL_BORDER_COLOR,Activity1,_label, _alias,Activity1)
!define Activity1(_alias, _label, _shape) ENTITY(_shape,CRIBL_BORDER_COLOR,Activity1,_label, _alias,Activity1)
!define Activity1(_alias, _label, _shape, _color) ENTITY(_shape,_color,Activity1,_label, _alias,Activity1)
skinparam folderBackgroundColor<<Activity1>> CRIBL_PRIMARY_COLOR

!define Activity2(_alias) ENTITY(rectangle,CRIBL_BORDER_COLOR,Activity2,_alias,Activity2)
!define Activity2(_alias, _label) ENTITY(rectangle,CRIBL_BORDER_COLOR,Activity2,_label, _alias,Activity2)
!define Activity2(_alias, _label, _shape) ENTITY(_shape,CRIBL_BORDER_COLOR,Activity2,_label, _alias,Activity2)
!define Activity2(_alias, _label, _shape, _color) ENTITY(_shape,_color,Activity2,_label, _alias,Activity2)
skinparam folderBackgroundColor<<Activity2>> CRIBL_PRIMARY_COLOR

!define Activity3(_alias) ENTITY(rectangle,CRIBL_BORDER_COLOR,Activity3,_alias,Activity3)
!define Activity3(_alias, _label) ENTITY(rectangle,CRIBL_BORDER_COLOR,Activity3,_label, _alias,Activity3)
!define Activity3(_alias, _label, _shape) ENTITY(_shape,CRIBL_BORDER_COLOR,Activity3,_label, _alias,Activity3)
!define Activity3(_alias, _label, _shape, _color) ENTITY(_shape,_color,Activity3,_label, _alias,Activity3)
skinparam folderBackgroundColor<<Activity3>> CRIBL_PRIMARY_COLOR

!define Activity4(_alias) ENTITY(rectangle,CRIBL_BORDER_COLOR,Activity4,_alias,Activity4)
!define Activity4(_alias, _label) ENTITY(rectangle,CRIBL_BORDER_COLOR,Activity4,_label, _alias,Activity4)
!define Activity4(_alias, _label, _shape) ENTITY(_shape,CRIBL_BORDER_COLOR,Activity4,_label, _alias,Activity4)
!define Activity4(_alias, _label, _shape, _color) ENTITY(_shape,_color,Activity4,_label, _alias,Activity4)
skinparam folderBackgroundColor<<Activity4>> CRIBL_PRIMARY_COLOR

!define Activity5(_alias) ENTITY(rectangle,CRIBL_BORDER_COLOR,Activity5,_alias,Activity5)
!define Activity5(_alias, _label) ENTITY(rectangle,CRIBL_BORDER_COLOR,Activity5,_label, _alias,Activity5)
!define Activity5(_alias, _label, _shape) ENTITY(_shape,CRIBL_BORDER_COLOR,Activity5,_label, _alias,Activity5)
!define Activity5(_alias, _label, _shape, _color) ENTITY(_shape,_color,Activity5,_label, _alias,Activity5)
skinparam folderBackgroundColor<<Activity5>> CRIBL_PRIMARY_COLOR

!define Activity6(_alias) ENTITY(rectangle,CRIBL_BORDER_COLOR,Activity6,_alias,Activity6)
!define Activity6(_alias, _label) ENTITY(rectangle,CRIBL_BORDER_COLOR,Activity6,_label, _alias,Activity6)
!define Activity6(_alias, _label, _shape) ENTITY(_shape,CRIBL_BORDER_COLOR,Activity6,_label, _alias,Activity6)
!define Activity6(_alias, _label, _shape, _color) ENTITY(_shape,_color,Activity6,_label, _alias,Activity6)
skinparam folderBackgroundColor<<Activity6>> CRIBL_PRIMARY_COLOR

!define Activity7(_alias) ENTITY(rectangle,CRIBL_BORDER_COLOR,Activity7,_alias,Activity7)
!define Activity7(_alias, _label) ENTITY(rectangle,CRIBL_BORDER_COLOR,Activity7,_label, _alias,Activity7)
!define Activity7(_alias, _label, _shape) ENTITY(_shape,CRIBL_BORDER_COLOR,Activity7,_label, _alias,Activity7)
!define Activity7(_alias, _label, _shape, _color) ENTITY(_shape,_color,Activity7,_label, _alias,Activity7)
skinparam folderBackgroundColor<<Activity7>> CRIBL_PRIMARY_COLOR

!define Activity8(_alias) ENTITY(rectangle,CRIBL_BORDER_COLOR,Activity8,_alias,Activity8)
!define Activity8(_alias, _label) ENTITY(rectangle,CRIBL_BORDER_COLOR,Activity8,_label, _alias,Activity8)
!define Activity8(_alias, _label, _shape) ENTITY(_shape,CRIBL_BORDER_COLOR,Activity8,_label, _alias,Activity8)
!define Activity8(_alias, _label, _shape, _color) ENTITY(_shape,_color,Activity8,_label, _alias,Activity8)
skinparam folderBackgroundColor<<Activity8>> CRIBL_PRIMARY_COLOR

!define Activity9(_alias) ENTITY(rectangle,CRIBL_BORDER_COLOR,Activity9,_alias,Activity9)
!define Activity9(_alias, _label) ENTITY(rectangle,CRIBL_BORDER_COLOR,Activity9,_label, _alias,Activity9)
!define Activity9(_alias, _label, _shape) ENTITY(_shape,CRIBL_BORDER_COLOR,Activity9,_label, _alias,Activity9)
!define Activity9(_alias, _label, _shape, _color) ENTITY(_shape,_color,Activity9,_label, _alias,Activity9)
skinparam folderBackgroundColor<<Activity9>> CRIBL_PRIMARY_COLOR

@enduml
