sprite $AppScope [300x120/16z] {
xC610000082W_QaNgG800000002ONJFRRXVcWVZ82zw7zt_QR_aJg21AAVJqAlbT9JwcbCbO5WDFI4WE2FCyaxtcw63omUS-ptC3qESLbeW37oIDUI42VjOK
Zoy-k3fl301btj435Zv8dJK9aFb0zm3m8Sq7n1YRgtoKSlrP5W1ZFiA8DoVE1Xu8nd31MvDdYmwWMUE2zwNEDX5miy6GZrH7gFi63Tr7gYCP49fY2TwHCd-3
0DDiCV26s5BOVOCcu-tmiudTDsW4RyUOlwU_A6ZfKwoUcG1dxv3fim8DLRBTUMMy4tq-9mEWtT6xjxmBlDWt-ENOWWzd1YpBfc0QwuEtaYtRM1-gdPZY6qJm
Ito8mGl-3XSSVeJC9k5iyb3IJNX99SElXAfS62NWRvYYY-bYQApffxE3Mf8Dht0aA-vJg9Zm5xWuJT67-ms3nmkevEddjpg99ELNKlKSuvJh80L_GPIK9gJR
Ix2UDXXkrsj4l62m_y8FGPif9Fm9mISV9TvkhkJCXsNVcfRN5nixEsvIoOm_9mVuV3jZJsTz0sL_v7XziP99ZtjqqkFlYMd2JsYN4xnYtKh3HCW6JnPTIIC0
YQNM7B3XOm3WKgarURM2wM0XKwcrv2XOU1nQr012z01yghKc1yKoM9B7HMW-ZFWEKVt2oLwGo0de78ALI3eaBlHDhSeEgLoexijN0GPfS66rdQjyaB3IsE0Q
5weefTJW9UPdsccN4O3m4taxAOjYMgjOoD7Qq6r09QMJe_L1ShXj6onuGfPh_JVnOQ71xTWccrR33R8lmrq0DRctJh8xNC3DppYSa9xJmVIYifTr9IgjEaVS
Vb-_QTNP_ds9W-p6FhZHo94S09-Mq_hDYx6JxMjQVmnFuslOaSm2m3MoumBXvWFbwIUvUtaieQfAT5njiogqVMB5WXjaKiF-QM4FTxHlneBqJTt6BrVweOVJ
bvhJhxIYu1pX3mIMLOcejlwehU8sOrNTiaxa0BPnjWZ58EFHlbr_6L_smqecs-h1PXrugxsQReNErVBUzWiE3gsLQEVbLPEwayFhnfyZkzSNMCcqMw5n_L3q
xqRtE6CqpdDBgt6loXMxid_LwAZgbJezsOphBTfxUTdqYcpYPIoOdSL45YNQKS91YbOv_c8D1lo0TgwLThl-67S6SkJO_TUc7h6IvF3szGavzgVjgpe1UX6c
PJBZnhM2vUSzxUQ6aCtAtki3acxJIkjAqeXkbaaALqWEfoNGUdVhQoFza_oE1zBzdi41mTrucfXmH0Ptv6jQLUm9WwnQWhsH3AksuzBCo-JRMk7P7cmt4gze
LFOzuwwlzAPWQdN1LthoTMWy1OpNKnn_Sj_Ro7YpNkbDwsVrghseL-g4jsZ6q-Ln_I6rMTdtBgi_tmUhKNFNQyyNzi79t0STRfADjntFCvdpJYEJatL1h_kh
jfji6tKJMrCkz5VgHxbEDD-6aOkPSx5MZ1mlwAHlTyeQtJBgUDctZzqqsVfsUUhRWngzYfXlMTMBEMeqAd4nAl2r-q4HRCXcawppWQE3f9FPk1ya6RVX9hX7
tp-5FtysOI5sST7qPIIIuv4pkBhB6SOZPmXRpX3OafSboHjVVkXy_049nQtYDh_c35t54Mlye7E6GVQuV9ngmHMI-LPeFvjjTx1sVwYhUoHJ9KUh_P1V_TEe
DfLV1VvZZ47jHjT9ilT1qkdygks2ggR-f1g67ylXdOlnBY3ssyOH9hF9P5Jsz9mwK1wPGpPoKNhN3hceQzmO6HjIjb4vvg9PbBN5TovKiGxdYBX4CzzY9tv3
Z55m8CJe5gtMl3m2MYl0fr9hzZgTpxMsMdF43ZULTLJbxQrCWeMjR_Tv7-7_bvspI40O2c9elT_lVrlSURWpoGwffJQMh1SFTrNSErP7lA3Pn24vnErFm9gh
9oFpz6mZhZWCyCSfSO3Y2y8RugfAg1A4RWsZjiHLI-fJw08od9rxSDt4yjSDQWEZXhZYb1Yc5XYjEQvEfyJbqXreY2k-h63A2X5lDnF16dNRTVMp3wdhtYep
YNJ5IPeQJutOjg8AoRejRYWIF8Fl1o8tyXn0tmzv3d2165Gt_BqyKa3DHHufmiY-7vUyT-Jf11LJTi2ILnXNuXFUVlAWsyODvPm7dRmDZ-A6SbAM9dIZJxci
ueDHdfdJzk101W00062Gl_KzlceC000000002
}

sprite $CriblEdge [300x120/16z] {
xC610000082W_QaNgG800000002OdVDGSvI7eQZatk_xF-rV82GYA6NA5XZEDZvFjftFNEI2lmCNS-q3mEYjHC-aSc9JmpqzExhZX5E7piY6RfoOWcTKHpCd
NF2AQec8JXBU8TE9QNYFuUY74_0-YNuq6O9HOaWLZwbCFnSfPeJN-TNvL0MWCItOySsoJ0dq07QyErLzaXHpD4Hay4bPR0mfDC1E5xvrqGO4ij7I3YWGM2AU
tUNdYT_e8Q43G37QtpGhZW1TgBq3aTWo_Vr422eHDSmK8XfuI7dMJNi7EcrmXeIh1I3IBd2GUEdEFQzF0wba84tPP4XXpwvuGC94NPRed79fW8ub1REglvYP
Y9ntypMpSEM3sPUhWXL4f4IIgz3ef900NjtVndG0XhpeZ15m053svCfXpIgYglZSW4AaBLsclii3lcC0JBQK8boXfWR47RdgszkgIXKMG4jCn0qAJ1lkGhzX
mDC0JGXNSVxYVbm5fQTOQQBUHe3jlKc7kyQvxuonSNNvnUp6LTSYADuUWooYIvN5R_IhATPLLmvmUt7bzGZoVPdLAtWXAwbv9MYBEisL1VnUN3LiSVCOXPS8
VYvhQEKL2Hho4rVxwLVcHOcPWPUoFDrXWVIkgx2Vl8fGQPw9YCC0NiigsX0d4X6N-DGLJr_iH4G3UMV9BXbTY7ekY-xX3epM033PCD32xCV6684IOvnSZU2M
SYi3hNH3Vp6CZw7BSeyMEQeXYYBKej0RqPkeEIe0XBqy1Nl9TNnALY85wonFYUWcQBvU-F_Qai_fwjbwnpkPOqyyDRZsbgoqQJa-YncH5F6rB2OogVsqHHtC
32OYzjwAGS-vFAX7krrkn-55fIuvTpNOxQnnUFVXs4fUI4mVmtXlQMUuwpC_AZCBxnFfOwIFP5oCFf2pVqd9iAf98v5j7wCQMf7NyDTSKJQTIw0_J51cZGjz
cO4LNtULSZfTlKLaduq_w3qu06zkFCchCzi7O5zc-raplE_gh4MVks9hpTQLiLR85eq77-D8L_f-a96PuisLBPXQ-qIb2KvZQao77plhhhZVL0SWgNzRlrkr
7VQeSpBIbQgg1X_o0FBYAW18XiXc0DbRNfuu8mMV1W3xbyxrbM-PwzDT5G1ERA5Fr-hYsi6M6t38oT9-q3balRwQcenSxscBAmzKyPjuwUj5_aaxM9ledr-R
6Di5j2HxY5rSPL6QbOiMbfL-1DhVl-P5drtpqbrr8Au-a2v-WeZEwJe0TMNrs6kf0wZbYhiK9uQkr2VzIhOH0p27NQFNizq0sEoHNFUXSR7IW5OMAW1xsBqV
kYiBG1dZCEHpiEa9Qe-yfqXtDHHN505ao-pAzMRhG5zX3xrNJRy7DLUKiB0uQO3VpPO6ywKzaBehrl9Aocf1v7uu-jvQtPNULELuq1Fnki-LO-_PriLeTcHz
HNOhsm7W7_8kWEugo73t4DbkbKp8Htp79BuzVpLkjnOFuMhh9Qp_N3xskqi3IE76rK0rbu7JM5mP0EWJDHcH2TLDN_Pb-4E_4wUlUQNRPi5g5rVaDFK50h-V
Toqj7jBv8wueBCsP64X2uF-iP8MEXMQE_Gwl3ojkxQNM4itq2NkPAqrCCoR9HuNBjTQI0f_lXiyK86mgL8tpp0461WayaC-pB7GiK4aGzxJ2QlflFIF509q4
3N37Etk7wLiOApaP6EUPJizAu6IdIoiM0_U3_OrdXHLSwglNYypd6NIkOg66ysp35x0BCGPlTtzcPki3m1Yjf7_RWmi2060O043N_fLNOmBylMe000000000
2
}

sprite $CriblSearch [300x120/16z] {
xC4n0G000C8W-wSsmtvW7G0000000C3PEG_5LNaOZYRT-_V-J_iDHAab2dUfN3bt_d4VaZOjhSR7N1k0LalobadaH8M2aHej3Pomhv1fKTF2YOfuHZ5quOGZ
jYXJR9rux27nQKeLxADP-d8izXFfgmdu4GhJzvBmOrH5tqh6Zz9-IfQAdXx0XWyQLTiqfYUm4brcmD3_cDBkpfCdxJKTW0Y94fpHMXiRKeD0VIpBLW18Idgb
oq47q4og5GZ4ckdpSLYJ3FNe8EZApyAqLg3I2gEeTpNJ4EWGQ8mqpxJ25enu4Wb082AEcWGExQfY8D02zxOQ1aGPwgx-OcOYCjPS_i_SkR9E7yjLU50Di4lr
SY1x_Q0Fg0-UKDtbj-OwUJLTC3h0D03fIAuqxabYnjKvA-sEB2ozGXqRN4K35AcKKkSAEHGW7CXLaVBFLa3EJ8Dxc5OqPEh8Q71KGHETgt1vzUEuCaASS8P4
rK8S9ben7Cn08CdL_8y-ZAko7XFhXWSumIvlnnM8Y5bqfG5x55S6FMKu9EUX7_IAxTL2xjMDhXJWZk8ghKOj6jYIbT4ZzOEyszLnuefNASODJx72emOq4FUw
iiTfhzmg0misK6CMPXgP2mEEuQahTUaaB-LmEjPKZ5aiZ8n6s_FMlG2jb4ciSXNLEVeVvRq7ilT-SjMScQrI04ggcZwPiGPdR6D7fPPM-4bcrhV87QAOoQ4M
04ZTINE7wGNTzaIox3IIW3QQBpDu4pJ_VuQ8ZIORWg4PPGtJ9nF6LC8Up92yzUjcZilkIpbfx1Je6sZ3w2PX5qIaqA7f2nWpgs4NUdYefRyVDJHNZ7sueGxp
z5gOtpnrHKG6-uX3kWPwAHR8RoqPsj2qRpNkSN0tOaBEEGMd_a9NbOWSzf67SYFHY6kuqiAVT-MpAvGC_K7idtALqD5U45T1PvFj4NCm0YYMYPK91U4bhbor
ze1jEzyTKlm2LufPCn-mPd10VKC_UCXQD03n3QuEESQ9Zrnng01gO5fGFbK09IgQCIanaOfjwHRO5qntCeihStcSF_ROsGE51FnwsbdbTIQxvH9rMytUpguI
PymqS-Gv6Gr0oozMOuYryy80MWeXjYML7M0jW9fBNbOybPGAa6PNCK_F5Ge0g2FFzHNfRDkR3T-vJF7oFyv0lRaA_Tej1o0o_O_LjxAm6hfUoyn7daFMymJo
7MsvOnG-7zy2n0t-0OILzSRTwQQNKFxCjGdT9lcExmg9F7gHLqSw0ELP1MBlfkOhe0zrpMk44oQMJ2g0wK-Heu48sDjxCdSE_TeLz-Cf-wPhgQhXAKvub8IE
zuqP01Qg2jbLeuLr3DgxEoJ07UyQ_OWjomfS1I3UgFruMraVOaorSvNlpoQjN9Ltk3BeoR-uzcD4bsjgQmpChdJ2ZSLLeXjAT9K7Ln-ufiWBBjLc1MVd1zMU
k9HEBQSOGvLTQQ1jklgyjMfjOwsQo5n06g39w-hZB3l9hjG7kQ8ooFh5DP0Z3YXYAitQ3T5JLxmd1pzhRMqBBAeAj86TooDft1Fw3vrbLzG0lUNgxMksrNND
TijUFxXptLF1vLb5f87KkuReQdoWxEfJzWBmau8CUa-AXsj0wYUk_E1gg3m_mvMynsJVbcZvRdO8MdMDZweMv_DprUuzoAwe0cN3rQVjNKfgDJ-OIGJ8tYWc
KhukGha128g8s8HQhhLJdeu4e8YkPetLylIuydPN526HWpDQQMrzQijurcusLbB7EfPjPMdzQcq0d15SZQ-8zdvNbB03InDbQwzbdAMCCpCSLqdkkvtvagjn
zhHyW2lAsARHXDxUmwjTJFyHtQ2JRPmEBmBPfPJ2bE_6yiMCjPe6b4yvHQ_cP-dleAtb3zp56xgChKpVIy0swbOt5APlncAJH1CUWROuloF5q8IX4uyDAbqv
uOJdEDhB-LrXYNPnVWSTegA14-qBHbeq97DYtFoTcQWb1VDlUt100000mG2C_gNLmBTrNGK00000000m
}

sprite $CriblStream [300x120/16z] {
xC610000082W_QaNgG800000002OdVDGJ1q7ekWTzJht_xzs2nYGWp1EicJXXPEUk9wepWX_3l6njAuajTSSBEQySRdp8orU-NfZCs_Ge-326z-uHJOuyiOr
tYCBW3TIk8U8DrwvZsRmoydSZyTlHXhtyQw7flDpbD-hIiaVaUMBmmsimoiWIlx7iemHN2CaSI3rCloEDF3EleAgpg-GS0j9Ib8d6oWR3bJMyzbx9msCnGjG
-JN2HkEdJMSsnM5qjM19WvSWyQiOJEca1s0B9hoqAyilqp4ZaWudv1y0yTu2Sk3YoWGlh-Mgy-ka-G7RgduhF4azZNRbv2gHP7WbLudVmU0AMIcCXNJamLye
fLrSaJafQL_7bU6tQDCw7TRgj1kpD4zkS6K18Slhk2hy7WuVSQHVkwA5OVxegXw_wCkuClmcRKUvAW04KrU9V1bNcGlQQYcryTFOxVOAiXIpkQluEgxaAkrW
VDPlJdMKRUBgvSjLE2OSN2nDbTfAi01iuIUGISzgzxggxA_YgbKdeN94imCaVMEc8qfr06npMwxwyO_vwChZsN4civSKl7C-fD9ve8VFsAhuY5LIMoSRu2DP
eiE_-1WBcM8CG2MRztqfK9sijUEPCIavYFCnnk0j01FxqPO397CVkCAKSygd3erQ7JhFog8awI-XHZLuOiJ4gZpJipitLiq2fd4F3XEiiylNVp7BzmiMi4ua
f6Z6xPyQkzo4M9-ENZGAp58Mv9BQUSVUfIqrhkLW05zFj-wK9DNlo-ua_08i1teoInFLBUHIj4mbtweGkAQvnKm48fUYTQSYgiEl8F8ZHOu2A-1ue1e0eVC6
wHTdcjKV--ycC7rekdt_vUj02YSaI2EfvlXr6Mm1hjnOZIN5uHgVIoqvkZ_Q5Gjma6M1nYFLBlVVTF5KWXcYwrl1rkh_K5UZB5gWScqB41cpf1ALrwvCdpLf
pkAnc1oZDV57NJ53bAJQSPCU10DZjNIJR4Tn8iQ6ebmKELOyc61IYlc7Ln45M2woncrQyWP7nCPwAzmNLleSZgGVSfL-EeLZuK-o8jTeQxrl9dFQT2ZH7-_A
m1gnU0XXAqcQJh82xu4rEclj3LbVVewptRxJ0awvYLwxibWO-m0j_tBCtXS3IEwaoh95wYHx4boGKBfIMp9OSAK8uAkIFPjZMAcJR14FHdYR0CEJB6cV2lPr
CjpE5YK0ddImEXJAS1rcDUKwb1589stOD791BHwByYOgf-k_6sr8rrr6nmgfjP5Q_yKVNNb7ihVMphEjdbFkWnSXgJMdWp9_TXKRMNEg9EaYgINdHbBb_qka
blEVq_RyMUqavrW5QznO_ZoPbDKCVsGuIxCuKh9TJ9_b1vwFRJgfP3eV8EAX16xW8NhMTZEYhF56_vfaqnLPfhKsaMtMLfZp1RT1CDEusqEHEqssuv5cRjZg
OMCmKjoMguxnntRbPQIIxdheracEPHcFfN633AHrY-kByaAD1ZTmVIXqSrT-fSAFFyJ9eDcVNOrR5fnulAl0BHpGXpZW0UDZoZb5RtQz1ahzBLVhBaP6BtdY
AfokjusjRPWVu-Sh8NNLsrU76JUTcQGacUUksleYyfa-bXRZGqevzy5L7Ltv7tI5mYqou7YX9uiLuWijRXEKP9YwgeFK6mCscvKBWwlolxaotCG3aIDQaxT6
ZB4-bawotLqDhlTSMP8waYypUwqbvzIVmXKADp50vXRk_l_2xN0r3u9aYmFbELm9D-btbh_N7JrjlEDAI4ubU-2fN25nax8jo-0EPSFLLc0YZjMxFeahwFqC
VFbwogkHuPwhiXWOoUF1-Iokx8xrLP5J-gw-mondwRTSsJ6sEXbcXQTnXRX3bcsxQw2nwtwm3dENkIlKrO8YMIvA1vNFuWgxLYm4dKYSuQWbM074vK5e9xi1
81DNeYIJ1I0kjNuELXosJsHx7bVIkSaI1GbjLsFbvX4RJvAziqnSmVIhcXsFsol9w9x75KIvpJAjCw4eJsJCCPLdD5rLzQahIBgAyiJXt4_a2aPvXsgnOAnp
rigMUXTpgQKaXn69kUHeS7hPrnhnkPIIWnt3xQTZE2_u5pFkQBqNd73UFz5hmwl3BjxF71Zdpcyozz1ozCxW8RoVaV9-ziuR-ubdEhrndtXMs1jRTZw3xisO
snffoMBA6-DJQShbcPdnFGxzkpqu80000440zFzrDrA1R00000000C01
}


!define CriblStream(_alias) ENTITY(rectangle,black,CriblStream,_alias,CriblStream)
!define CriblStream(_alias, _label) ENTITY(rectangle,black,CriblStream,_label, _alias,CriblStream)
!define CriblStream(_alias, _label, _shape) ENTITY(_shape,black,CriblStream,_label, _alias,CriblStream)
!define CriblStream(_alias, _label, _shape, _color) ENTITY(_shape,_color,CriblStream,_label, _alias,CriblStream)
skinparam folderBackgroundColor<<CriblStream>> White

!define CriblEdge(_alias) ENTITY(rectangle,black,CriblEdge,_alias,CriblEdge)
!define CriblEdge(_alias, _label) ENTITY(rectangle,black,CriblEdge,_label, _alias,CriblEdge)
!define CriblEdge(_alias, _label, _shape) ENTITY(_shape,black,CriblEdge,_label, _alias,CriblEdge)
!define CriblEdge(_alias, _label, _shape, _color) ENTITY(_shape,_color,CriblEdge,_label, _alias,CriblEdge)
skinparam folderBackgroundColor<<CriblEdge>> White

!define CriblSearch(_alias) ENTITY(rectangle,black,CriblSearch,_alias,CriblSearch)
!define CriblSearch(_alias, _label) ENTITY(rectangle,black,CriblSearch,_label, _alias,CriblSearch)
!define CriblSearch(_alias, _label, _shape) ENTITY(_shape,black,CriblSearch,_label, _alias,CriblSearch)
!define CriblSearch(_alias, _label, _shape, _color) ENTITY(_shape,_color,CriblSearch,_label, _alias,CriblSearch)
skinparam folderBackgroundColor<<CriblSearch>> White

!define AppScope(_alias) ENTITY(rectangle,black,AppScope,_alias,AppScope)
!define AppScope(_alias, _label) ENTITY(rectangle,black,AppScope,_label, _alias,AppScope)
!define AppScope(_alias, _label, _shape) ENTITY(_shape,black,AppScope,_label, _alias,AppScope)
!define AppScope(_alias, _label, _shape, _color) ENTITY(_shape,_color,AppScope,_label, _alias,AppScope)
skinparam folderBackgroundColor<<AppScope>> White
