sprite $AppScope [300x120/4z] {
xC610000082W_QaNgG800000002OVNDBUnk7OIY1x7_DSqynd3dknqgzbtWhVug9ZY7AjjB_IweglVwIhNhGodyHggfN1BnMUjDHW_KFlMZbLzJ-6NvDImgC
5O3HhhueiRuILo_2acYaDHNe8UxjLA2dlomgNcuCSL6niKYBYjixQb5nUqVj3ZWtblU-QcoiHJLkxzfcnL0OeTPMP2mcw4L5xPq1xXu8N8GXDDRgmMe5Mf6j
s5WhyzPONrQIwejATvrTXUATKH-bgxgHl_WXabJIJMSlbi1MMOGCrtUa8dqnswfqRgjYTJoGZcmlKLcI_SMMkkgEbPyhXuu6L_pE3_htOEcBiQe1gvD7ui04
jb1T5uPmAdz1MLKU9GuRUuIFFC_LR-xiK_ZRxxD7fmwcH-bY_UMBc2DBIROj36l2Iku5k69AHX2SQcohABQAdfVWEp-X_dE96F1TCcYJmOqZXPsA2RcLZ1Ay
O3KhePUgDC7xOGzGm-S_ulO_uyBghyyE0kXN2OTLsBb_UoxPawzPZMvpmOfq-VrUYOabtOtAEqkTWH2LsjROnffAThCw7t_tZi4du_oHU_PqzqQYVLlpqaiu
KWea7yTok9bPTwoExEY7f8g_o2gD5T5mdcwWYG4ySScivlzybojMEjezpRKL9FJzCeNC1V9JFmN0llrVNB8d7x2wjXMpQkuGJ3MEm_dsw-8s13vdKZB92Owb
CrlDM2KAKyNBpKdAffLCO0KbYPK-A2aZNJNso0pK_oZJ6RE2g_E9hD1kDwTs9uTOizjNe7d8Ajj-47nxLfuSOcd02hAkMANHtREgKz4XbgP38io2lUg4LL97
Qt3Ss-zVF0wUdOUi39VrO1-i7lJzFdWgq-6oXhQAU6PzrD7zLGj-hlkhGmcFI-_VewP8fd1mtmuLKm3JkQIRhq-5n_0UiOq4QMPRp9y7esv1C1Oy6KF991-A
J-4lZpAu0-iJtpFePS4ZTmh80PGqBXbiuIRxO15EJsPqjWJZjEVtLtebZ1-Mub4ICvPBykNscR5wezVLmQiXzi6vBW_VYvfdbNZ09AsLXD4mpR7ClqQh6qcY
MEoLj-EPs3lS1jbEwlnzUqgsC0-VIs0hTEUzmcfWn0k5rUTM6dlJidemblbXrw-1_0knIjVj4iH8luAleZJsffcn_6kn4b81WgHVg5zb8PuPgtuzLeCVQgEy
h68QNQ0YIRFmlQJwClAPiVOdnkFsNXKjhFo1_xYms5YBAlB-_zsvD6ZlYV_g6XjBjHB2CffgPMplRAgLqLXCQYKs5g--bQ6zMyLQIOwPj9n-RmyEP0000006
-LlVuwl600000000W
}

sprite $CriblEdge [300x120/4z] {
xC610000082W_QaNgG800000002OdVDGR1M6eIZdwl-_-OqC8HoXE6_MnhUBki5D3bUAyVeJ0iaU4YmWPvAzIZcl1IgN5foALB-v5gb-RorIEQqbwnLN9uNr
Iol-TWca3bWB5HtvQw5gCVnnM4MZWr5H8Vu6B3-D_VodbHaJbJmfyKkmE4jgIbXffBTMsgoT76VIM_RdWKOJwWo8oeW5rFcTKrGtZ2dBiLcz1DRHEP8-ZCB4
SK322WPZfOALmq3zi6HsDEszngTVUPRZSJmAAwpqbOlkA7mYTCWyAvOKMDdDi0p4Ad6A3YYScMLw7uBtUfwFT5PU-JYio9oIWDC9BFMmOijO-OzHMALE8UMM
m-fXvSSPAqPXHPw2SCl8ti1IXZz1bxFQ1c9bYKXO5h2sLheGAwDeJzHedKx5Qj1yHTaW9_DGHn3gKO6eMSNtGStIQrp3Agfz00TllPi9U1OxLJEJJSJAOTL1
cFPJD3xTZnLEO9WGbFHhi5Jst75JF0RkVqVQyS0ejuAAy6gbANz-9Q-M3bWDBLsALGm2rl1WgXUZu4Ubn5LPAJYCS5nBkxPFnNYiSJuKcVlFnwG-oN406r-5
LR1Ilx6AtAwZ-bdbqcQR-8gizCSRkB_FIbgi-iI6DYQDmIo3vQnMRdSlLQnMcw6VrMgBzhDQzpWLAzp515Qo81qBDV-zSyugeEQqNwCjdBvFvhIhL83Cp6EG
E5eamdCGoAkUjgylPwKzTBMVuuKnB8-TfPFt8OUYjCnPEQ08MCT2vXwRI4WU7H8YZs0y75hq_SHZNZahhx9c5Rtcu6OTItKKktXzpIfOgQKwznXzKfQnolEL
7KYdhEQS-r6pYg69iserzvoYVbOyMEC6IbXDF5UjdrNhMhVQHUP0zhEAi98SVyMvjJKhl8Q4u-npjXrCHS3yDpEIIpVvMe2SLKu0PqNUuj1rrfZO6m8MMIbx
Dao_TYboOTUhbq8CkkILXVuPPCoz9Yvzb2BYlBzCsRDXxhMM-SFOaJWhvJwD12TVmyjHUxdVIiDh6bUi4jt4MXk-rqvVoshjET00vxpMjPU5cGfMQu-KmbT9
lMlldHnErQ-tzdIYRLEjlSAw_zNQWwuI-k0YhBqDkMaRMyIBhhLDt_Vsu80000040T3_rzr81M80000000001m
}

sprite $CriblSearch [300x120/4z] {
xC610000082W_QaNgG800000002OdVFGSII6OUYG-lzllZ8fX9VHQeo3aTN5l1fPTZ0ladjsNW0PTn78tBOOBZglBKGcklCEgLoGvoPLQaDAiY_9nAsuAkoW
kYxkdcf26zM4Dghbi8Yq2ArGhOV523nwHzdYjA8pAW9Q64x1GZO2y5xBMB7n24ZKE5copnCDGs4VLc72DQ98KV7yzqZKbzNbU46LXVcJ0tZ12cZ6YXa0qFBH
V9C6HxwtZ-F16W_x-PAjMBqEAbYwvMPlS2I71rQI8LP1HWJ5gYCg8QbBwXJaYVJX6M95SUt12Z48bch6nGZMh7YyOgL_6h3AdZmomUb6pKe-8okzxi3A7znD
pX9cClmZA_PdvTbMxsBHAtcR_oahJx4m5Jueab2iUlTNi0Y9IbQDwGAPB5bHh5gb84IXWbNsxYf2H03FsNi40JpCJweHmMYIWdLOvKYHnIlbAUif_P_3laoN
58JYR2wm-EtE7Kxf_wTkvI0XVxH9mJgiSgYVjtCyTJw8ZsCrdO9Yy_6iufgywWSe0L09nsQ5YLDdlkyK6k-OkM8XA_0KDgkA5QnqAIiGSH0jMN5mNy_gu47q
PAK52wZIjQmGGCU-tKohMFMVCq1vjvXL_xae8xYQLVSrJisAuIcBhqQGJr_XEKM8rRqUEg-Tynn4U20op8Y8fw-DGKzMgeZMUp8osPkH79xlj8r6H02dFQYA
EgG-ML5jHUkzlaThzbwmk2D5Kb4qP37q5geV0OsvhVUGaua4lklGn4grZOOSBE6NAnQSJQWSsU2Ld2h2K0Y6HwZQwdpcfMGUyC1UfApWTgUdyfPdgJcjhy_7
RrbPRXQiUfxHUz2grtbgZ4RWPXCh_aXMS1BpTpzovPy0xSEQOKLZrUvEaOlPc35EdKWkODNWhfhjEQH3EuS0--6iF8Zm3tSWNO9ahXeF-x2gxzRMvdbM6Wvx
i9g_i-tErpPGn2Ld5SPAJWjOhVukW3jVQfoAhvmLd9KA5h1QznqJ2RKRHXmn_Y_14E6iLBA0rShlBj71CaDFG0t35jHWnBWiPkIiX16CzxBAvmYyFpB0TEEj
3bEyjjjE7r9M22bXzMPOQM9MgF8Z7bfR2BqsLX8Ni5e9It1ILFK9FSoCfm5uc90qQ0vwzUDWKQxxY_GJWNLyj70vi10yFbsNktSSMuXAyjrY6LXNjMbn0ze_
WsxT2Z7N_fcPczFlzk200000107G_zVTI0MI0G00000000S
}

sprite $CriblStream [300x120/4z] {
xC610000082W_QaNgG800000002OVNlHLbG7WZ3SVzNxF_EvYB8w9ZGmurPaqtCD2wBpKGqQdPq5yhqaOg6kGkvhu7LLWgguhi9bAOgwf4gjg_lg8gx2M-iA
bJVM5ItlAYwgxQMBwgUn4B5Kd83gbLZpZK5My-0HS5Qg6ak37Mghazq1jr_W2qqYMQK3panLXU71g1ZKTrlPhyLYa3WOMK6oEZcLjJ1X6zfWSbNobNKRyarM
ibySh8OGsTntHKfMdhI-oSf-DTPJ2qvxtVr8LidLFckiwdiXlLMChDIGdJPMkSfSvPRyUYjvBabwaPK6T6ChliYgRoHsWcaqPsTrWbmnGV404lilOdrMpsbb
qGL9xDDYyNMxoLRrVP0uUX6o9Mwb6MYNbeeRHWJOOf80T1inJG-s7mT81y-MH0HJpKsvLwjSPr3oL3f4daPypre3Mcg_xIyeA5Vk0DBVvo4HY2zQwQCpeya2
MwtENssWcBk2NOsetsNLNbrojAQ_NbGCkabzjBWwS8IW21v_fjHmVVIbSKmUVPY3Go7rQwsiZ9MrjDHz8lf2aWGdjAgnrBqO4wcHgMOM9xRAM5hhDeQNzs6Z
_hoP888tM9LOlKZE6GCgpOqxg-eDxsw5tcjbHbWpGDUGuuMUfpZff5QEuA70xZVFIsiFEkaN-I9KOzLMdCugoZSkBh5gg_5faQIfZQKvrzNNHNZUY3HlLZwE
3rgPX1KkI-kvUjgRDFzpn1bT8iWlKDBMTDm7hLojDjHMwf-vrEGA6pnL4xi6At-un6n5tdeVl0DBjO1I4ahL3HTtR3M3PZnhaBjI6J-PvXEjDC67Bkwv2wtA
bOLJeDeg3tFNQeoVhV8acVE3JUXakPX2YhoAqYgQOUCoc8y-Fyqa7xPIuc5fTRuEBCjMT1HfK5dbhNgVrVeoNfyWw1SGQgsnLV65BMssuerMuRAQ7SGVtJcq
oKfppOUaC-DafOzPQQqBATVsa5V3nT1AnGbJz-GEOHKkYwvD9Th_uxi-_Nwh9ANZv2haibRt85Qns60LNIa7x1XMuR_2KhpSAXzuC2kvBDMxh4-_pOhHfIwE
PXMkYmfByOfSAGs7sxpTwlDOU5oR9az_oLRjJfKLnx5Y0rRyEPNMhMIxw44VnohakhGWoXAzybkYz0_khBA6vcDQPVb8Lk5Lh96MDiNqURD6Lk5SpzF0SQng
h1mXjE6whh4dbLMeVwmqFePLZJMMWQWBT2lwp-rPd87k4EODC7heF03YC5ZMl-tSnG70G0W4m43_FSVj6TUP5au-i1j51-7vurDCUU9jrv6YUuSd_5cwmdJG
4RdcIZ6BVRr-HnO00000002W0W
}

