@startuml
sprite $AppScope [200x80/16z] {
xTg7SgGy40JWdg0mxS3xF-qVG9o4ZUhuuorLV1UyGrYhIo1f0twzn-FnU3mUZyVZyH1B0djxUwlP5JSb7iko522MrNjMt8-apsMbq6KNXfj9ouv0MNgbk17b
qZdaO-aoRiC-by4xaCOwv6xNLE-1jx5-arl5w0IsZDu5hy-NRofGbn45hqwN4_PbyuVWrRqj9mZaiNQykh6vqx7t3SY2LoRBkG-17o-pWbScEY40ZxUzugPi
QNHzMF2wF1y83kfnMfIJqt6LvbfpClnzgegPzsLKS2JxhPBE1oqX7TSKCe9a_GSnJEJItF4f-28VXgx05yvQSKdcsjTYzWzoEEJIYYITzTSubU2BMeoA2uI1
VypKC56MmHk-yyFBAiM1qeK96n50pFIqL6OSgPdAy1YDRBMWwTNbkTnm8YeGarazKr28JIt891csxGkaNWehHbhvftMV1qdMBObJRAqJDZvKSyiWS4O5Dhlm
M02ZjHnHYefuKDiDKKt4OjjVQUYCuQgM1K1YrVKutNBaS16jhGCJYufcvkkJkVwyqp86BG9Boz4UA6FBKSTIoQpO1GMDjkCaOiknvK5TVqfxqaAzccEQECt6
vTeQB5j5m_0xCnshl6sNIfPsX35Xb_SM-dgSiup796g_l-Rami9SFYSvb6duWKhP6-IzVKEZhUntI-BODTW8SpkvbNNOAuoBEHmJPTPdYSd-n6Wv3laofRUl
qRJDcuM27UlXaTFsaW38sApLt3ZcEixeT8BX3tObHzj70UfvZlYMGnXvTstSDUXat9szcZ8cNHdBuRgobkDqwaYqB_qH62yafn_w8t196HRcatbmCgIrnlG4
bTgRsdFqbhNAsX7zvB4RdMcFLTh0TaNg2_FPkcI4RhXSZBusoCT1DRS6zNnzU5AM7kmuhZahLedUzbwXVM4-NITsWIvHZzT6PSYs8s_Dek97mqJso1Kzyof2
XprEUh-HWA01_Gcctll2VBPkxnnTn9TCDHAJUM6LBKTYDYjREcUKb5Aqh18ixZaCW0QpUpiEpXJ5BR6rNzSZKsbbDrkOdyxfDdsLPJ64qiX09QoIaGHR3cWX
kPqagP9aTMma1SdIzf6CX9LJ9PCiEXpPdtLAZk_n47zB7tTbM4EEPTytASTnO7xaN3r-tk60pbp9WJ77PSSSVuii5OZPM-sZyj8va0KsVQjz92-QetkRlzNU
9RnwZhGCnijiLF4JkM2KYk1liABuktpwLdj7mUjBaxVQR_o1L9yMRnIZiy_9M-sha7j-xfo1iKouapHqYGvZRoZkHVBdzuyvmt137il68FrxChUagSJRMm3k
BSJZyNWy7e_7u_5uF7u7
}

sprite $CriblSearch [200x80/16z] {
xTg7NlCu40JmsLrrovxtVzlxnGgHWmrN00VVfpzDwHbsvHhyLiCm3CCm3CCm3Ef2dcPEENh5LLbSk9KC5-GcxinUS2rMU6Xsk9B03sN1LSZ4Jyo6Qz3AppbS
WSxaruCO3G2SuCPxBp2SIPvY9AyY8keIjmplI28dGwTP0IWLDovGSQwoNypk5yIpl0-VL9p3UqhjWrD5FWIiH5Ma9UcbodYI9ZHcMFEOcRItRzvUaCFufXe0
SPchifP6oWTJX1uhYRIf4fBIUfKonqXtVexoY240_Cmk223viBE4zXXLamK0vfR30t4-FOVnRbP0odx58LFlkautEI9WcnmAE4eRlA0SThZyTPl5sI9u4FfT
PNeEEps7yYu2KhbdWEkXkbHsELvPZx1f_i8d-nioEbsYYiM371ueUQsO2CuozTvtF1GtSqZGQIQhWqoi4m3X2ieqrQe0F5bm4jcymyfZ2ip7A_KrbeYqloj0
88f6JbzQbJxS2K3emz_9zpSO-O7QCoRyKh4tpCAF2BH7-fqo6uLmRtyZdibNrbjoTWu3ZdAuGd9ExkivpCI-9uVy-noPImgfaFBr76eUNvB-Sry59W40iQ_N
GqJbU-Qv-toU2vi93vM2xjNpmxFn_tgvI-AP-U0LT-9yS8gLAQ0-sEDUJjOSwxLUNxmUd2ZOaCAR-DIkiTqp8P3q_LvJgqV-ldMIy4u_tIwf--qIpunEwco0
n7lIv0JGGhVcc7nr8W98fHU8sPgZ90KqCU0RL3R-Nsydvkr1YK2thv8ojkjcmIhIRUP7neqioqktszlSYehLChrTvz6nj1mU3IisEGohJ7dPVbGZlf99-dyU
S6tG2CjJZPHfcqEnYfIJzciNDZDsh72IfvQCBM4i9Dzoe366W-Lkf9nodA5V5t0WjQcL_PsrZelEpDxbSFJ7EKuvxbEsCsLFcG6ZHsSiWfipwm7bc_dWE1mo
ttWS4UOMfWkqv_dHx_g3EH2U2d0ZgYfe4kyo3Xb3dxLDlETmsnnjf8SvVlOuTIF7NIKcBKQbhcacnOq2y8phS7wVmzqRJducXrHkP6VQpXiiSLCkstLZII4M
qk76aIc4LDbMszdxHCizHnEun13BjClnm-TnzB7ATtYddHwPWg3HE3_sgYIIJ0gV021bF5WYMHo0cD64B3z-NYq3W6inBa7A9wVJSZLSHkIH2W0gk10jFE3_
9v_BgBWYZJEtak6gr8LKbddAqId-FCCm3CCm3CCm37y1
}

sprite $CriblStream [200x80/16z] {
xTg9TgBC6eNX_Kqr0ll-x_OiYvY5WZazH3kkdwU7O8KCB-LOY9_fT3gTJgVJwNGwdInoxPnxIQvuLrwujMJ3-v6OkTCTRyPd7cg6DoAL3sMy3PlvXIPu3ywl
JVh-6SFy2o6n2009N6XA2VBQVEF_DmdkM2MhRWUA072EFSKpyLeoynUqNNmI3JsOMxbkuBKQVqd2ZIbZ45E8EyJCPEtmq7_G4Vn5YWsbOT0owz8hjDGnvAof
Kb_U8Gj_KJky-i3OnJ80-UWme9UNToJ-CdlGuH3TT0YGvz7nwkceoSqyyimlrQFh5MmKtNOalhh3MKpK8i8Lq3J_wYrapbzqvFxgZgIMfrRhH9B5W9X_xIxB
6I8H1nq6MSQuYU1LrFL211fjVPeU2n_esB1EDeDDxEdpEK65BwKj3G3o27yDKOkKSYTxKcWTlvfaFY3O4bd___Wu009L3A-SZaWfXObOlXvTPe5r7bByK8Mh
7YA9B2A5dEpeoZN6Vwg9dx9evQH8lFH0qdr95lnOTuSxSp4uoTdlNwzd1I0_lcC8939Wo_LbkQNAotRsKH0L6z59zcG_huE1J0PqJ4GrR4bCt7H8vvHpdTXn
uVXBfcRVra577I4JBwPaWa7NbQs2JvK95shZVmh-ZahujzpEXqMaam7fl1eFzhkL4-64ZQ3WNwgyqw0S8PK70bVASllOxcO6m0Im21cj7ia57zGZhfTC81vX
OpjIoFS_Qq-8zHTEtBFZ-SXS0K8VHq0_rv9cNoiQXt59wUidcyWwxj-_nA1ZaZ9W4-zqsTy-1cbK4G64gLGJ0M1i2cWVJP1g0ZWfewDTygImj2o0pnJy5U5E
MnSUga1YuSOKs93EvfigkNw_YbLV1EllV3F_DiR61yZoiNVGlt-H8U3NPo7YXSF1uuGKSWxPTIW6OyBGADlvZz4nOwXqhB7f2KjmYhnv8Y9gfe83cXOoxZhw
viWFcRRlQ1WozQCZFs6PeNrEKp4CWmNkYKyijnq5gynFjaQNJlAZes38b6_gGE9UWanSBINSp3mrqh0ddNhOKPZYWuwBKtAp-EZ8tzuXC_SCkX-kEEAC1_EX
DqShuSAUre7Wtgm78OeZzg1Zz7rQYC6Vru7AlIwGnXi9Xn8TGDbr23k6WSHGdzWXyuDJD_75EhKg1cTVQ-Ak0ub5SA406csT-oTsm1wTkf6O7fqtS2ujfpoD
_G0biwUR3cJEEUKw5a-Cp1wjspCxu8zNgzHJgIKdnIs9EcOfDcT3EY0rORYESKewjjjbKr0TcxrI5M0C19uNChdWI_8kvpcNR8At8fMFj3ZV1_1FlF_xCgwi
S6lEXdTbdckVh-zR-WywdKwdq-bqEfrEf_y1
}

sprite $CriblEdge [200x80/16z] {
xTg7agiu48NXqzsAI73U_satIF8mffRnHenhzTqmEVm58aZW4qpJD4tJD4tJDAaBkQnRoT4hFfL5Fac63-GAULGzFeoDYgFgy44aybGIV0ejx9RWuyg3glWC
kewA_Wi77Xa-WMviYW2Y0ZWUERnahLQS081uxmNNvilApY2Pt1oGUQGua4GkXfrc1Q3ZCrsWubg5NG7Iw34UhNBS5QEASpXIwlxAfIA7064J0JMN-2JZILhG
cQ7rc9dqNz-ylg73k7SecuH6qlaG4Neq4gcr4f9IUvSonqHtVKVXGmBg-8sbhia1uNJFKXewOJMj030w793gvHsEE-aR9u-0BCyX_gGZ08gzGm5FkRgZS1S1
zT41ocPv3bcn4pfqqekUEjpb7SRlmk7iVWXnsENyGuSdBku8VB8u5GqSZY4PEsLKiVW77HvO4Y3q8hZAofySGmGxpMHrqCAw050sKAPIgm3mFVm2-q3mPg6U
XVYJoooH_lzusG02qVtZ5t7Vz_ju5gAn3vZDS5DXPAXpSXPI3RUN-kZr95U3R2U3n5idU444Rv59kZ5AAX3vimKlaFY1gHZ-4mj9XMUZWFmCNvGFyQzqMBXT
HqsT__CT8Yetsw-KwMI_kiCuvwjn_hhZliVTOjYTTMX8qGcstY4-nU1_um00BgPWjpmF7ZiYMGgh5lRlkiQGoMq90BIobetfWkkIuit2-le2wwmZC0k0iAu4
82pIQW80o5QrVKgyutMYSh4EW72JnsO1u4VlilKXEDwYtl2wNVcWW6FuUc-hqL4bW32ZSVHtkuywRez0GoEj8uoEJ06CGHh7XF_GShYl3T41ihsuhtqU7ucA
hdKOKuzQdk__qotd6Sux49cT-Reg0CVa1iCb6sIVz_5jtiTEvtsE7V7GWSYD9SWO5hUTXpjsUBhlumD6nOCoNpql6Y4Zw6HUzAn3kQ1nlQDax0hrNVFKUZ9F
VTQ1t7SUgQDZjVtgsB7q4BtZke5ogrte0TdxI9_vVLaeQT_hc7n8XNBvEev_kI2bvI40W8ILN0o-0D2b1EzzoECqhsaZcTrrwshb7woh2GPbHEVfqSaxrZct
VxRE6QXVHG5N-_VMdHC5dQF_uES0F0CQgwjyydCPYJLu7ogBuZqiRl_6Sp8MbxNaOEz_RcdjpotzFqpJD4tJD4tJDFqA
}

!define AppScope(_alias) ENTITY(rectangle,CRIBL_BORDER_COLOR,AppScope,_alias,AppScope)
!define AppScope(_alias, _label) ENTITY(rectangle,CRIBL_BORDER_COLOR,AppScope,_label, _alias,AppScope)
!define AppScope(_alias, _label, _shape) ENTITY(_shape,CRIBL_BORDER_COLOR,AppScope,_label, _alias,AppScope)
!define AppScope(_alias, _label, _shape, _color) ENTITY(_shape,_color,AppScope,_label, _alias,AppScope)
'skinparam folderBackgroundColor<<AppScope>> CRIBL_PRIMARY_COLOR
!define CriblSearch(_alias) ENTITY(rectangle,CRIBL_BORDER_COLOR,CriblSearch,_alias,CriblSearch)
!define CriblSearch(_alias, _label) ENTITY(rectangle,CRIBL_BORDER_COLOR,CriblSearch,_label, _alias,CriblSearch)
!define CriblSearch(_alias, _label, _shape) ENTITY(_shape,CRIBL_BORDER_COLOR,CriblSearch,_label, _alias,CriblSearch)
!define CriblSearch(_alias, _label, _shape, _color) ENTITY(_shape,_color,CriblSearch,_label, _alias,CriblSearch)
'skinparam folderBackgroundColor<<CriblSearch>> CRIBL_PRIMARY_COLOR
!define CriblStream(_alias) ENTITY(rectangle,CRIBL_BORDER_COLOR,CriblStream,_alias,CriblStream)
!define CriblStream(_alias, _label) ENTITY(rectangle,CRIBL_BORDER_COLOR,CriblStream,_label, _alias,CriblStream)
!define CriblStream(_alias, _label, _shape) ENTITY(_shape,CRIBL_BORDER_COLOR,CriblStream,_label, _alias,CriblStream)
!define CriblStream(_alias, _label, _shape, _color) ENTITY(_shape,_color,CriblStream,_label, _alias,CriblStream)
'skinparam folderBackgroundColor<<CriblStream>> CRIBL_PRIMARY_COLOR
!define CriblEdge(_alias) ENTITY(rectangle,CRIBL_BORDER_COLOR,CriblEdge,_alias,CriblEdge)
!define CriblEdge(_alias, _label) ENTITY(rectangle,CRIBL_BORDER_COLOR,CriblEdge,_label, _alias,CriblEdge)
!define CriblEdge(_alias, _label, _shape) ENTITY(_shape,CRIBL_BORDER_COLOR,CriblEdge,_label, _alias,CriblEdge)
!define CriblEdge(_alias, _label, _shape, _color) ENTITY(_shape,_color,CriblEdge,_label, _alias,CriblEdge)
'skinparam folderBackgroundColor<<CriblEdge>> CRIBL_PRIMARY_COLOR
@enduml
