@startuml
sprite $WorkerNode [99x80/16z] {
xTU7heDG30DGs_d_VtvApH14whpXhUkoIJdiWMiYHLD4P1YTaOLk8xfp0S59tCaa2FOIGePzXB26JGI1FMeWY5E64NKVxKCZY0hWi3qQGvHbleeGhm5rlmqW
JWkhyCU4Jakg23ybU6UVZoJuO6OZeHP2KYyXPDH828xw2AovWD1TOXBiFnRHUqOvjD19EB-JGF-T5c3K21X2271KPmmY0biwdjtrRQC27FqUnOeE8Egx5BQe
vvss0AE8Yh3z-o9YA54H_TflFKVSWFbfFub9w8MgnmIobVjR43NCAgfKFIQe4EXwxN-kwqaYJCZp19Sy9CIWa3s1K1104Zb8GW62NXSg2TxA0YP9w14HkFqe
xx8WixVkE_4sPE9GvlakUOQW40S2z9qM1uBS27TTyf0W6UA941Ho-KualH4oyTH9A-_Pj4IQyB409Hu8Gk4oGKIuf10bJ2S7H4L8EUHMf8SpscefTztZVxY1
J68Iam3KB0X0Cu4C6m7Xadm1
}

sprite $WorkerGroup [99x80/16z] {
xTY7aiCu38FX7mJu_gzyarYZR5zbJheQR9LfytEt9q3vN0IWzCaOI9zDKNqwv3YXyqJzEuaN4O_a515cwX0X7l4HmY1V0HqX11d_5lW0OQWU2P3TnEoQZCse
xSHewl600RAP2D1Nwqbj9Wmr93J9dSJSCm8yzjjkOkoPb3mtOZFH0hyRR2QI3l1-axoLaDxjVY0Tl97mrH9q1UfEPXiHG3TePeYrZQZHhHYHBvTi8RvjPa2R
205UcBvChAzj06qX1FY7oWOYIRwlv9__7fNIIAqLdoV4Z5UApnFcJR9UN2VoMBQWLelhnFj5WQmMrua0xnvwgyLrOZpPKfwZbU8wCH_MpBzQAwuJWbkjOFxZ
XUAJX6UNCLughXDZu_Fbwr-0RuhhnDpuE5-Sc0NrA6eMdpzfyxvbk4TV5F_qfJSwwd5FCk-Bpn8ZGAuKe-t8s3cpM3jkWxgDgqRoliW_-MRUSOrulVZl_mpa
HMGduUgskgEt0lr5B92V9q9taVQlX75YFKyqRbLrLHkKhf92HnuJPDtxgaQF4Xdpkbjf5VW7eYfOBOVSsaXEkFqNSfFHkBzdB82JCQ_lat6R7mZBQaANkkzM
Tr1r5v8qMvCsg6iSFJE9xlw92ELMwJqXfKj9Cednm9j4beaMwMBkbukuWI4TJy9u4hTIgSVUl0O_44MtINU1SX7gLhM1QkNjpRxkn9Wt8DA0yY2sNN5v_ERi
3MI5UDrfNyIBy752EYqOwgmG0EKWOFwI_04
}

sprite $LeaderNode [103x80/16z] {
xTW7ZkGm34JH_-l-TzvaGZOn0ensscHE8DKkw7LEF5NcxhAK1vmyKVW8u__ClCpBo5BUoSXQtiRGwoO63ZjwN84R65bArl9wPkoyTVvMnYdZrGnJXaUPbtd-
Bl0yaxxnRGzF9un_vrFdtFaxNzRcJkvXI6AxA-Fr39LKjKOkPsHANyqm7ozcSBgtNCf8fapmGgRlPZjo2QCcWNPICqdKamnAObUwKw4p35yZn309dMEmRweX
EWiTPtHoQNBrfI40OPiNK2UXeupqk_CwojVGSQODRN8IEiO8B1DW7mI-XWun95f3I8Nfnthe04CajBimopmRAlGvep4KE9X84ep5P316ZrvfGh1TQS1oR18w
m0WM2EsasH3Wp_iovMLUXiyUOp1vUiRh6KunWckBZ7KIOyMmc4tIIhhFm3Agc41r8mbWvPPr8fFaFfEaObBBzOaJHtpp6na9JRBB2039qYm60EoCf9XGsu_a
BhEkN9cAToQuOVhbtM6sJMet8pD664b7SeS180AuD5BBqJiJI0AZOVNEpClnl_g7vR_wdFOoByCZ3F2C0jwC27m7
}

!define WorkerNode(_alias) ENTITY(rectangle,CRIBL_BORDER_COLOR,WorkerNode,_alias,WorkerNode)
!define WorkerNode(_alias, _label) ENTITY(rectangle,CRIBL_BORDER_COLOR,WorkerNode,_label, _alias,WorkerNode)
!define WorkerNode(_alias, _label, _shape) ENTITY(_shape,CRIBL_BORDER_COLOR,WorkerNode,_label, _alias,WorkerNode)
!define WorkerNode(_alias, _label, _shape, _color) ENTITY(_shape,_color,WorkerNode,_label, _alias,WorkerNode)
'skinparam folderBackgroundColor<<WorkerNode>> CRIBL_PRIMARY_COLOR
!define WorkerGroup(_alias) ENTITY(rectangle,CRIBL_BORDER_COLOR,WorkerGroup,_alias,WorkerGroup)
!define WorkerGroup(_alias, _label) ENTITY(rectangle,CRIBL_BORDER_COLOR,WorkerGroup,_label, _alias,WorkerGroup)
!define WorkerGroup(_alias, _label, _shape) ENTITY(_shape,CRIBL_BORDER_COLOR,WorkerGroup,_label, _alias,WorkerGroup)
!define WorkerGroup(_alias, _label, _shape, _color) ENTITY(_shape,_color,WorkerGroup,_label, _alias,WorkerGroup)
'skinparam folderBackgroundColor<<WorkerGroup>> CRIBL_PRIMARY_COLOR
!define LeaderNode(_alias) ENTITY(rectangle,CRIBL_BORDER_COLOR,LeaderNode,_alias,LeaderNode)
!define LeaderNode(_alias, _label) ENTITY(rectangle,CRIBL_BORDER_COLOR,LeaderNode,_label, _alias,LeaderNode)
!define LeaderNode(_alias, _label, _shape) ENTITY(_shape,CRIBL_BORDER_COLOR,LeaderNode,_label, _alias,LeaderNode)
!define LeaderNode(_alias, _label, _shape, _color) ENTITY(_shape,_color,LeaderNode,_label, _alias,LeaderNode)
'skinparam folderBackgroundColor<<LeaderNode>> CRIBL_PRIMARY_COLOR
@enduml
