@startuml

sprite $WorkerNode [180x140/16z] {
x9k7RWD124INfVt_5wTt8jpjGPgd7hN9tRijWDSL8OGGGWWXX112jfaEI-pvGWnABPOVn5upqCXlN2Pe4VaRWzV2im2kjUM_-CONkU82Bt8b55_aIcnqaKDt
L46WHRRcpmWq3zGmjHRln1K7rDhYRoOxuYrWQj7R3gT5nN04ALheyV_TWq9h_yPxYs8z16z5FgIrF52DumKLHyeSUkmr4IQphQFH0CaiwtY2cPbPP4BcMaUo
EPabohADdbaYlz4PcID_iYTajln5JCWS-PkDdtdd7mm_i-OV73zplKVnETFdPjsOjpvp7-HveuOEdND-re_piqoxfmZlWrU0cP7hI3kcrUl4nzL5BNyWh3-V
L-UFAzRvsK_faxY0zgtwrXzoVx3lQFTjJ_QxhprNK3_JUVCR0ZudqwmgO-QHTDpSbt6-xcg8TMDgd1UzgI2s1c1HHCP7l8gCpuvxYCpVJH1222644FBCEtdW
Lfh3CDWg9Ez_uuKbEF9EByuGHGG4_lgSy3sIfzNCh67fwqj5_EmJCT_wIfRsd5dPGrxe-fePM3zKx6mR-zO1Nwyb52kRdLf_min_ommLAy1vmRBVOqx5pMoV
pDnjC4Neeob92ROD36fcvzu4nMjpc0sqDdTwESXq-GGVoHLrpUIh7m251_TzaCXYTg7UbnxasGop2Mtkj9CHe7o2BmkzYy7iwOfkoxwVtGqlOyfxqshKLBIv
qomdlu9FDBp9WsFTysC15qwDQfpDC2-opQJjbDolu1DDBtpFg3SSahQWX0R15i_cPdPbcKbxW-unmNU53cspftty1tEObQ5eqrfVCw-KRpFf6EO9lX8JA3OK
2RIQz93jBMdzZDOtc1UvpQHTUPWx-59WDoz5T04B0JUp2VFhv3UPNPJTQNPQVWLVANIEda_xCiXkvfLTTJU3_6lcffFTwL2Q9ULNy9LCRCC-Rf14NnVp-IFD
vXlCLlb9hvG4aq_m4sLktz_yJjhjTuB_jGS7100040p0-hVM0dpR2000000A
}


sprite $WorkerGroup [180x140/16z] {
x9hPWYCX24KB4Fp_Bvvz9dLidTWRpOFdBQbD42w4obMFm-5mE1mEXyFXS3Ye4RtAutqaodkvlwHTjOa-GQxAj3x3hy98zDv3NiItLaz0Ou2NJaEkZ-5YjHDG
f_5o5SMGR_owLNQpBB-lI8C_HGLXNbBlv9w0uZVHWzuLr3cKmn2OKrld39q6mgOGtFysjdJKk_fhNcjq_TYmuZdeo47OKw-dkrlWIwshNrDOqz_EgTsiqNF_
bqCGjwiuh-LhDzJekPv8IAdEEQ33SztsxhMohprgjDnv_7RHKeBN_jKF-y-i82efdd1XP337QeteP3dxkhVKfKPq_cJ6Q9M6Ty6XdEZ0vBolW_xRteyoRexz
kDS2EhUj1r9YXivrxDkNojltkupUxUTL6RtRrwzAUYU_UUq5LoKE1sq3zfQBD5tYYEy97R5qYIEwCMSQ2SbkvKZiLKpYgMuEy7oZjKylqlp1tFvy6Il4s2dr
PS_-Eq3E6JcjoPtexyyHUPp6vqyI-Ur-EF7R_8djsllqQFgKbv6xlIn6xZpAS_zL8cQwyPy7XJrwkoX3xxYoXbe6QoOwT_UvmveCdMCvZEL6um1_npP4JPxE
1JgDzKO7Ntt_HhBUTWfSENPdEarFVgrZIzK-FQBX5QmPiJwNRlePEvVMQZWUZrXVArtCaY2leaZ0pQjqeZ4woG59hDpYqSDmvFdkgFVkYYFv7T8JrLX8DrKZ
Iw7N8jmU20uk8psn4ivTsVe3dsv2MXLanx6sHFeTNQoEbkHtTemOxtTY6GMCcFmEsk5IO31gdPaPUgSt3A4B4EHDRoJe7BmAK0x5HXIsaCX-YKBQMmOvTgNH
tk8npnaZxJy_T4yanr3FH0O-xwB3uJkxPO4kEGp3uCYa-zzulzYU5oz3krmzi1lG_C7fRzIZHuyUYKb6immmpJW5mzTT8jpaLp7JAb1sLEedcdmDnXXkyUlU
bXdzgRQZ4z_FRFGTuDHVm-pS_yCzCaOM0fzbHeKXH29NxwdfCWqkIvE8giHQoEMrrykd1vmGLYuvbRKW2D5CihciakXRf-aI-Jc19I4M3BrbGmi1QW_0gH3F
BC9jIQNOf26IEm7qC3ahDLITfain4qiOBdB35jehQr7HqrXVw-oqsXk9NDKrC33JiICWMpYTZijaxi9BAikmuYvGr8gZKw5q6Nrbi8LEvodUqku_NIQpTk7b
3GrG4YstiqSNIwV2g9iG3D-YBvprFUSMIgt-qsKofqs5IqAVlnMMPesWn656H2QkfS4yxyV3F5qcCsvXFlUSXx6FL8KtPbdI1-zrMqrcfNNcpVmf5plph5nN
vK4hg_0CKYEPpClF4WXrCkzYQVZ3F5oCcIMptt06oxxyGMeZ0Cauc16nCmTaPvZCGff0d7QOXulIHRoOQLLuLM1K4itkzMqmcNi7I90qJERJmsN5OJukoyWm
IMODSZUwNn1yRnNmfQQT2AKQ_ZKgvb-WXpdUjGS7100000I0-7_Q45Lp000006
}


sprite $LeaderNode [180x140/16z] {
x9XLiWCn30J5kl-97wCpOPgjKl-6sif8Qrjko30Cmp0Cmp0Cmp3e6rlIzQp-eD8t8MxP_qWJSZHxXrHX9XeImals7b9OgTvBSLSPawpAMvFsFe8B6rhzGqP4
RI3IiLIq-2UUzd7dLg72WJDxekiKvoAB1d0c3uS3P_Pm178cdnnvcdEEytKKSEOQ79CD_hanyvd_EJZx3OdLsRz846VE_JDUZ0eNUTmvHNWBdVvBWZ8p9XeJ
Sxznqzi2JAdmIsDbVkdzoloPJbfV4n4hK6IJDpILiCGkxtWjnYuVM9Vmi2fPr8zmsB8e9gfD_g3sXYuTIjQ9SKAVELSlwX9Mt7F5amviu-rePJHufm1dc20E
S7TvE-nKej5yp9biI3iImSwI7IGDg2WmgNlUJ96CEEzFONfednx-f-3rsfwPA4UFma1OP_Vxl_7-o0IAAkBiuV5UT1sMQDdw87Y6r3HLyw3jo9gVif42tQ_W
FI7SFQ0jtY47_9SGMsWLyUc_fK0dbxqKtYuElVNjnVTHQI9-qpCXOYQ2lFSpvILLgsH-szDeegHMi95UlbNmujO8nhURG-7Nzxb3l_Eb_FSsHx7MctGpgRiD
xzD_IIOExSjb-m94H__PVqTm0J8J48DkLzcOlyI2k_7zhPKEkcWqQHsSjoTxRxxFuyMD__g_KQ3TVZaRyqV_yqhQxMd3cDlowUF6BnrPDEd8jNAJeSfzvbu3
F_gV5FANa2FFQq07KkKSkRByM7tQnl_isKX7JxkYFedXPEKpCchtuJV-HrH8sj6_OBNG9uBskW6Z4pBHVT_udpmRUItNrrdJs0On48nOlxinpq96k_6VrsmH
BHZ71fyCDGSdoYZLMMXEikQqyIluZAgdseMegXUxwVnR8oil1DLYgniIgu_uykS3FxWv-fiK94ESEeVdEnaG1Oc26yEBByrNGSvNzqDIXhidHBAfNTmzPij4
pxtvBbOt81VVD_u75MYoaMlbiS_d3JhyR6bk_7-DZewEZewEZeuqN7wlxajzs1RsNOay8MF-WMFgdPraH_Nl2eFwZsF6luyPLV0wi_dOY-hXDiTjCCyQCz5H
dpHSJ3uBVJxDjPZxa_KfPasIH6zCaFGgQX4APQbX6kc3MPqfapdg2TbDadanEreI3p43tW0Ra19Qi5Viga76MYC4qdKoIz87Sp1KD1dbfTRCjRbPu_a8S_HL
RMsSyoVOf5rGiTP8Nwt9h81sPYNwi8bUJRIOWL7-03FOhnX3XKl8u5ngYc6M5cvsvc2CXGZQAEcBKTS7c8aeWVrDIN2kaYXZhQd9hCm2siMSj37JiefV9PZH
b8m7c9NuKcqu8YDerRN4M6gsp4PyCUjWniAChWUOLuHar3jUwuonpalDZbc2iQnpq4USrCgd7jZFlOqNpjpFysDtgTao2nXpFzSJHWpEty4izAypZpO-rrCB
CUaTPgtPCnl9-RcXm8Yz9Wzs_h_0ZAueAhCWYY3D0hL5jCOpYtFMR9ahgC9WcZbe5SCjK2NUOWVzB-oDhkgJ5QZq42O5gY2PKYMpPizSrT6NjHxH51LwbHZc
-1DICnrXHJgIJSsjrhjCboxoVzRHqT7HqT7HqT7HqMy
}


!define WorkerNode(_alias) ENTITY(rectangle,CRIBL_BORDER_COLOR,WorkerNode,_alias,WorkerNode)
!define WorkerNode(_alias, _label) ENTITY(rectangle,CRIBL_BORDER_COLOR,WorkerNode,_label, _alias,WorkerNode)
!define WorkerNode(_alias, _label, _shape) ENTITY(_shape,CRIBL_BORDER_COLOR,WorkerNode,_label, _alias,WorkerNode)
!define WorkerNode(_alias, _label, _shape, _color) ENTITY(_shape,_color,WorkerNode,_label, _alias,WorkerNode)
skinparam folderBackgroundColor<<WorkerNode>> CRIBL_PRIMARY_COLOR

!define WorkerGroup(_alias) ENTITY(rectangle,CRIBL_BORDER_COLOR,WorkerGroup,_alias,WorkerGroup)
!define WorkerGroup(_alias, _label) ENTITY(rectangle,CRIBL_BORDER_COLOR,WorkerGroup,_label, _alias,WorkerGroup)
!define WorkerGroup(_alias, _label, _shape) ENTITY(_shape,CRIBL_BORDER_COLOR,WorkerGroup,_label, _alias,WorkerGroup)
!define WorkerGroup(_alias, _label, _shape, _color) ENTITY(_shape,_color,WorkerGroup,_label, _alias,WorkerGroup)
skinparam folderBackgroundColor<<WorkerGroup>> CRIBL_PRIMARY_COLOR

!define LeaderNode(_alias) ENTITY(rectangle,CRIBL_BORDER_COLOR,LeaderNode,_alias,LeaderNode)
!define LeaderNode(_alias, _label) ENTITY(rectangle,CRIBL_BORDER_COLOR,LeaderNode,_label, _alias,LeaderNode)
!define LeaderNode(_alias, _label, _shape) ENTITY(_shape,CRIBL_BORDER_COLOR,LeaderNode,_label, _alias,LeaderNode)
!define LeaderNode(_alias, _label, _shape, _color) ENTITY(_shape,_color,LeaderNode,_label, _alias,LeaderNode)
skinparam folderBackgroundColor<<LeaderNode>> CRIBL_PRIMARY_COLOR

@enduml
