@startuml

sprite $Parsers [137x180/16z] {
xTm7hiCu38JXOHdU_yPR0p15Jep48eLT_QYlveFSArPCdL4NtGIZBEgZuZcDdbpma4VMEIYCnhHvF3B9sRGtubPqPpaWpUM0h30a6lrnWKKc5np60kdJBB8X
DWco8Hko8JJz8RyCulWjuJKGny_n4WX-Jw-041Tq1SG1GFbrrq8ilauMXMp8Xcp8XhYUYhCXYfFvN8ZZTFyJ274scGi9F-lWzCMNfrfmFR8X6x8X75KFSGop
QWXna1T370Vfif2k7IDMGy9qa76lq6eX6x8X6x8X6yA_wuRalKEYtWQXuJ5Z2yGmg1v2mH8G1vQ0EDQ0EDvbPH3YVLu54No8DH33fxG6Wi-n0c8up5noIAP3
14Tv_fJp8Vx6aUDbyo7snf4ZelCXyiwHpFcGSmvmDeJd7F0wYBgzE3eWcajGEZeWbhj7wMWQaRzJmD9H28ddtGuREi32zOZmpVgsTCqgF7JeV0Y1p0ySiEgj
huqTOFd-YF3n6uNx8spOGslUPuLy2FFtuWDNvF4xnF1x5XT0GkSwpaF2PPuZ8TV50wz7CMGyEsdBpTTyfYZRxW9tVJohs039-7SBtnU_8Hko8Hko8Hko7w6K
HI348X1R1IABG1oBG6GHYAxr-WBqEvQ0KB44n8058Ax08OIkKXEoLmWLVKLcw6mLHq8SQq28HI2w2WJ3z4HoASJ7ZZYHNmgnLI3Q2f5L8BO8H6oHUSJl86o4
IDn1GleW_W3nDeZ-EuSoRcaJH6wVRN6BqW8HthOl6YbfW6WkAKo9LaFa_duNYunI2L6FVnjT6gRRNHudedsJysKVLQCtjhvsSpmxUBCZisP7fcmyQzLFSS4e
CUTpSIP-avl-z6eebHUSOtuwchMy7y9SnbeXbZDsAqGVTYBQ81JSvrqGnrFM0p6yf6o0A0O9go4KZFDQYECmguGOtYGiWoZU9go1KF0fhu38kL_wB_Kd
}


sprite $Lookups [134x180/16z] {
xTi7hjj038JX8Rd3-zyuFI5aGL6Wjrvk7kP7TV-iNh5RvZ5M5U70EGlcuiO94jaH3QYCsPIZ4DbNd12j36PhZk-Dx8qrFZgB6XJD0oFxSrZs5uZiZnYvGRih
f9122Ycaa48AAQIGGWeff1XkS_9uhWZCovugY9d5GqLWPlPGuPZQHnJCKtRvdNxnYlKff9122YcaaAAowlNn_IkOe9ZGF8KKLasOBZIdTYYaa48AAQJm2FSu
P00GrVqhshvuYqAAmLC60ApkNz7oebKXXHHII265dqCzV_zAFVzVdx4Qc9a_LAHXOdogICUiZ3hFVf4KKaWXXHHII2655598eRiXOmk5xw0WTb3u3WfY1uNj
e71ie0Xie73qAmRGhXY6AmL7BCcByAgWewEZme5s1GsTYaBqAnmRA8WT5Bw5ukfimdrZde9RACOMYkXK-1R38hPGS8TvnBEM5tqAbcAqAI8JaR_o9eLd4fw_
Oe_2Vdo3PJ4Q5FvhOSLYs595BJCDyAnYhIBg2y3hUuJzdnJs90yUJgHxzZPgvFH5e9z1Gp-3XYewfudAHeE1ZjSira8OXelic9y7OKnQNdpakg80Z7EMdSyL
Zk-nKr5prUXGd7_DsnHnU84z2iSnDYXeU6qiLmpWN2nMnCMhNAdmovUvJ473TMEHWlXhiKGHkCduVeNZDWjybhu2
}

sprite $GlobalVari [137x180/16z] {
xTi7Zjmm44JHwiJxtzZPhiaUQ0HMBz0VQVC-2CeaqJ2BhBMlId_CoBM_DDoMIrFWAgkbgguSYoabLgk7X0xjVk9BdN63Q4jk4776CqY3lMGrA7aE4NUxYmp4
-a46Cf2136GW0nb8XPzIr6SGnsbvVG0nd9WTXmHEBGv33ATcXo7uMPuIVlOPP9sITO8CP2036KWQGWpXfzu0Kg142bb6YHPIe4G9eKGDeKGDeKGDeKGDeKGD
eKGEMMMKA26Kg26Kg26Kg26Kg26KY26Kf1Z2snCvf23V8dJezn4wj10wj10wj10wn10wvdxaiKD_ppftyNJCazvBHyMJSlFR03mjzhuVmTDyxniZF2tslaDp
FCbgNcyEv9q6Cf2132JoX08_-_fp0r8yMuAvVlx8-HB_T8xHITLC_nh8G0Ooa0qDP2036SX01Z9BA5LL5qXqWLWJIA49nAyWiqY-q0HYFI1bQ059e0Ea70qW
bMJSGohSzWHs3qc3BByzm-aXPUW1CVI019f0q0IIU9Jv6vqBSJmgrnlvgH3h0e4KOaqWtWMIrcGVMKP8225n2IaXvFfjWCiWkTRb66Yf8F7dV_EkI0E9l_yw
ATaCuN-8crkqijqGBvx4K8k5ROEGiVBHVNpbcyFNBED8MNVtXhcqyLnQJPuwOILsi18xM8YVmfa9A1Luc4VMJUkTwb0PXlVBTLEPdtXcFGv905PwIF2hIWXt
yP12olXr5q8Ibrcf886RKW8fnrqXW9JXGRuTadYSrLv8u6cv4LAE5yKsI1bUvfiWYVzbjGDY1txeY_ST
}

sprite $Schemas [137x180/16z] {
xTjbmjmm38JX4OpkV-Con4jrDuwbhzNxTo5Fc54nDJAsHJV1euonFIfkKqPA50nvfAMZ8p4T72Ka6haHFs8av_YMHNeoJ93iII9He67EPCyRZm8f04Q1x3-0
DAGX3N4zaN4PH74kNGHHdCsMG1pdumg8udos0Y80u7mt0m1T1c6y6pygf24DQKX36j8GjvdyQWW5S-d54CLiTYr4C9lMcYBvouXyjBMcDsWDQKX36aBJcOmN
GuZPsCSZUuz73BFvjP1Gp6MNhxwSwz_RZZIa8GrfI4CQqf266BucnvJnAbSvXg_vQGZn8FdhN-0IoElV-Kw8n_Dq9qJZUR8J0axyO0i4yYniW9oe8GrfI4CQ
qf3dOKbo7g9OaPs740kI8WzD2bT0WdgIOVtCSqFUgY4DQKX36jAGXlIxd585WY8GhmBH8X1YWFHByeOQ44SDYA46H542ua01Y1lm7EAgiYMCZH0gyk8mnqf0
33KWZY8G585O5GWUfXF9KWZnA8c9k1HY3VcQL85O4OWS89u9CIkorWpdlfe7yG72D8X6sF5P8Ks222DqkDKc6o6Z8sGO5YK1eW_FENKtHFom4TFXe7KdH7nS
A1Z7t0xv5CJUoVtk65KYD-9d5ga9QaWKg22XO4WOAJdkKYOm18yITTuMC_6TtFJKinO6BjkWdO1G0NW-X8AlQJR4XtKi3sBu7VCW51ppB0W5Ove3STmbJ80O
7iNT40eUPtiXnDDq9yJn8k4sYE5rlWT2mP-oBP0JN_gWVGO
}

sprite $Regexes [137x180/16z] {
xTk9SXij40JWkPhtV-F_J9JPIDl2Wmg8YwxJjbRvO8SzWCYMKVUO5ZUzKKIR7JXXp0rChh6sAY4vtjO5f3zMINGb8vyTjCKnUcBcdnoqvJ5I8VEhnDi68MTc
RdGNY8b8so7-7I47SY07SY07SY07SY07SY070ZUjpcovgZc68NcM2mCp7puAoPCeCJ3n8OeXI7O8ncQbeXl27OxHcLICGD0_sHV_fpq5cYHLYFPFzgLFyjPm
22yrr25P4bK8o6mmWP065I4g_wSL8Vpaz4E2T0Y1q2ufGJgg7GG2qYO2gHMx66uWK7tkBv4An5AjawCDBo2mV63-iWBa_HKHkRypn3FgScwq4q8EPNUqI91y
Mo3DweVusnA1F69uGA3o29uhFxeX_CWSavI7MrASjAiNWeuICU7nLxVnRWW_y1eeOHX8m_eXrhVA5dSKnSqWz2z2jFT9nELLWdqXXv06yC38MI5Tt0S1XV1I
KT0nHY25PtVQ9KvF8GY47bOfac1D8n3QaQLXexY5-9SWsWU1zLr6SjNPvo5mOV5FG7fs3OIyYGRvoZA4t_GCFsiZrupFWU3IzCVdGzB1Ko3DSyFJv_tbG7tu
lW91Wf1e6Xxvyx1KbJCWaIuOry-7Ye102gU6nkBslSQzJO7mDptwbNysH5P3T0p2wj_sXz3BDuOWuuy1pY4y718rIBHwUDF67vuHAFHJyU6vtPQMQsttgnPU
9yXnqAkGXxUCGtXFGgIuvHE5LqvIMoOfNXeqg4vBnFMNEQL1KvweyVjtgIWC6YEG_YDDBl72e746wPwfqJ84f4GAqvjMW0nFRpQ_dP4ht8T69dpnt0Y852ua
jIbmlgJWXK5JNHJWgm8sDcPGWDoiiXXn53g4GlX22Kn5r56vyvON5vtqQA53eWnfMfRKbrlv4CQuGr67v9U08YN8-y3CJGgHfXd780qwSTi6Zy_SoC8JRlKQ
CO-pwwe_1t8W1t8W1t8W1tB-2wNk0f5D8B4Bn3Q1G3Q1s2QGa3qWa3qWa3qW8Lj0OB8398ojTaJud2J5CoHKbeNi2rq52P4j891D8Be9n6KJYAmEhH1h7OcF
GdmNY2s5w2uGsmIYlacDU8B4IWWIf2s4UCiGNmRHrZolVoo3e3NBAqAO2ycEffT_ArP052_UEMC-nF2hFYC_tS-56FAZaBOKk6bA5mHQYWNuve7vINMxD2Px
I5nIiDIH4qlVmdCKIxiZHtsk1M5o6_qj_c9z_aFN4Ua8kR9wEeaptvdjvP37AWZVJ38V4kJtCo4kAOfb49DhC1T2PhLY1IJ87sT2d3nlpeIOt0KJ8NpIC-P1
GcXi5iJbJHHJ82Rlu_ATyZS
}


sprite $EventBreaker [137x180/16z] {
xTi9RkCm38LXRe_tl_7iOzg1N1c18X85_nDyOULTfPAngcrBXMyKvhk33XpcARrI19uKhWxF2pnn9Co4tMj8uCbf_66IYu4afx522gmIzG9nd59parWYkMb3
6jAGXZIa8GtvV0rfI4CQqX2OeG04Gh_JR0XkNYx19c4nXEbVrva8JHEiX1X5UEI8U2L4XYzaGO-oXH2cIAzpcgVV4QBZITEZi122yTgpDGC9o3mTBpq8qvUn
cA-4XCJIhpKG9bRqrVTJDQGX3Mb8d-8bzw8tlmsWIMpkrM-CycyL-ow-_WDM_KVE-W_X3avuBL7qHKraXhxwhgmX3Mb8GqnLaGy1nxKq4sBqByRBc2RPOWWT
oNLCqnYVkek77t5_52Xr5wzP4vclaVoF0dWyaFNd4S85g399uGiX8U7KCslyUEkhxtirf24DQKX36jAGXZIa8GrfI4Fwdqgf20HL85840Ye2aI8GeneGK0q8
g0R4g0G4GaV8PumXCDrJA0OG4qeBWr4bGq2f8Hn585m4ObG4maKWUFzRAPP2h0f4Ko5S1I9L85faZOWMEMfmWZZdGSJF4Ck3mFNyoPop872Ny-u7947itn0a
RizI87Pi7V8Zx8S8OWJgaUw522xBqq_1X4_98mY_bHXUVebwSXph9JMb8oGx8YGx8ar-_8tOaiSHiS9t1XEwZw_9O9QBpYCqQN9cDIB6oclDcn2Xtras14n_
qrm8w4Wo8KQd66aGeMkM0m7JQve10GsI_H2bOOpD4A6xR2S4JFVfFeZHbyakYD8anXQ8q3obxzHF
}

sprite $GrokPatterns [137x180/16z] {
xTe7ijiw38NXWtAm_ns__cp1OqiEYIjmClodftwM4OKIYILJyzioqqyAnjsvDZ9o5EGykhBaOFHb-Nei8R7eJV5l4iqn3KZ_boFHNvhKzYbXzEUBV3F1LI01
G3VacFnEa0tPa0tPa0tPa0tPa0tP4BhzKrn4-pld3q5Sy5zVl-zGba4outj8ebH251Y205uA4Gn3u8KGnGG4NWOnJ4708WWn2T4YYEB_n9maB-L_vuf7NWBX
wDjOFYXQ0h4XHxwM9H2zUYjCTsUyBNs6MOYSpxxBoItKqeUOX9o_djRJ2V8q9EMGx3YJy2w8unZx898WrWT1IjeWHAuDuiZjAn98QH_44iJx894lI3da-p-B
U2Jy_DDI0F44-RobhZoxOWKGkVeFr5L4bEU_swSXDh5fdtxx9CGmjqdDD4634D9a-lI0uF_KEG1nv6HY7pKt2V4OJKiX5kD98KHZ8XP2X36U5q8WanTa7Z8_
9387eQggu1aBJZA9gkhOdTMcv_LwpZBa-hpQvAHgn30apvhFdgUwXaoz39XuWfzV6ELC0AWFh3ChbuhXQHZx5i-EPso448Ua4Q8uvlj9RxyDkBeY-urHw2hl
q9WWSGi48oUulUhDy_Lpj9qvGiiWrqiAAlvEUVRDiG9olSWYUR60Ztb8NdOEFj1O3SHUrk5wAT2_mpFMG48cDnSjYY2SWqXKGS9d8C8wIFWuH1Y5aE0eH5bz
ViH68E8_SQB6zTSWelovCqRyUakU-zJLH1ko8Hko8Hko8HlI43OanrKWlWf45u4GYq1i4GYn24GMWHZMW1ZMW2YMWBWWGHeP7o5qkoSLf3B413rbY2FL1Z6i
0J6i0N4i0f5588v588ftUNoHba9a5GXQ8R88H5Q1c2mo8vGr_jLe723U2E4H4j86iOZZtfztGJGYqZwGza0a8fYtXxK3eeyLYCKZkn_YX_cCPvHx8SRZ9gh5
8PhAeQyW9YEfyVMJC7hpmznsnZIvRUMvr4KSWB1nFdBMGQ7YJUgyLs62ZybB7g-P5zr7Hkx0URIiviuw1I7-JXiXUSI5lH338s-4K738sY14JfiWZjU47H2z
-CcR81IypMw649zItWbnV4vu7qGdVaLTJi55TWl4S9qgVgV-1
}

listsprites

@enduml
