@startuml 

sprite $Route [357x180/16z] {
xDS5ZaCn48FX2Thtl_127oPg91V4_dRBmb-ZG1pCKigv_Ab_oh-SKto3vL9hwnq0iI71xTFsr7khvRtULchhHrMGnzi3nsS2_x4ZT9P0Nlqst1_pouN88RC-
1EGmnjShSUBsiOVA4WHpvOSS8gl3chiXBkklQeYiOwv80fo-UZhP8J8G8uvBCi5LwHGIAqzM17An7azAIApDYGbP2ubrB0ZfUqXiaLKJ2ajYNX8ZoYTbArDR
5VMTp-gweJ3ZDGJMX8bTwo4mR0ZgRNdz7WBxO8x5o9ON9Kb8SkXygUOqlHHETThEPqrRAVZ1nThw8g4iFk9zZrX_JJcovKzMYy_kV5wI-TlUUM19giDGz2l_
_MzuSW0nDQSOU6ftzRidTIHSP5asXaBDTZ9Ru9CoiqK7NIbpuWAGBvWjGFc2M9ta_7GdgKA7Cl4gT2YJglbGPcd10gCBoei5gfqUvS76rX9LiUWO8WMoOFOy
_vTULFmLNRJ32f3ZyyWDP-EhvbA5EiPRrYLpUzSJGCTuox7aMbozOuP62u5YJcOUkwE2yiBWTno7BLZQdYyp9EiwmEE8PPSIEo2CiS5iQoxzahmUH5Pe37Wk
UEHw46aMdjJhpUcjBElb8BAi6T9ENkjLYWoxU7OIDKd8nUPa2pW-bpJ4iwP9bqlDoPPot4cJdM2BUYkY7qhMyzZgjp0otCtS8ml1-KEnVpWKNy3nw-DqF83J
yG3-CevfsUfZOo_Xc9QjY0tCLn0Tc7SZCk2O2Fu-2Ca1noG7xfcI62ZUY0yKRqG72WiY0vqU6UZqI0nqUiG7EZsY0myb4S4dP983WKm691E1ryWaySK5KVXm
ZoI-JYOA7rMJmByZWGXyye8OV1gE9FwbAaJWjv-8mMzMay0lko3uHLf4uKliYSFNQP74h-ea2dycXmJ-FOy4_yW8CVpxSCZ4qqyCP3H5-D0l7iTBbk8C9vxa
O0-FCrlW4Owe1s1jCK0o9UC9pWsnvwDa5XVBJbzGCYKpNL0oEpvy2PUoGSs3ad-GoChUE1Zv1lY8xQuDspiULilTaaM_8d9dpW-SP7bl5LpkquzBI_ehIhO9
oG6Gt0gaUmejUySzNo4bbzrp7GqWUJ0f2q1oFmLTMhBY9JjOiXmlP8H7d1TXTI33FNBzCL-29LkJ73y3H_UUvGknrIeYNbznLVdUwBxXhLzj-bUibAN0adMt
avH7pmRrLYM_v6blUiTDIIwTBxm6qeNsdhoxEI-vRofMhY-g1Ze-spLCCK__OUuPoVOZNOZe5oGsczB8Ykjb8duaCbZ2oJSnss_i2SdjKct-EpQ9mzRj-X8i
ERPvt_UgTFV7voHxQmOhXx8ML7BgBb_sFMukm2d9_Q-lbz6sV23tmFNuYfl9xaeU1t--KNLEilsXDf55gpYTc9or5hXzD7X2ykwNtbFqehD4YPSiiVkT7mlK
4v9RLcfRMdC2mmijMQEbaZZ6JvwN78SsOStwCWM654QonrUiM_DZs_5palV_9rkkp_K9Bba0gmjf-x1MPxNWFYFP01FZ2Hg7e2Hl3EfV9UUjalEbFpYWIsw3
ZPuRhaUoGvAT0X8oJlBs6zbBZljoyiVyu80kkUo7k8Sbd5qfuM9vorb0oVlYimyz-ZHeq_YCv0AjBai1v0gqPD-vqJ_E7daJthGsvMqKit0iMmr9BZdaQEjd
jFKcJQCTOhvjQjrL6543abiPrsU8-hVzEstHq2v16Un40X368CaxMR7BqRxrf6tcUTzgxR7KzllGXOBPicOajp9k6oNgMU7VFMPFXnxvRKGktkk97zSdOhCf
yQogT3aHF63DujL0I-vbd3_ANFrtqbU_QHz5ERHW2ladm-fPDIwvbt6nCvcFuaSFYsLJ-htVL6W0fUkv23RF6Y6EahtVr7YinJU_wPAhx12oBk0sccxoX5xr
o5gCS3FpV71Mvl6tV_JiVs_WCynm5MX-88-pXq04KtHR6GQ0R7lRma46ndJ4y4-Oai2_98HaAzOHaDVezoYP2FuzRqJn7uL335yc4yUNoIHO9e_DcICXEI2P
F5ac4qgcP28lCU2ZPA8lCQgcP6BFJLqGIgPauYEIATdh5Q1aIjR0Gko_0SXd
}


sprite $Pipeline [540x180/16z] {
xDhdihCX20HWGMJl_ug_ajxpHZnd2BFF_tJ6xAfj8oAnuM-CBksBa9g_CxIzrR59Rr-31hPmQQyPDhBs7KWS6-dxLQFKoa43MtbxnH5ueen8iPqjUXveAuNB
1k3lqaQfn47uXBIdlDfia63HVm6gpGRrHUk60AXLLCZmYLKpfgqMHb7uiXchXb5qB8gYtgfX5ErhPqoH4Kau9iHdh2CXygcO86kZg24X6gjYGcJ670cHnQDe
lEuW8zAPc61hewWWCKPHdOgY3Wr5KSiSHIaI4phWaGDwzCHHbCPCJC15VjK5fp832P45QefUFa5anf0HzK24D03m-8wv82EIm6wcupyfkcDEaTrCx7JMb5lS
CLVi3DQKMwmfXXrdJRd5cZAm5wufZc9OKnnxKhAca0Pg2WvwoPf2RVuqHN1W5MiAUI12AWv6vPh2ccBpDGNmuAMlWOJ8eXLsf-AbB-hH2hiZ1K_QIACLTaSB
LbYIGBt0IIzOOIbGBoGm6rKhB2kitiwJjGF9K67TnuvZGlX57R_dHr_pBtjdeXkxoqDnxxp_4t_BVssjT0WSuwYZiTORtGuvzWy7708EleND1GvvTWhhbhOi
PJK_7o0L_jQeg9qcn0rey-WKDkUQWCeRDPh2XAvD3aRAbUdIM8_bhL06bBQyXRLqvSdoHXZJAsEB8s3GInFl00DNMlyMzglmPyiR8PIi8r36D3UDMXgbhqtP
d5va3XWiR-3-0kW0oEYbm_ckqdYul14pDl3o1fupS9_X6zXf5HczIf6tfm7adoesGcdDD1gYb8rzD3mtazdpYypnxwsrAqZeZ3dpsDcDZPQD_RbjMN8gwL-z
eRHZ2gB1j6FUa3IosLEhDnXZ0ozz1TEUSVHsuBxqc4q25-ee6zPV-dBQDuTILNUW33pqf7_rXgJRRovzEI5cm9o_Er16Y3d81ZxrT63NMS1XpN244BN3eOIP
Fx2oHzErrhAe4MhQCi395W0QFN3KJpq3A8lMeg4M4SudCeUyFDFIzKJcqDT2ZO_1mV2g2vmDgHnhQAGu5hfCPgLuNu03xGIMXDR3KVTHIMTPD6uuFifTflFy
eyNddWsl4KhHMXRDR3IMHOFlk9sBNMOt0FFYWKvK2UNU5O7aJx4Xjnp0jNquxkGUBnuRyftRPX38-f9vbiXj9NExbmMAPx9yn-TQErdHEtyVX09PNpAdU8QD
k1TdQmaJRnq58zXWmtPufC1AvZWRmBC9daZke46C0MbxvGz3KXLl2ILzZWrf-b3QvzhTb8lhepBhZ64gnIKmhHLAthUIc0RA1kyqpbFfN5-fjDd3mUkBiW49
nUSgMio60MoW1T7yFofpBS_-bkjhvr8jbAnjbJdEnaxZD6L3wyDaCsz7_TkSm8JYYKFgsD2MLsssmGQUE7Y33PH8hHTAVfmDAs8ZDXhd3JRWC1bji04I6IU4
SjSN29pOw7WDQtJ2PRO19Cm6RQGDL2ZvQJRqEJQ47kXEGHjie4GU4KgopeOKi66xoyTubQPwbyL4xmORO9mS5OeNHwcG3U0LFVX84NFt-BebXKdXiv-l_yQ_
DkhkheLnaZD2oLhsdINfPuFlHrRB7Yf-Ex1H5wT3GadUbOrO2InNTM6z7rUhYfEV4ah0qfvEDcoL3Ljv86XL5-O5cAfcAeeAnMSgKSd6-QKzkiA6LQNQbR1M
pIZbb52o3JRWoOsVPuEFvGs6XXlr0uvZGac0PL-DREWg6qk31IwQCnYT6c-GBCxLAt8LloSRiU9YAK_lyp_mgfgRdHDAqR0ai8sDkUjPpTs_JFjDkQn8oNId
g99A3U1WL6y9zHsXv1riQ14RXanJy7BX352-WrJKVW0fjuGYMtBqio57sT23RCX4xHasl8YD3nlo11ln11jya0tziB5etCl6nEzqa0rvIpPucGsDSFbAW4NO
6Xk-oWPxQaCzNCwmCHUAi-6Fi26dsV3qRqbnB6GZjy7v9awmiIxqmqQwGKrUiPDiHFfKmjFDLxAn8VJ3HbAboIadsCYU3yxtKC_6J6YyAnluM3J6rqiojjY8
JJP6y3V7sW4sTeH-sCYgb2I5ktuEcnaB_du7zNFO7Q6aRy06LllAkS3JxvoeVMLNXiyGAs935eIIlGCRUCrSx_-CWcnCwk319shcKw6_Xut-zobQu35UP8DZ
WWRmhYsniIEK_2rhNxxC1YdkCLbXungEu9ftz9cD3Q7FlQENthKzSpP8OO_PAXl4iRfrNJPVO6DHA8ttP8FNsI15FUQhR6GuWelM1EPi8pj2PRpbsfwXgoxB
scB3Ox7AHlQ3R2opuGsXFhdfHM_7xsB3DjYGMtJPPhRowrZulRmnTKszKF8dsB3pRCIjTy_yAY5epRTBsTF-ol_1mBTBnK9f_2Osy6yU4sAltQybtpncfYoX
SGiEsnjs6o2Kv30RNFljabIS2I0Q5yb5Rlw6RasFHEtgHtrItm2-bOQ5aXt-vf6hltc47ofwtStbBc2-IcIUZF3aju8NavNDXTg6K8eUDhYVZS7pH2cNpe_a
inmbx4Fwk4GZ8lsFbIwy8bJk2YNfEGO1PyE1FPqcixSSFVigCU0zdRANzUfoC4NwB-Y6C04A9GU6bG0Rsi56JCVUUdNPllCl1Nl1QRwhZ5dmjrzsO2-uYL3-
KIX3Uy4Lin45R43ToQyyQIaOl5eEch0X5sm4VxyrfqKWfLuesLkp4Qy7tt6LG2s5CohsdkLhNYKFFkC7g6LDQHRgEq9vd6CZoIpQ9v1s6h-UCjZLPSjzNIXd
02HEpXUNWnDv3knPFHSwRWab0r80n8O0Uy-YYOCznd3bArTQEjWvf6YlUuqnmkIAcU3KgsrZmk2NGiSOhfVCQButcQIDty16d3iObYLVOFGeaxa9vvi0piW0
X89dPEWE6rR4njXYOp1L6dSSS4vRG0QLcemjDcYBZK3FGSWyjuPfiN5v04YZIeiEDlooCGRE16muX1jUpi0FX4cAKnMG0d0s56EZtMNyIBeo04ZaYT9u9fUZ
RCWcqV58dhMwCFK3oR5zhhlZR2JP01jzBlCdqXK_0MIC7ZO6m0QmyAlIPLjG1ZyG9gtk13qBlonT11P-DSC1d8FVteEbhHDaAsCZY8uk_CgcBMZWSE0zMFhH
m1Vtw4K6GWxtmk70qS3Xg4_kyWmQWu75FPf6Bi02ZXqp68r-E0Be1jre3AuwGCMHGuW1EBeT5j8mGyccpPaAVzac5u7oHZQ6C-Imxa19Z5rp3CT-DXXW0tZP
1dHY84Xue6m05jpvvCHVjd7weOwNRTaC2L8daXm3CsrNQbM7ZYimuV7EE4aCt9o1A7Mb3erHmaQWR0WmuR6-EB6F4Wi5U0I21IZjUw6IWH9WmgEep-xImOd2
7ZeaojgqpZuGL3I6P7p2W-SEd0oS3fmCl1-8ZmgZeZ4a8uFQZa2fZtepcU4OezfyrgPMjSb5OqWYi32Acol_w2uVXon-naCI6ALuT2XbAbbu4OIi4YgCb4gE
a5gCi-OcYKgM0pHcfHTj0agBYr-QeWmCQaijtFuqZz5cuVvNetsjHk1jrd-5aDbmmWOk3VQnpkANf9zfA7ursiSSA7vnIZyDAqORxME1Z1C0De1AUxDzs32i
-2L4ZnQ__jlUNI173CH05Et1-zyu38QmL94y-rzHE0i6zQ0D_4S5pkqNJ8rVkS0-Ad1iZp1Jhrr6g9BCsrjCARY10raRE8P40yU7QE3eag618sc8nV3e26bw
OXp1uG_n8pYgj628XIJpiYgICePOnFVIJobnY4NazAKXPGsn29wYqhJHq_R48c3DhtAQIqLFB3snVVk9QGXPHZ1lsZRqZg12RzjsdV-gBO8AlMtF-db9Hu8A
GUNP_7Wh1e8AGKKgscF8A47bC_Ie45G-HL1XME07BDtz2w57vGEcCUi9eLk2oWSO-iNGhmyiDdy9CxOONI-eC7_9kHYj6K7FQb0ncXc2Yz7445oC9eRWOZGn
X1QZNVcXU1qRVRbZ0rx7HZFqpEI4uRM3h-7lv8JcTIlejnnJIB75vmeqT0qeRgVxMEtGG9rU1MGTXaNROy2-bTFiHJzHlg7BmR-yfG1m3m
}

sprite $Collector [180x180/16z] {
tDQ7SGLH24DHNXIt_uPTmCzf5_bKm6X8yG-rCRUKnv3s72q-qQSuWsP_C-2Ld2VNwt4FSJQDrofEAiZdg-v95Uhnb4qboo3a2_amwaKzC-uI5Ms_aa5nIqkg
oXRN9NN9e34koAzas0-NdCFAwzJNB-QllhpuCGoiYyumq9qwutBX3LmCkvX15p4RTRJ0BUY6atPvjKqkUE8aB-w9INDCi6iEuML716xysXbQ3DpqcBYPiN6p
GhZPaRZH7pjtekiu349XE61iyFi_yEnBKfKcloQCV7MBrkvVDcCTLtcR_ql56kReDchCmyphvfVYm8pYr5OOQiNjPldNA2GyNf8t0sOGIwRe62U7rYLPTxGa
6S9c-DNHpW8qppvh96RXvXojfwcV9f6nWJWPcttRePFpHiuZpPQJvVvne-tHoKjnQjQS7CZCGqbzRdPWJiZKpD7S3CZ0JD3S3CZ0JD3S3CZ0JD3S3CZ0JD3S
3CZ0JD3S3CZ0JD3S3CZ0ZD3O3CZ0pD3GB80Cp10DpO0Cp1JDp80Cp1YDp80Cp1ojryqR80CpHs_03CZ03D303CZ0ZD743CZ4pD703CZ8pD70JCZSpD7Sh6rV
DYhDRkrGp9oNHfdvqRXHSuwkCjjMPjwyo0n-67zqr9Zz0vZv0GxIW8uLqCmYwBnajoIW8g8shXwZFelCuzhn3TizP_4BBPJCpHmjlyWzyOGFJwgs3_huKm-2
ICTmZSNNsXJCb1SnDz3b5Z7txNdPkkO0tMOLiwNcjgmPzBbLp0DqZLNCziBS5ZNh2xCiOCPpg4ND6p1_hltyFf_R2xCkQkuVS7oEbViWFpdqFQ_ZnRjtcmkO
sN0diR8vX5-0zMQEbbZ-FwuDtO2atXm7K8Bpm-AXF_-YNTMQ_M9G65tbuSO_9YS9L9LPG5gFFjdBp0x2NBX24EMvA6vt0YBpUyq1p33cxrNcgMNcKMQEAhDK
ZiycKc7s6dC-7d2p74ejGG0p9NEp5lHkG0PcW0PcIWPcW0PcJWPcW0PcJYPcXEPcJXO5Pe06PaoETjKi2j30pCdpkda2D31pCZ43D31ZCZ83D31JCZC3D313
CZG3D30pCZK3D30ZCZO3D30JCZLl4w21cP2v6Q21cP2v6Q21cP2v6Q21cP6FvW7C7CtDFILFu_jvSZGtHqwUuv6KZtKvki3Sz-GasxApCAVD73tkDziByWmz
aDDqqcUEReNxMUAfglSuZIV7d3bQxpT7GWQts7ZwIItSpzCHcGUNNc2UOQesxw_6qjolxTs53SH03031Gxl_Zb_up9IC5DTmOD7EEjeiqLlFjVLajjQGsA4I
UrzYLutirrMm4rYut9VOlHJxecB75UpbYbrYiVyCThR5dZdOZHVx_B230Fqh5NGzG3-5Tsg8zMw0xXBeMu6EcEUr9UtYNKu8rqzuyWRkQVfkwM5QhiY7rHpU
x9ntt3HNUjHt_UvbxcEC-gcJFkDlJdhCPvpq7G
}



sprite $Source [180x180/16z] {
xTm7Tkiu38LXr8lzhtXwHn8t1hwQXsy1rdzuA8kgyZ-nrbfhhRNMMckjjTPQQwsbAbTX7WdK7u0CD-6b7gWF8LmfWr5VGf1bE-eES66XRKgm3xPcFSJvYlcZ
0_KubJSor3D2tYVgEIdlegWdWNvUT4avBu3y3K0mdrlopQL5NuH0vHtoazwqZtlidzrEb9nVnbZMRq2Kd2etQ2Gob6Okfmgpg0OcrBmNkt2pdgp2JT4FQkoo
BuRP-UMI-ymmePSdaYqcBtROWOcXERldeYqfdvzTUCiEc2_Chh5el7ueqU4pB3-n_zLiD0wS7raTY1xUdDPeT1uv_c4oMiziosemEWujCtmm6cr3zD7QXfa_
sjjM-AEp7RNveziXa3-w7tFvewDD3VxeRFyQ_D5ejt3uezkFyqThcyxyqNRFojaUbjyPxRTtmQW3y5tDTdjrpH0TjvgZ3edlQLRfwfYnPgjZJ0x96yq-qCmy
pcFp6NNAZ_Y_CV__dAF7GKUz3jFh3NtKeVK6_xgEV_tCVvwovuDnOoSyaxpNDvJ_EbA7DZdeaoKkU5tKskGudhpN-Vjgq-YJ--H8nkGEHmOQaydY9pPcBPd_
VdSC9lVjbGxypRyEhm-I3ITB73X5ncXot-dzbO66pF03rtmSmqziui0ZnEgPOJ96-oEv_ABQIFF31QCL5tWoz_RbyRp4bBxU_CXgKYyO3HTog0uXDrba6DNR
ZlYwHmDjzbEyr-PwnqlsPD5LIDSRNp60C4Jty8pVP8Bf1UyOk3j5z18l-5_xvphQ-y1xz2H3hV9UXlbXdgyEOM1PTqkZ_ZeB_sTmB74ZE4tuM6Hz8iF8FqFr
x-4DLxa2LJDJdOzTQwsrrbfhhRNMMckjjTPQFmC
}

sprite $Destination [180x180/16z] {
xC610000082W_QaNgG800000061spWE9aHW4WY8C_F_5btEsPe-HoziVS1S56ALLO1zu4bUFHFKNgf3X1_i6gdzDvOdUdjL_1c57HJYh_mN4CI56_pELjlH4
zMD0RUtLZoEDjQ6tg5mgihSfLwK5G-g2_4oXHlE482zeCAdS11hfwCie4rIVG5gWB92ElfYIA_FI-ewXxnvMJQ3v7w_-FuIWPT2OeFvOIf3CD2aOvMXSrkOG
7gZUe4GzevnO9eQa0CkOD2fJXDcvt4z1QowsOEtgFlTed20FT3x-ar07kZR6CsW37LiT5j8UZRqE2-6VeUrsMEYc_-mfQS6eJql7XQan9Gt1hCzAbs1mfgLT
i79bfLEmfy5AOpoTUUaIx13GqdPL2VBIELk4tfFI8KWELZhNDPXliFQaiOuYYSOX0mFEaXs_THXuGkTGEz_ETpuFhz_l_imh3pfxRB2dt12i1zcnFmyQHJ4w
FsDIkLtah5yFngHol-x-nXfKxdpX_RgSK-vNsN_Mx_FhprDafvekEBSQIWvdbJkcps4XE8Tb0ns2ysws2brmhu1jqS4gOtvFCmNtPDX05waCnUOnAEKsoVqw
CC-mKhJNLkdcMRr1tVT59-xbuhx_F94T_dpt-LEmWNpqOuyG9BD2Ml_YAWNAD10eAoAjVycRWYZJn83o_Uxuidafrp0GL1zDL3F0bW034UHO8hm4GTOa27nf
oIACPKGHnZ8Sn9U6T0J-Bao4MF3vh4BOEXMFHFsWcsxhVCpy0sRhANZR7XmG0010C03htreBy6tZ00000000A
}

sprite $Function [180x180/16z] {
xPs7TlGg38HH6zx_YM_lzryTYm4jANDwaiNVAeC06UpnSVKj4VrJ8fUZgda0yxz2kAbSYEk1cGjXzu2h9xWNSel5B0gkRmN6N1BYJTWMan1SsaFicAp2Eear
vXR1-ebvmIyWlf1QME9-X_Wy8kWnOiCyfP1sM_22DGIvFTJzGUuFjM9sAFhJ1IzelozuMRylU4K3yeNGDji5QUXz3T2ToFtf8-Qy7pf7xeVkH-w7zlbMGJgG
-w7vl0ottouZ6dkWYyZArLWa-aT40JlrxOSk8ZlT13_B2oB8UoSgMaWPVF-MrkIXUrfjdPbYJo3Gk7091da_yvI2CyWeoDmaR7P6rBzxNRurPq1uY_7kq5qH
qBvLBJOvJT1MzB1QcBiA3DWtpn3-zWLlGcU_lNe4-kR_THDwumhIDosdb4RcVIXaCpeFohU46Sddsm8DaZbcUw1jNiqCEipzpDFu2GBFp0SwkfdvzQpCwvc3
JLGyCv_ky06OZHx3efqvw37Ck0JFcmDqcFlCKRS6mitCTFn0QkOUw3674_N4pbktoN-LBlb5mx12b5PReRrkPnzF9VE8KBUpjDvSp0cm_qQIdJRqWLioSjZG
UYLpZc0VXnb95wJzh8Ud737tvmq_FAhWm2r6p3EoglN0XfcNbwqNf9jvHVq28LIKUM5bo0fJ4Nc1BYAYZdbGH5HWn1PfHi9CPvGrCS_Sl-vcGWM-VfQsyyri
ZSpVpFFV-cOEbUp4B4oA1rJzD3Ca7ywjKCPfOevyKGjDFjtK1_EgawN8Gt05iwNb0sWo6Mnapl_0CkGX5UOun1mZWOOkBiVqABEF_yaIv145PkzZ7lO_v2gp
d63E5u_s4dcWm6nTVV0tQI24s1IRhIzuvgcZ8gjSLKunHuaPfTNHAURf1UIe5NDnYdaQYVownTZDN8UEwchVDpFNeRrSoxMzp7LehrzKjZBNeNsbg8ADp7Le
Nxgf6KUPfsr3dihLNYDXBa3xuarwFSmyPTS17lBCZXUOBGdpwZNZCBCkCUVjs0xcjSCAozrUTkpVN3j3hCjT23opL97hq5QtLUvHhIBNeRTl5zKoChkl0VJf
2oyYrw6LsDS2jn-G84VceR6owiqngBFmUlGyJ2HNpP1vQ5duK8xXvBCTR6LJ0wefab_1bjAjBTT42c72-B5agS21vQ98q67sEM4BWRRbufCNt2YlmRnyVIIn
McJ6GnjvqeuImSeKXVuZsTzvZHb4cIyAoLNJh-ObFpjJJfNdvpizX_92n43LKojRUYIFepyFc54ZAEJve1__GqwW9GipMPz44kGCocV-UonloHTKvdNYUDfb
8_zI2c8deZsSFvjvuF4ZY2pT2p4qqZRwDwS2UPC0lRDMvcKAOavuzME_OjuaPH-SrIydrcODQjebtc_c-osjeo3SQURx-s6CclHEv5nsNSgu7neo6g2Ra7Fv
dSYvx1Pa7heV-Nve34wAE_BotIEYN_XuVcBrTsVEWpQyq-FUTti8-gtCo_jzmKlH7sHUtXxagxCUV1oJeJzTy78qsQAVkfyubpWQY6_rTUZeb0MVAuGYwBT8
s7YFT14RHeIu0VlELzkAFUOErt6DH3rGsE1s4xbv_9iT2E8LpQsItpG-iBxrCm
}


sprite $Packs [180x180/16z] {
xTn9cXin241XG0BT_yGPlMhPdrnHXI3d_TjChpsZSf2_3W000000002qzUu9UZEvX_d84qrku2DNg6pI6Dd2P4-CVA7b7nYpa0qs_ersoyqS6MwveSU3gwJe
uy6s7nek3sdHNVvKs_YfzrwdVFkdbZn-RdDKRgQPPfffffbcLNj6PQRsaYOsznYl-9SEYyMOdTJiYn7qoWniESr-OPhhOy5JcdKiz2j3SAGqzsN6WSsZNhF_
9yrX4o_VB9F-GSqqqqmppJJJJ3FDDDDCiqwyGZCpBESRTk0vaiGYGwkTrwtFEjkbEwNbD8lw-zycQh5u7AMTywkrvtJnMxzGhgUSrqmppJJJJBErb-pzTqBJ
l6Qxz152VV6juHBNOTk53u4czUOKYTNlhJSFheUQ8iq9SqhbkPlcq4altooJJsgccMQQQQQPPfffffbccctY7pWFqipvHhthiEtItUqbpkiqxZiN3SreNcUq
A_yvA--SN-qraNT_kt8zXMQQQQQPPfffRezcpT_RSz1-fBQz7qbBxw6gl--h_bwrK_VNdRydyFnzZEVllPnPrDylEjFMFN-FQtq000000000lWC
}


sprite $LoadBalancer [180x180/16z] {
t9hNkjim38FD1Rx_6_UcYncAAXDsL5nrdF677mXHj8zMYPfx17uhmjrKZg-Kg0VohH3-NUHg1NS0Rb_1BOLt0swno0NTY6sHomgxeyIEF2NunSNMo0Q5NaYC
R19qB-9ApIVUYLeY2GfcDtgIvDlOWc-GIAg2KcIoe4mdR-5gGLuY2C4Ns_Z3yq8v8I_e2eALwOAGaVdGVEJxeHLvYw04P3uq1vaFpVSotzDyP3uq7vaFZRnT
81pOT0LtBBf_ODBy4Ycn_-xlmrxaK15dzw4J3ZJbMbexYUrq8VHYPtZ3ZmKrcSVhPUEbj3RQeWeqTu1s72WhEvoudGrETWXpO9TSbJ0RS5mMPxIX4cp1RaEG
xt7MtuQMfoMaL39UcPsL_k2LkJh3lQ_9ZLJcocn8PHVQyhoiBdH-9xEH2et6gx94YLN5-JiGEDdy6zDGI-Ff1sEGZcmHt1oFlmL_N-pGTXWASQSY9GMjBViz
snM5ydoX_O9TbnNRnMaNWho5APL5TNSqTM5GxLp_ZgQH54mxLwzOqw9KasddyY_MDSu4ryw_X0YqBNV1j3DdYwxCtR5nThlEN1q7PuaEffr9ZrW8oE3uZcjd
Zkzq2pjNEIkT4H4VVGTtd4ZeLbwJcHCMkXQ3w0_zc9tBRRMJf7mZvycOeJTLjBS5VVvXOondbhUseCqkYEkmOqjD2FPZtXWEExRIXDmglwwABqF_Ksp0JKNK
yMcoLOi8DnbwsbQXPRuBOAEN-l4gA496LBe8hOLvFdZjRTKaNXSJRT3JXr6CNsF3EnFuAD9qQILaar-E3nj9UrjE7nGQIz0--khn-UQlFbAyBwRbEUZA76i7
79wTeyEXfWawvfYFLpB_BQqVutMX_PLADRoHEOuvoS9t5taVinrpijDlziKiCwOISRrCqlkE7AQOPQ5AQyp7_ygyepSswC5Disx_CsN7itl76UcsMNHzWFOT
P_vlkLivuJv8kCFQwXrsnrt1XZkP7NTVM-uOxz_bsi8lsNHd_gEw-og040gY64htBnaDhqmv4dQ1hxb9nDl4yK4teD9RspjtQnDlckBj6BpHYri8SNCYRdl0
3PMuLHCtWU3sKjouqblY-Cts4x3PLhRn8eF0inxnJCqTmDHex58y8tO4C682Y-SoZ_5iwHdmDqCCByXAYqmwoFwBZWNGPG4wGsmtIxm3vmnmu1Yk8T7f1Bgp
G4UPw883dNkWsn1qI8AkJj692hfdGSSlw586dTMW6nnqi8EkUx0fuBKRm4O6s281cozUMmTi67cjAB39vRNFmCQSr_BpcebUcz9hW7gjLQvfYxQ3mKQpqi8E
-EgCvhZOTly1
}

!define Route(_alias) ENTITY(rectangle,CRIBL_BORDER_COLOR,Route,_alias,Route)
!define Route(_alias, _label) ENTITY(rectangle,CRIBL_BORDER_COLOR,Route,_label, _alias,Route)
!define Route(_alias, _label, _shape) ENTITY(_shape,CRIBL_BORDER_COLOR,Route,_label, _alias,Route)
!define Route(_alias, _label, _shape, _color) ENTITY(_shape,_color,Route,_label, _alias,Route)
skinparam folderBackgroundColor<<Route>> CRIBL_PRIMARY_COLOR

!define Pipeline(_alias) ENTITY(rectangle,CRIBL_BORDER_COLOR,Pipeline,_alias,Pipeline)
!define Pipeline(_alias, _label) ENTITY(rectangle,CRIBL_BORDER_COLOR,Pipeline,_label, _alias,Pipeline)
!define Pipeline(_alias, _label, _shape) ENTITY(_shape,CRIBL_BORDER_COLOR,Pipeline,_label, _alias,Pipeline)
!define Pipeline(_alias, _label, _shape, _color) ENTITY(_shape,_color,Pipeline,_label, _alias,Pipeline)
skinparam folderBackgroundColor<<Pipeline>> CRIBL_PRIMARY_COLOR

!define Collector(_alias) ENTITY(rectangle,CRIBL_BORDER_COLOR,Collector,_alias,Collector)
!define Collector(_alias, _label) ENTITY(rectangle,CRIBL_BORDER_COLOR,Collector,_label, _alias,Collector)
!define Collector(_alias, _label, _shape) ENTITY(_shape,CRIBL_BORDER_COLOR,Collector,_label, _alias,Collector)
!define Collector(_alias, _label, _shape, _color) ENTITY(_shape,_color,Collector,_label, _alias,Collector)
skinparam folderBackgroundColor<<Collector>> CRIBL_PRIMARY_COLOR

!define Source(_alias) ENTITY(rectangle,CRIBL_BORDER_COLOR,Source,_alias,Source)
!define Source(_alias, _label) ENTITY(rectangle,CRIBL_BORDER_COLOR,Source,_label, _alias,Source)
!define Source(_alias, _label, _shape) ENTITY(_shape,CRIBL_BORDER_COLOR,Source,_label, _alias,Source)
!define Source(_alias, _label, _shape, _color) ENTITY(_shape,_color,Source,_label, _alias,Source)
skinparam folderBackgroundColor<<Source>> CRIBL_PRIMARY_COLOR

!define Destination(_alias) ENTITY(rectangle,CRIBL_BORDER_COLOR,Destination,_alias,Destination)
!define Destination(_alias, _label) ENTITY(rectangle,CRIBL_BORDER_COLOR,Destination,_label, _alias,Destination)
!define Destination(_alias, _label, _shape) ENTITY(_shape,CRIBL_BORDER_COLOR,Destination,_label, _alias,Destination)
!define Destination(_alias, _label, _shape, _color) ENTITY(_shape,_color,Destination,_label, _alias,Destination)
skinparam folderBackgroundColor<<Destination>> CRIBL_PRIMARY_COLOR

!define Function(_alias) ENTITY(rectangle,CRIBL_BORDER_COLOR,Function,_alias,Function)
!define Function(_alias, _label) ENTITY(rectangle,CRIBL_BORDER_COLOR,Function,_label, _alias,Function)
!define Function(_alias, _label, _shape) ENTITY(_shape,CRIBL_BORDER_COLOR,Function,_label, _alias,Function)
!define Function(_alias, _label, _shape, _color) ENTITY(_shape,_color,Function,_label, _alias,Function)
skinparam folderBackgroundColor<<Function>> CRIBL_PRIMARY_COLOR

!define Packs(_alias) ENTITY(rectangle,CRIBL_BORDER_COLOR,Packs,_alias,Packs)
!define Packs(_alias, _label) ENTITY(rectangle,CRIBL_BORDER_COLOR,Packs,_label, _alias,Packs)
!define Packs(_alias, _label, _shape) ENTITY(_shape,CRIBL_BORDER_COLOR,Packs,_label, _alias,Packs)
!define Packs(_alias, _label, _shape, _color) ENTITY(_shape,_color,Packs,_label, _alias,Packs)
skinparam folderBackgroundColor<<Packs>> CRIBL_PRIMARY_COLOR

!define LoadBalancer(_alias) ENTITY(rectangle,CRIBL_BORDER_COLOR,LoadBalancer,_alias,LoadBalancer)
!define LoadBalancer(_alias, _label) ENTITY(rectangle,CRIBL_BORDER_COLOR,LoadBalancer,_label, _alias,LoadBalancer)
!define LoadBalancer(_alias, _label, _shape) ENTITY(_shape,CRIBL_BORDER_COLOR,LoadBalancer,_label, _alias,LoadBalancer)
!define LoadBalancer(_alias, _label, _shape, _color) ENTITY(_shape,_color,LoadBalancer,_label, _alias,LoadBalancer)
skinparam folderBackgroundColor<<LoadBalancer>> CRIBL_PRIMARY_COLOR

@enduml
