@startuml
sprite $1password [419x80/8z] {
x9hRcgGu38CZoURzttWFrQTW52hB5EmCN-cI3ewJ7ncJhlRRw2rMeVrMUWjPnNOBlH7fcLvbnxTu315oHl42J6_fnOYgud-4z4RqXWHGaY9EBUnnEg8CtX8F
9Oa07gn0IYB-51VTlqcaH7Xi9r1Yd83eteou0m8IpxOIvyjmvAnm9q25mJMGZZxnp4d5tG5LIBWS4J-rM-_qeOZxbZf8a-DuBIBLWkKHzHd6BMt4UNT85o9Y
v3IYSQk8Mn82AOKa0cRmDOWGcKSGDTskqaa5J-IINrgM56knkm8Hb7aCKVqgrfzFYElQicJ6IhcaKEuu7P4oZoAgVunR4M8k6KQv1CvXv14nyX0YRwCR4KBq
1ggGT08ZZmYHUGoHz-1ztaCg3YfQxP9m6Y8eytM8wgsWualsjCkErNWegEzHPnmwKxs5miaR2NeIj-n1MRI88IBbhoEYlHMAoTDmNsiZAW4NCKGmdTIUokJN
BxatJ8GUMfU-Z3NSmIugIbxkUWWU4Kv21CDd10dAaGAEejSOKMpNxTU-q17A8DOFYcCaVWSiMnm-BzdLcbJZ54IQFSVpO_qRyoWY3AuRznb2AHZFEqQD9WLt
SRmWmInUhqRakOyPHKuWOive2aMC4ItO4EfyN25LHXJDGkdpGgILCpnUtIwKNNVIDA7aKKAfaKs7zbs-T_i70Dj0sWun1vOcSyqN1NPx50JYCA8Of3KMPWab
2w4ZY68mULH4c-qFjA7uDQZpNfKpWChK4uZq-G8_ZgXc4FFRfwaiuvSGOVI7aOcmR0dfIzmmoXnsY0YVbmxz4_iu8fMmB6x_x5LjYEslyG2m6yqwWJv7iOzP
uWVx0scE6sjGDgbFGkunrDP7NKyJKuyEyc94KSg89lo2xKLPwbnp3DYaIlZOxnZzoe9rv-4H6KRT6GFZEQAu657KHpJyPcc_uvVl4Rbs0VpCnOzrM14Sln2-
QBXE8KCFXLQXF_ITFEai4g4L8jfVyu8w2L5idf71932TvsX6z07ql5slUMZwr-pnWwXOGss0o37gZe7WljNLvnR3ptEz7X7SIyOFTUxYSCO-oseriw0-LaN9
h0etKN3z9ahC86Ak7ITKHAn9g3b2dqAy1X4U8XMsNI6bYFWbHD5bMMvpcxzDSGMooeNuhdFBT-sQGDHAKqSscFtlBufxdw1w1QBvSmE0-uWqtdqzC5T42Jzg
U13dEtQuLz7wcoZR496pqV9JwM0tf4Eayb1VYmZJFxJSNecPy-ZWN7ZjfixjegNLmK8bWH6YLYhT256CFX1mBIAs8uY-9N-_wNwSu7bpp-pOphsuWnzqY01N
wU898W3WGogfN8g8RHxHOFja06HLb55-0NLMc7tX1ZnSdGDQ_BYe5Dlr3O93DDvBNOaeqFuh8lX0Wa_CO_BnLU-EFWvgQ0dhbhjrUa3vGRHcXFNBY1mXyhR6
XOZKYYOGjI5kqTpdMVgrHyrSVHnMWw9q2oec-cHa4BLFH9X5f4iHrSto0a1IYYsYs0ivCtbWL15HkB6Fen8vMgox1LOJDMPy8u9v6Hr4r2v15EBEJq7IQoOk
IsP7_l-jRaLTwF975KIvGQJyGTGS8duYqc-1ABub4V1y5Bcdaf6NPZmSi9LEvLMqNY7MI-PJH9cX6KHuYYXs_ww_spiJ9STP60ZJhIRl_yR_kKbPZbk1NCnK
kUlSXG7XBm4Cal8UHCrhsDDWrslDY8ECxWSFSql3NByzHgJurOXiFrw3C6EaGVaXS3jQEiSFJI12ZOY_0v7wOuton8Y7LfYPBYr5QHHAXTmZKXX4GXlOBlnu
HD47D3ehAlbkEC4TC2ZrjrkCjFb7lUc-8X9RUtNJdSUn117xdQI8e6mR20smfAyKPWomnxRS5TQlhZT4FTghhwwn7f7SaLfKRO09ap7JLP8P88jRcyOjO2Av
bcJxW1kYpja3e1eH5Y1oHr0UKSqfXc2Qczsq5ALYxGevTeogFdsCMiyoN80eh8Knr0QeyYYuZYgKSQEutvNdLwQ6tMM4dhkCm2oYM818gOyQ4GayMiq48jMg
OdDp7yXBKJQEo4zfVwM7fwxqQ13vOu3LY50ZkfefU4PYEhGpFU68Rh3ObSTkdTfTZ6lkObpkOlpX_HU-ZwXF8BAs94GZ7xZZ0mRjsqSgJCFXjOvUTo-f4PKJ
kRwDYBQ3N3UyBK7NBqi_xMEB_MuGppXfeHidBOkeziIY-hSHARNl4SdRGZgZU6GIQwyN5Rxjk8tWVQwE6dXnP5fUlxqMTReZXnrEtnteB0uJ_pWUnvANCUSm
x175dSDm6q3KZ3EgUb-1g8l9ZzuXWcj3ZMOwvB1FLcVjzsY-HX8C8kTspp54yLHwFo0R7y2sKBamROEd-iyT7FlrKCu3EdZyOgIg__m1g8BvM0IlCFu8HV1A
uExB42JmV4vW_DUi95T3gjC5IbAyaF3su2GlLCUvIRhFinPr_nhpmKVWjH0mgbl9VungAPhg2lD90jNVA2P4ux6pbc0KVnjy9f3oSgiICMWar2VqVaIqDTbd
5Mq0aJ2Hg9SENqv1CX6E73OSsJyd5eFHvn4rsOhpX0OGwQ4h38fIcjmbyq7zY3QCg8KVySSH-Om27bxj0SJP_gVcmPOK9ZN6bX9jQenHH9uHKyad47b6mf5T
2WruNr5pwTkZj30gwn78twEhRWv0olyTwHiuWQZHFIH-495_Ig9T270CG1ouxrDWvDgNHIcBB9e3QPguWTj64PchVi5CrEr3OgXqXCm4kDb6Au8-qzQraeBu
ZDtj9eudEqFWrOUqHlWThVh4gBgKAGCJeLDh4cyYGJA06eBjrB84mxXBNzlxfKTRI-Xaj0-fxPVBDWaqsadevoMx1sb-EP0hrg5J20xNZBPUvsJdnNMJt2a6
CVJZE6jrGlhXW4wnJXZEjbwd44UKaDYjrgdhPlj_aOoVn-SKGAxxJVM_0G
}

sprite $AWS [134x80/8z] {
xPU9SYiv24MvWFp_dpoLZUhpV5NkR9sPUJcrnGJJHmYfot6Fb9afnTUZpAfCFSYgNhTX5TBp2KGO9iedua3jI_kqOKroz4kaWomNdkn2W5G0f6rpwpKG86ys
7FDjf94L0zRaw62XzEvfvOGLFEo6N1PpQJL1XYctZCGvYzLTtSVMi5jhypNNsRghNPKrHy1QS7HpH9eh4Ze_E3bXiringEnyFYd4m4QoTFgHJYE7xrMGR7E-
jJyssXxAXKtsfxgmPH-03oZsVXBMtLFG7YXz01J0RgFpkKQEYMPIFm2QYINY_sedD_Bhixr8Mh0ryu18Vridf-kp5ZVtSPhJ8Se5q-hsYMPWWrbU-7T5C4li
eF1g_9G5MysnU8kBYw_xIwKppY7b4t8MCtOeFyyjFbLSotcHx4F-glI3C9z7IP3ZXepaAH4cap_lId4i8inDNwnyKaJhjkNFSiMnu63KcFAmaPNRGTnRCAin
5lFaFFHhFMnqMubXFU4jOXq2ypGEnkx2BjI4AAfpnvJLj62xPonebDWG88hi-wK0jE3evUp2hE9GwjGnh02GiBSMCnjZWS5OVjFzrY0kv-OjUYBh_fgkqSmu
TIUaY-g11ROTtZCOUUe5ccRPsvTlCeuZC6F1mQW76u9qvj72nndhA7UVATR8dTcJTSA2Gyl-p5WWN852U-fyBmeMLCkfWi58B75FcxcetOzDnB6bqtc66yNt
i32VjnWSUlT6q3uyTEVsgZPgqE0hLfjNZfNcOeHVdgpTkpTUILBsQvvDNxv7_c8UwQxK4sclJfOWAPVVstbXvsX1_7dEJLPlpYgZb5i1pafuZIMyGrrTNw42
r4a9TewrqloGg5Clva5j73esv9gSLOTetMVM4nb4rTrTCYiiYh3allpNetoINDsLyL_Ybrz--KNA0ueVO0pW8Lthu8YuiYTAJuGkt9lSC88NZQNaUdFuEyYL
tK6dz6CMt33zg4NeOWyTBOH1kKf4oLb0Soxoq3p3diyhRdSTxuZDPPL0twR03R5vNo_YE-qj9awahp0WYFlwcLzg8kMsmL0ovfzNeO3VP7ps7fzmWG2nzyPv
3o8v7JsHW0H0nAFyQkwq4Rl6Gx6Jk4h4FsxsuneFXGNnhnQvulgzNe7e1ms8T4u01jUxI74v6k9p_0C
}

sprite $Bitbucket [561x80/8z] {
xDe5ikj034HHKVV-T_mn4vR7poK7TGk3fcEsV6lAaSdBvnp9G-eQJAS1ah06iwREU2WQpBnEUImQp1UaIyayy9Grc8_FEGbmqydY7aM3QJ3_WcTcZ6UXmJmm
Zxgy3imezAN0D1YFogmGpEYkGcqmJofAys8mkOS-XdbI_lfW29MRWgTkFZO_P0rcQpvwhrrIleq1Hv5hYWQpCSrMHti7C0ovIP5yjYkO1gDHcUu4XfRz1qpU
5qo3sJ07mcvpnve3Nz44w7vW6emy6upB_IpoJKnUFPW6ys8Nxboo53o53mJJOAm8p2XuwaN0D1XxOJ027hFN0DDWDEhIQZ3AO_vvO1gCL8CHS1Il0QR1o4k3
SOxm631g7W4Wt5GUqXWg3eNRFc3C3mE9COXjO3ogydembeAn6Ds-1Hv2N6GJC1hWMGYLKJxml7KpHXsp1u7cO3JEoWUI3s8K8uxYiaemLWz6UMo-qWKdBOCn
PFSzDwxnMB6XS_1-i1yCJtcMtlh6scUDbBD4x9N1oEF01EyMEuBHu4AwUdYA9Iy6PiKMC1fLwPvR6EmBnfW5tGkCamLWPa_41nU2FHECl2yOuqAw2nW52y1C
lCo7uZy68wyCnZYAFS4O5zCTm1XP06RgXTFyns0yQl9ICFdtwi4ebqCz66CLcDZgPMIV10OSsOvWm4ce1cCi0BF12u1iGEl1M0OWA-vdzM2CnsG_CB_Rkmyb
wL4O2C18Ql7-RtnvwpRe6hT1u_slLXN_u27CPmPZ0juFJlnLU-OWxVOjCFoRJBZRluDury44Mr_n4GVSngXAbo8O4xiaaNN467ql7q70R8xqldrIEXaXiQDW
SZM6Pf4r6CKBoEDGaDk1Z_JgO91rs3OOKc9h0_CMGLjxd0G3zcJx5ixJMtinJk9z9ZGm0tMO26PiWU5UC9h1f2q6Ikm067rXE4_FoUUivuQ0UE9Wn3v9je2X
uzavci7aScWjzi7mvs0TZ54llam4fFWKJA2CU09CtIspRZ0sX3hT1EF4oneCyIBF327ve61SwiHure5xOF9haC7v9Z0-X3hT1GEIhW36adhnWZfPko61CGAc
vo5fXBQAhHaCXb2dss18kWeOxcM0g2ooSWICINrUxm6JFjh1cFQwN0V3vuJfODPUHf4A-rmZO8HUhm9cD819s1ZjO6ZMKTMS3eOFNkjWSf5zBrAXWr4Q6ANN
coy40sy4mwgKrxmEXj_wEXXGBpo7PMOWWOb7mV38i6umGwnJ7Km9C6w1uLvusgIcKWBZg4D_IEhP7yPRmUJ5_Jfp0mpfDeXW2Y-KkKiI2HYXroiy97Ljzs6D
O1RKKIIaWc7tj0uco8W3-Rxv3wwT0ECD3qa430ll0xEW7WV0aBzKmHHUA0HXDOaWxW2OCOw-6Z1p915p48mFuIRS1hDqkWBZdxpm2_8g63y19buBXc_vOG-1
iIOmVW-Cq_4ZFfBEHjL30XENUxtM28Q_WSp7mVWt07Dnl15J2HsCN-xrEcenE066pwt7_mkCxNRvRFmAO0Arc3W2Xe-Ns2DWnb4mTWoCZmV0w8z9G0t66y2m
__e39kq1C7gl5wZ5M0COEfR-yvEKzlt0eFYFjPXn1WmllFrqUlszc0V1105J_NQrWU6rDNuUg-EIcEW6un2Y48C6C6HCzXSUkClDWRj23C_qrNWjc7W96FnQ
hmPc-wk1cOBoHMXW37jYl04CgVX7NZxc4J2eBrNGWeWHsiyjC0DxOkmbOFBHwGqGmTXymVI6cGBMDZ2wcF6IdwHyT09Li9V1VAiImcXt0jK4PpwRmCIM67I2
SHLC_nHDrzxdWCmgLy4KOlWLtWF6loyOVQL7Q60Wp9yIkWXP9m1UT7qI-0Hlbll1w6AY4qnsWvdwdcaq-roa5o_7P31hCNEpYLbbqh0ZnXl051KSAfYa4hGD
0Q94dEpAteLiN0mscvYbD-o8iKOmEOLN0wIBGS1C-LqvQ0fyPIM8L07CI4hU19VyuR03p6W0GxOn8M38e1m10tL78oSfa0Q0j6qw6EDYKXAZFsR5XXYqWR6w
tZcOzws-KJ0i5tpT_Afr0l48GGmhhD4I-DmIWzN5ZdlH2SQAJJ_4dKZJA1YI3Rx-1zUUQjSR2gLfOAwBIIaLuWqBCBgOE0t6p3oGarGx1HEKGWLcWhTkBjKd
-6S7jSh1436qX31oEaQLXTLAGiDzCNu3Z1XyNqAk8ICy0ZcZ_2yeAzp0TwZA_xvzFLSOFzyANdsBVg6mJbVYB5CPviYteZFqYOW8vFiCR82nPZ3wpgUOLTHW
FBzkJ1gvcd3jvQO1xoz52cT0PBYP_TEsHfB5_rmChuL4kFqTxW4wrS9c4KV08CSBm60eO4m0OpxVHsOzuNhHIcG2mFjsPsTZPmA6rQIJF98WFJW29d0xsi7e
kxU706PWXRKsoSE4hUC5C9eOR80PoS7uTmO3UGCK2616gbxMtxahXrFeO7GnEXZh0XFjO6B8O0O4C5GCxXGYze-_yLiTDYCmDJ3rjISUaxmP3EpM5aiXW25Y
uaufN3XWImCZYx4KmV1hJnmlQwrWSFlOHSjhO5ZRdRHmdkGYuGW_5GmNGtF9arf_KIU6xaORc8Hl7ULik0gchjQC6mN9k3xVsu8S7IWKDebnAdDToCW2p9OO
6tfuhW8Hpiln5fUEXCRdWwZjwtna1zagZLPeVH4kJHSob59DA-nomgmZAom86yjuEylxot_-YRzqpLaSDqvD8ZDdPeRRpXdaazmfKl0lVlwJZj_9xUy
}

sprite $auth0 [80x80/8z] {
dPP7ecCn3CD4qVS_yypgTGkVmIhDCk6IfxgYjSDUErHRzeEwzrFLbhLb_6w7fWmW7EfMWN2gYyAXBWZ7kgam2x5me0l2iIu8fxgPCEkYSAYBmfbkACowkN23
RYgyO6gGMA4k2sUw_BDCbuLpNHREFVY7F6qkh3xmdQu7xHsgW-u2cEwhhkjttYMWRM2q_dD_nn6fJz7Z45W_XlFZnFXrXX9w-1yFd8V1m_abXC-jpbonthA2
ZO1wKSIcvtIsBGwU-rRWolNOkUE-n89mQL_IORhb-UiftozzJWtCzHHlICz2eFj6iv1PbuKzn0TT7C6wB4ntCHJsE9qBy2naR3Dw5lRyzKSOZy8zvlVNxRTW
m3wWlez6JmEcWBlFlH7sV0AyttXzJWH7NiD5zCTK3NTe_XlMKwZXZ1fwvNxzV2weX-l6MNoLVEXgZUWGDbvB7wu3VVan55J92x5AHxcnu14E8ovdNHD71AA2
Lj0cCXsriOWgmk1QAGskCJ9iH8p1DKQm4Jc6S34D6n4ZmqR465nZ6bnp3E5Y-g_X_W4
}

sprite $bluevoyant [94x80/8z] {
jTQ7gfWn34DXnutp_c_SUPW_0YCgiJi-pdNkAcUtAxVxfeFuxtKEXy_XRpg4iqxXr8TmrYaSFec_wH3EJWgdFe0xjpyBtEPxxW8tZzFllRl4zTDg75xYVdtF
WzUuvi-Y75xWzd4eXpTmZgFB1GzkreChNkEQrsU15xZnjETzTmM-hDTdWJVmDxqfXmStZmEkU8tFzZXddbZBlxhrOrq_0fSVrrJ1M_NWLJq2BxyUNF2tokV1
vQVh5BEF0qxzjzoe_-Bm0dVgmGK_LJR_nU7dKsuSH-3KK-xN2vpwMyol1__o7zpWkqhnLPANg-Nw6hy3pX8_N2Q36wygSF4f0xylFylonsxgBF36P-CAXq-L
mujo7nVy_RzdWK-T1Jxme0m-L0xlF-ZcsVPdqPE8LQvFu-C-xv-5JQgS-b0vcrGvzIaSFdGMDgbowbFby2aSFdGM-0cLiqcLKvygXm_XR49deNv2vMnIvTId
SFZGMTZ4ogcdFCI3n_YftCxTbly2
}

sprite $crowdstrikelogo [432x80/8z] {
x9S7SZOn24CD4lS_ybzIxOWrP59tnczQYfT5UbyT3nmEXyC1uquSdEDE7E9MmWwubR23nQs47N0hOGUBTmapnt_SneTnVvZazdFPGJB8XpXt0NrXpdY561CU
0dbTWo4ci9oR9gnxFd1n50-_AkeYNo7equssk9x9xyGvo5pI7CDY8WiXTKGbJ7DepnuvIAkYhEAPX4ZS87-G-2ug4cKCmJ_WIsBKldGFj7nvIvZlTVWkdbQb
q78BRn-7p0SjfXMqqj0-u6iUqVS5yL7w6cm8Op73srrvAJQz56lI1_AeETxQmJxawm5l-j95HkrhEiAMBiKgNwimrEUOlI3gD7qYnWx8SpNZuxx2-hvChclv
iaeOOqFfAqnqvQ3rjfpDqgWA6d7u2RwYxsiTs_8r3xA6BWNYgxXHMMdICHA7UjqU5_U2VOOlT7rHBchw6jm8AmBGQX4cJMqFGX-hIJAJ-VLqpGE0ou6F-ugc
BuYBofS8yo4K9UigV21zP3CgBanuKWSaICWIwQuKzvZNTBuW0_ypLvtVoJg-D9E6M47nzIOjcMvZcFFDUTUAjr9rqZmlAtJpRFBhRzgU5Cca9gJP_x9hRjiE
go0KTG7z_qy-ztItZ4bqxTlJuQsf1MHMeWWef5Tdzp1EU0ccX3PPD04J7ozKr-Y3eqN1KWzUlrqR_39X1y9JvPT4KPm2mcFmWbMxuKMnsFEY0ocvnWMYM3Uy
5bAu15OmxipfxGZf4APAsi4SYyyhB5u1UuqzBrv80fz9GMWTyghcFzhWeGbR0BLq20PfNhoXI7qFBrcyYiAwvyN0Ofmjo3cl-MyTcuG86sP8Xp1Lp5I2-k8l
hI-KqQPUv1POOYXhMRpo9amO63v92kRvfZrtuOrvzOAIRtX_XSLBO9EXpi2AF4k7bxAx53UQycso7KV156c-fob6kqgjpqlbdR_QV3rUqO7nAeazBvRQQehR
tTzJpySODUM7l1vt5O2qUR7aJ_DQBvzgFldeixmqyZfvMUkfMy-7Byh2vJN7kqnUVlsGv1EyYe2LlebNBejNLvWVb83SOzcyPd_hEtY5oQjyNdhvtF-wvUT3
JWzXv4FqEo4pFihZjGbvMBpy-o-Ki7XTgWN1gxUF-IbUSRBJh9DQ8yOfzk4LFkUWVvcNbith8OlNDINH1EFLkq_mghEJ77mLf4eq3sC_dzXp0zOjNg3VubKx
Nbnr4fdA5qFfyEBjm7xwC1ooirFAGMykKTIep-TLvxoAhR9DhiB7V21A-FTL8g-0QZgLi1bsqV3v7blxy0OCBmYioOihxJhbfLL6VHwaUHjOdH0qci9vMPYn
DAoxO02Qxfwzqfk6gxF08MNpefk8FQy4npnUGdDzYULxvY_cjMBVDr62oW0u09V3G7sSQi3mc3leV5wKSVtxvJHvNTfAw5HzHBOosXKwkD9yaMZ5L4PScWX0
44WPspcfgMygAjGt7UdpeWNczs_8vhKIUZHXYJK9TANVIc-smUmYWZIFcg1ZDyJdjVp-GqZLM-yOMB9VfMk9DGdafRa5PUyHZEPTYyMh3dnOFg_kr1als6ZP
l5RIPHzkxVdn_A9HKyUYyP1GI6LPl9fIalHvOV_MdXVVhEzveH_H7cNEIom7LvRL-yS5oirhF2rUEbZZwxEymkqN1PTTNdGo_WzGgeRR-HnT4VSI7-22iE2g
ayDB07mQu_DQVhyeP4I7LrEWT-_gkGc6UXMvqhckNRXgU-5zoVYBqqGNMrm-hx3xHIaZ-hoM7hp4GjNBGdo4uOA6Dk6AsqvmKR3Yc5TftxByo_riwBGyNXoa
orH5rDDujYW4aid1LXJG8WcAbYRt1rZPQA4BgU_hZtheX1TbH8CNU9FzOTNJM4IhT3z5RM5o5sfMYoVBfH8U1Wtk4ZUw8-lo86RhQ2poAMGT7in1YdShESk-
sXujzW1o9v9aVUNB_wAYpFzdUtU1mr0Cms3OgNl_CqyyIASd63ZI_rqXSXdMGt2pm1Ut8qjvY5WV33Y-O4Jit8qj9I9YlHkBAnZw2ADwygmqE0_YQuSM37K-
CEgyWk7wWQ2bFF3xzv5AsQZOI_0KZcxCxGpY4Cp6QiIOWugvtMn9XF9XGtih5zoFRIq5WrzwiUGn8lennKeE6FfoLEK737uy-5DAXzeF1LC-h64BYDZp2aR4
z2tW0p7iMGM3PysNuLbZ3dXh4hWq2PP60u0R
}

sprite $crowdstrike [102x80/8z] {
lPbRhkDW28FnPVzRdckHG2TAgxyGlu--iU6O9a4y8Jw3yICOFODnms29oOxHbfc6uH867MEjPMP6YbiODOmsCOgK7y5W3UEAeMsikJ4AXdiO5enYL2eObJyY
OPA2YZ4ICvsQb3bLEvgsamxWQeV97EzbLJlmR6ooMLFhKCvXkW6hGJcDIGDzL2QcYpdjDAY5uSRiqv4zQ8Xbx52nGpibJjpcQpjmaJXNcNsDuIOHtwUc4ji5
Pc0PyAEQhOOPiaHVNXhwKkSWLGxqmiYU1K6jcryODqsi7Ug4OVDYD1FBmDuoQ9cDS_Z2P6PtEkQa7QcPcVK3vNzHU6_c_18X_odJt3IcRJBQPEOneTRKxnId
OZlNyvkMIWnMAI6chKrAP6RZS-dAafxRCTwPcWlihYjy9nqyRbo-cy4S9UIC3M8qSOuIj8L6_0Y3Wq8MqHyztcF4iuCfoUuS-4uY3ZWrSo2Dteld79OMuEpb
fDpjY7TsklapaDhEWJSa7hm40ykZeAv-KkAV2XWX7l_eP9QP24G0fDGM37ovWU98K6BkHE0_qOX3yGEC1Nvxr83t63CqSDNUOWpOjhOnWhut4xVZRwzuZiK8
t5JBr6jmuHB3w9A_3OpwuBXmT2u0OaMwY6eR8snXw2gHmAQTtUp8YY40Rc0Wsq9xHSpD0M7_asxfHSIQa5vsHIiU4AHBDxy1
}

sprite $firehydrantlogo [449x80/8z] {
xPs7akem34LzrVZ_Bturx0N5WiHi661zfgvnONIGx7XRUtqcaybaCfbC9XFyvLw7ze9CSIAY_v6omyAh6Ppkz0zsHj4o4D4lNadV149rbJ-e4ccloBHN-uEy
hB-fprOe2dqlLZudKBNx_aHVqzz4r7h8M_YReAzFR_kJzXfCPC3VsoVWz2Vj9PYezIdylLW2JcJ0tzi9dFKJkgAz01CC-vFsOv05lCy6cFt9JnOeiQ3jvO1r
qTHDjCFtBA_l8F3qZrSKg9lyGKS4mgFa_s3z6nb7UumuqpBAvJvK88nilC0ck2lmr8EXmF_0M7kCqq97u6d1FbMWRF7NH0yGoC3u55W5lDr37_2dCWKUXCN2
m3F4sX_q8O7L7aZ3EWKcxBGm853H4g8Ls2BGq4h48yBQE5DWuUyR1UhDBgBI7c8ApFvs29G1WGSm1IP_2VnCWIAgWYHmMns1Y9u7P_905Va-WOKHBS630f7E
olmIekPNGo5cxgQ2GO7rXPZ7VuJloy_E31s1iO2_qrei2t3eGhYYVxpKPM2dc_p1Jmlthc2XjJyYXmdKwwS8nA91B8Bnoc4n6HA8EFT3hq9oF2nE90nhWUVu
Vbcmz3RxRnR-DP5SzOolKCffJKYhqDeVWHA1Af531C8YLQmKbp3PBv25AQUWB-sQ5rjmAmLgS85bP292Em9DLw8n952CQAkuzDVaQ85OnSkYYCekWKn1xoSW
k5XQhH98OSQ9Cc5P86TC1lSBn2Q1T8Pqfi410YrIflXN8Dtvsdw1J47f9Q0bVuaaC65ihePHOD5hH61J8oXDNFawMc3yTsNdsOqx_SKs4x8MY1i2YnHaOmZJ
SL0Ww-9rXZbgWIJmgC2hRiW2UQXM8jyka7lwWaRAE5WiKSa2BUECRv62ZBeZHJZSpIDs28IVnvbnACSbWV6FD4SXSFScA8fL3SMNJdA8G9Sy2MqnvfO5dc95
4YXHRqkQSiW4hG7gzmI6sVcJhB6C-miucVS4kieVB3ZHETPSavbJWVvZlAX95eZM4OW310Qoh10si15PO8sb0F838Ja1wtqh2sInO5zBxvtLCGiyzmGda_f1
VcSDbPIFeAgYXjO2tNJ5JO6XUOwmbd3ssoEmQMG_5XSz9AYAU5SWlTTuge7mpj6K1dL0OBU6GjEr6aJHHWJsYLfWZeda1AI8iFq24KL3oANDyFoSaGKcCmMI
rC0xugdB7XO8-ZEJHWIDu521OTaKUrptTEmLoD04qX5cdJ74Ie7MRe8eIdXexmFY8mAHQYXRj1mYIl3j0ZN7Bgm_TSX-WVbMpA-C5PTj6fL0tFarsLAW9CtV
9v0DjPjZ1QwViiDNiEVMKsZUbkYJxo55ih9EqIqZtbtVYqCKMuS5vaqG52fR1CezWIPhzWYi2SqFyXcbm2pZ9EVfEHFs2lIrlbFYoG81jMyMgAtYSO4Ztmza
j6Z6aRQiCO5AVKyK23MYQaHHZRW4nmkCFYuZ0lLY6pAUwH_EG7Pxli22mWtqoGB3qAVj59Wj8UXou12J1V8Xpqt_4yS996eLKlXxbi3S8xDNO7wIqE2hGuyH
dXCmstcAGB4AhVqHELIWiEbnWVb2rEabcRArcRi2BPY-JnK8sr538SyJo2RxJe7CiqZHJAfoVEyBp8quKY1Hgq3Xxt21n5BRiC3wiAYrAxRT5vZbKCIuG7rC
eABqHt2iG0cM9GB3k41G8EVERiCbVK-e5bXzir5YKA2cR_9YR1DKQGdHPmfa2kPMyPCD2MIeYHMNHn7BZSz6WHgqG_T30ca-JCr3npP1hVEFo942ESlbDqhb
hzEmSO68d83P0jak49THLpNAtoqmtr_uK0rLbFwUTnF3ZsCiJrVcmPmS49XJCByKemARvHza6nUegShBI0r5xgLF5vZlyF_1O0uBH7HYKnkCs2GGlXuuA31F
vGC2fV2NmF426poAP1WKo6HXAEig6kgR13P46cWwA31F5TYz2UesVz8E54ZKBsjIXA6D2ymFV1cvNim56mKsM0G7XhLXWGr-DPNi5QWOzKTW_eUR0lqFnW7-
5nHLmZt-uPQMzJCT5GjQLcKKYyLviRzhcVz7qefsRwIaZjOR2BRMKzr4Hlqfnl_d17ji7G387u3U9CN8_4eM67PpBH5qfy6PUYJIo7fWFHs4K-qKADlyINjJ
XD-7-0Jqf_WJ5BlEUuCiKDFhd-8FuGe0udmk-0Ga-yDd-cl6-x7FIi0XVsZl1k94Fca77AcVWlPsMFQd7_WNUrMs-1DvsvCd2SCFzIU2zePe_01_kE_lFUtb
7xiD_y3wgLaDvBsJhxxeSiM7dJzxnqh81zZxu7yPYoNzAZSGcfENapU1d05kTC0BV68daybaCfbCVWC
}

sprite $firehydrant [86x80/8z] {
xTXNUgL044FXaWxxt_Baq3rG7oecszQp_QFMpTHBpLkaNsZPvckkB-OlmOf4EDPSNPFlKIRkEJSrInmS-pZbL4MCKCCzAiFWzEAuYlh30mhCNutwY52ORDeK
fMcQLILkcbVLaQ6chvetzGtABq35P02dw4ZbAOh7ABN78rKfEbA9K76PNatGuZhA1yXHtAa9QheqgWEqQADKfNwPkgFv0WvLrJaQgmqQgboh2j07mz9ydhJ3
Miq4dUfgeerXJQ9ssHJFXgLLlI71iEs3fMs2rV1iMBP3doUeIbLVgzwRUpsjHiCk43yqzpRXy1dhxG3RiCk_FnpMd1uyxtlSJk3J3m0FNXMW-s6zNeO67JzZ
sRghGSV3IcpD0pKO5eANi4Y6RQCE3OPbfegVLDsWYUfM9K1nJOTjqAHh3RgIgwIFbXYeJglEliLcg1X-uuxExr-XEZa-r4Xrr1IFL3AKcgWeGpLIOtIYEa23
6mI_7Yr-1-fdg6fIbL-6zatLc_dvKO3QTHEQeZrgtPaYlNkPcsKwi_yuZOik5HhKjbL9RC2sfEuFREjZwkNbBUy1
}

sprite $jamflogo [230x80/8z] {
xTi7Skim38JXNG1x_ok_T3uheCYeczO_FU9G-LoeDWOGgXSO9Cs78JBD5nWXlvLl-Kie-H9ANBzRQHwolPHq9qwFeVVQIbl-0GcSN4YTIfH2asmEUJvJ-hFI
bDIQdvT0zYl_zd4ksy_B_w2CEQJymieVWH4j9HDal_82f-TTnyjisMahMJQVlBwYMqcrb3dJpbzxl5zvsJFvjj8IPSxW4olPK9PH_iHAT2dB-86L0O33AmaW
HbT66Jwm4ekLvkznzkmo39NutkFuo6S9bAgWg2aBCXOfqqiIwppTBtFd5q2D-rAHGNmM2MsbL9xLbKo7kgRrA543h5DE1LIbg2cfQPOQfAOo_o1vEJFQIebG
hOeoNVDTMKtbUtmesUDwPPagtDxog3FrMAX4_HIr6JpU-nxr7fBsKeOaOxOQHNMVJhp7cC0dAx0uSoHfvnig6TNbiAQiVAtvU-mgfJPJvdaspmCoOMQ3UMKb
id-yiNGQ4hslKFhkIikK-UIpQrMiK6ft9UlAV4vP_avSJ4apjxBMzYiZ_pFNAdrh9KCbdrS69jbEIcshD4sAEQLtAh5IwTigymdwbLoW99ffKwNo-fMsYrAR
AdL99RMfyjVr3irFLpAqgJ8_hROZbVJ7eX2tKjQkc8zJ9gQjbLOmauvIclPNHlLROWSf_JWbafvP6KLPTXcZANKH9JPItaflVo_vpCf8d-fRCd00PUl26DH8
oiYPr51AwAj8Z5TNigNCdriQQHxIWKfeUMWf4sRfK2L3omeqbKqcunZbzkLAC7qFHrBcbp_4CCeSMZOIquYPY3FBbUDqAqVfLXh6RfYV-zrAwYECdLv16Hfw
YJNIB3JuMwd_yvTGOjGIvD1Am_XAnyZvMqQSqzq_
}

sprite $jamf [82x80/8z] {
xTQ7MKD140FXazH_pMGGcTkF8TX-Ky1lhVCwaPoDF03J6DBPJD34PbpC2MmKBgx_BneNTGBYUftUz1rHJckUYDxwAj10LFTzzRZJenrOpEVDHIVGHXU4HFLc
I2o8YeB4Fet6nO2YEX4IEn4IJOgTA4hiH51SjAWUJOZzac34WYkKg0TG-w8s1Ww_Hh_QDnUN_3PLwz7e_t_ZOcXHk6XS32qA5usB-V-YSJ6qA5mCBPeM5LeC
BGOMdLbclOfoQ-N6eeDKKQ75d9DuY8TuY3cLgyKUpP9U9z8r
}

sprite $lookerlogo [302x80/8z] {
xPc9agmw34DRKlx_cz_hEnjgumWAgkikKQq3AJbzi8qdFFP4ZV-bnm4jQNmAYyLnM1dN4f-Of4F5kAHFIZYGN4jFIDz9niLZAdmN878fBXcja5jBtmcbXjOI
A4byDdNgyy9t0pCjGUDJWbtWkGg-cU_l6LnZ8svWwR5eJM5fSuMFHIl1UWeaKPSkMlZYHEe35jkrYvPUEnI9HQiHAYnoqMh4boXatx8MBRsy_B1efJ2uG6lH
ugArAl6wTBhBhmc2NI4kMgvXkCX5AmzSGqHfMujM-jPA4c_QCAYdI1nVB284xm_lL0o796B7KH_ojU97f8qRo7SyNd1ifJamo1RpJ72CBxM6WrCx3hFGzYRU
K0pGA4Be5IR5u1NMDBnQEuoDjllXcrg7ngucB-qg7Wo-uwvWQ7RSsw9zim0P6ieLMXYT6CYQr0IFi8AXst6Omlv4t4mBenS3B5SAdc6vLEqmCYsNS2SjsgCW
G4twaQ4aG5kD43p0AeOgThC7167tuGktqSAUATHar-vrZXv2X3KFpvTb_AcmZyVgUsEJ_RgBbkL5kgwcGjacm-46Zs9ebvl-i27yRSnH9Tn2Iorzrf-6ThX0
bmm15lnIVoECDZP4Z3tX1bgOf2hBlHgveYZ1fzcgE9Qnq7g4lOQ1v0Aj5fR_5DyIefK7xs5XuaXp2B3C7CHJf6F31Lgssxa1wv_Xrrdmq0TRHrkVot3F2cnm
1LeHHuQ9uAUzqcbXvHrowpS-fJ0mSa9Izz1Axm0K6fbjqwJHy4Yxc-M7fZpGtyuiycuh01spQsZrTQJY66bDwr3fls1SeQNZoUVaZfTEdEboQIEyZXJVUWeu
JoT3vidcyUHCT5WrFXjf0w47GaCHSE42Z1354J7F8_kqsWwC4LHfuU1ytKLIf9KycCCmbcrNVJOhfaF5J6i20eUE3l1xqoe76gTfoQn3QdKoz5TeuJPQSbfL
k9-MMUVaqc-JMvdMkBqIuSwvS_scbMZoUd5Qbyxg62giL2mklXEP4nWNQS4AvbvQsSInldM2G9uW2YrO9PJ4lK9BxwHrVfPdBjjNMYXjjj2zJ2iQu38jdHXm
_RTbkoqiky3Y_bPQ2X6YWrBwCjlbVwJH7ihZTwVbAz9z6Bg0LjqSL6kHTk6tfwKA81-7Xd1qqEqydHqX_2PTte7ZqD6gmYbIGWlBj-pul8FVX5PEvF6f-5hn
tVJ16HthteJVOphrrjlxiru9Hl5RDOjZZx_GYkqeFVfCAnzbTFPgVcsmiU25ARAZXN_lVzMP-M1rxpkFRmuAN_RxMcJZwE6ldzZeyecDuzgqLF308Gihgw4O
lAoKXI-EIB-5jvq61gcUz-gfsHTBlQvsmqWBPXmTMUronmYBBj0Awr1CcVtYIyplA8GFj5Z8LYcloRJYVj6_Hgjuh0rKjWpXGrSPTtuXgmhxZT4LoPxyx81J
gTfdEzD-UPLMvPMTeS3gMEbC4rO8Te56-F1_XPOZg7kjeWBON3eU7zo6PxJRHorq6ysJPr0b0jZre8_5c0QVRcmtF13igjW-PyZoVwbE8P_0GONMid2P8go5
AyDQue8L5CQQsQjoYHSIQ_5Ah9QeKpMu14eQGn8TrT9_
}

sprite $looker [51x80/8z] {
lPTN0e8n3885UlyhkosEIEFaiURBweZ_fX8rzjAcBuspy2hHPtXCIg_afhCf-c76NZCSEmHcFcXdTeEmYSX51GIK9EAuZ-U5MLG9pAqGRXOOschnYj2Ai5K_
Xls29D8-72LI9uAzGoWls7yASakGZNCxRWbYdHUleguHtwJF47uxCONoOvFPpCl5c647uOaH4Kg93vs9f9jJ3BBvShblxGSoNwdmrhlJaXIgYhUKQ2EM4WJ1
Dpj3Ta-7kP72ONF_Ya2XpwCIIi8lNoKMn7G6uY1Ip-FmcI-mPjnM8nRBlYas4yNFh0dB3BpI7Gww2wBsNnH5mWso4UmWYBPQ1B6kwpKUvHFbl39XEzFiNbPC
12l4llK-iba9xoFw5_AFZhsnbKwnExZUE9RTmsyp6d_XYZapjKUm7R3nND0U-e-ImoH6DgYMhFZ-8aqhcXXL2mtv3RUGPZtySM6no3V8XAKsOR5Br9Ns_r-m
7y9Y7x2ea5B--Xj34alx7G
}

sprite $okta [238x80/8z] {
xTjNOeGw38LXIUUm_oNVVadHW7_ZzA3NCL8-ZmTSGhn1oDiUhkiNM_7rexRduKdiYuk_0LVRYyYO2OEk-ihQkhKjRksjlRMtzjRUsbjxQs_jhRsrj_RMRlch
jFuKGLR9_uGgtq2RyhEGkdRtlWYT5y_zhrJbmsBA4RNqkiULQzfgfgOz2EUXL7xTzbznFgX4a-pW1Mtsb4nx_CEennUwPdvPgUDU5jGIhB5MrBfxiLQdnLr8
2x1RpMX9GZuuU1Odq8Ai2guzgBUgBN2fQrfxWCLQ_9LmBUyo0Uq0wvZISYpNuYm2Me35Mexbseai0bg0fLgCvLhDN2-irU16HxGKoxMQJ02q0Ckqi37NvcG2
9zBge3RGmixZsfK-Cz7gJKedUq9ohHPI76iBFRxCd---g0NZsAfzJVNeuu6MOJl1IHOVVNMMPQZLQChqA9C6MeWDqobyZkuVAQ9DCe7eXGu_rD6pmZ7MWbNq
yJX8ZxKYK__oSHBrJufYkTOaduPQDomQI3uj0R5SMooV1jgwkaBAAQrpJUk61UswHmpR6sgW9LYkxVaej_WM9sY9j1LhsWAtTp1Ma_vPNJMXhLZKYcyx-wHs
zJHqD2NMAbQrnWcZ-BHFmNkjgDOyvriSe71j1kyrGQrZNTioyfI5glN8QrgjQtD6Aw05QU8JjJnZrBje3RN-LTfDFq4hgjtg2sdNxrAZS55jliDT2doqy0JY
N5v_Hkjtdbq0RZAjy130cnnwfvaZv_BwwpD7lTEgW7Dv_VLLWI-j-9Ak-5mbnkNry_gApuD5EljgwwpV8PVNVvqi-OdxbPqQqPqQnHItc4Dyf-Om8T-5AxmB
Lq6uw_KfTjFv3YiwyQo15dFL6o67avv2vzpkUOBTywQbt6GppHfFMSheZ6wGI9uvQAm0N50VV6ykTfJj6ZLpPJjEWgTUW0jEtPByouzL6H6P6XqMIggM1qO1
BURgg8hzlBctrT1xd5QFk7sGebgvh7KVonmBj6707JXQeUjnwP0_cPPpnQfvNJlVRHLKoxb4kywDUQu2QpdNh7Ezg2NSZkNQTMw1PbpBkHq3jCk3MJ7FjGVQ
AFCrETUkSmMQjKjof8qq6yNpsaJSDDfzBvCzlphGuaIkG5hExQbOC_ALr50R8GChq29kihSufbxsK99jZ3tAm0gqW9li3PrWpVfQGcJJAr-1xTgJ31qUD0DD
IsuZ4u2jxAdCtgGgIRPKNThRFekJPdePTPfI-vjrWzB_9JkJx2t-1
}

sprite $qualyslogo [254x80/8z] {
vPk9agCy38JTQfdtV-F_P3QJRx0mcL2LWguxFdO_wx0GJ1j84NP-oOvGkuKKpcqvT75qPothwkXtF838UUbcx5HSY5q9tSd-pbVacpazfKiRtdROlh3vXs2Q
kWkl26yrIhuUlWhsENvTBEFfq5d5fUZTAlbIz3uA4rUcZyFUuWlGZ-0b5VXNeYT9V0qwgZMNkUud6Qz9Nzu5CRhuseoaEAKrg7_rMthokQxfunYz-xAglxau
YkLVlOL-j_OVBAkblZmhFf8-OFaAFwRfS_cf-41wmfVEFqaVowRou-XZfiibdb1DxsMW_Z7q1CjA6qSq0vyXIU4E_0-W9rUb62miuPykI-1_1hqdEvoOLj1h
vVHsAiZFeQTHz-bZbtwOu5VtrmVHQyVnUKhQepSPYT-FLtKdqDEcjJnB3ykFnyAsd-QPl-WhNMPyBJ3elVxuaFolzBtUpDYXzoGzLrAkWZk-6p_NYV0DRrTC
NVzltK6VgwTn5H9mh-dpL_Jqxhe2r1IzM2bkqeiPjgsqh3lUI-yYuU_S1vwXZuNgfDyyxdX4LumABPFUxw7tJbfV2IfwMhxt_WG1-i2_s7amwtANz4TplWlN
tYi39-Zx2Xl_8_OXVOEtFL3rnmlYAzKILfFqsgMdRIbOggOthmuFw7dWXbVaUcssaZwELZi1BXYY3Foew0VtfaVqUfgAIR3424AJOUy9Ul-QFZRsoH_qy3Vi
Zqr03wmi9KmxbtubvLBICzDouPzAWTAnOiy_r-bCp-zRs_G1VLiGCMQkY0PDFD_N_PzsLjORkb2I7XSDVbytXFt1wWdZg-WBpDvu7D-dfyLCUZeK3tzTWgCS
6B6ywtb2hkxpQ13AqBVGqyQ9z8_ESYBjpJRseco83L9JvVY68nVqjUVpalU6vmKwJKCVZZtumABP1rm4eWRqIvtr5j9ZA90kwFvm_RAXNx_9SbtAzjr160hq
EJ0YwE4M-9M77ct7Zb5-peAVA-DdqUNNu84ebhBQwGLzu25mlmmftzHnX9xHXieXlfv7n7bzELZf0kzvJJWpc548Mh-dZG5yjB6OOvb-C35mRFxEQi2JdiCi
0hfQGnOj7Pdcjm1VcBwiiF9X6tY97bVJyITS6j_mDB7Ai9CygUgZ7eVah4pF02M_4lyxDZ0MbYL2JsT4pyFz6IhERolTCfKmFl2dNctK-Ajwsfc3zvYvG7Ld
AolwMEUCjzV_z3rRqiU9ty9LdwUMbf7CO_gkxgV88BxymCEZExC8yHyZRlPAtsgcS6twu_YgNlPcyufKTRJRWrwxJnWcV9FL75i9tXiOyU8NkdtNy7nVeTQy
T8z7cv_28cSw2qe6X2A4_5voAJoPyegO1bVzRI17NtwpHrngEg8Ly91I3DjKEr5uCfYNSfQVGRylFzi-JcJdi-rn_9hV28uPAK_uRgSAjBTygHyQmaSx9YFl
dQMNjtTnfNEENpdT4qtFziQxyDEXL-4fkPy3p-x6E_1v0ah0lo95d0SVUAWwfgnam7-W53hxJrBTBYlV2vxolU2fsFjuuRxuQfUNxWfVrptj9efxXJobctaz
5J3ypIGO_cwA6ngUoT_jjf9rORg_0G
}

sprite $qualys [68x80/8z] {
nPT7WYGn3CCaqlz_yrvsecGq9-DM2QQpgowqP9ydRAchSbe-Eyv4xSEulo28D3ev3OOS3KCV8ClYynaCrSZf88HjsNuO1NemwVMXs0MigMemP9OkOQSbGq2B
mqLuSNZUOWGEKB34PLPKTm_9S41RwEcX1MtY6WFc2RAJ0-UGRbrSbxVCqrHNnngMNfWEZHHtYIwEeQ3gx0x1fC15fvR7XrWAAdZAo_dcSBW-pzSA2c275aU7
Eut6UxNu6GSEXuu2n_aBXyjSbwyxk5-ceqD71mvzT8ofD3A6pU75OUeOcjsgdY6Z6FtQ6gmVlDPLrIn2L9DPq7jXSH3LBCTLfNr1PKMzYxQl_ApGku-yRp3X
NkdXX2HTBypRiAEE9oFbUFs-j-kYq1hj5iNhn5x5JOT0gzlSsrDIFiX8lKfA3l-3nfDC0sTerw23Cxd6qyrZOrwgwPx8yz59BQCnDWbRJDNL6QYl2XMKm65y
xpgG7AjPCINWwUXNwn06HJh7KC4ILh245OnGeG8oILT8WoB7q1GnWgQ8QQX7ZY14J4E8746874DtnBIx7l4F
}

sprite $recordedlogo [659x80/8z] {
xPs9OhEs4eLdV_ytlajY_jOdEcBg40Arldkx8W-ZqOSmM51fubaLSXKMYwmFL2x1OX7rG2x1Ob4R9XTWiR3Q2FdtiLXABXPBoSLISh5OIYwMagfo3ek5PwNl
A1bdpPgBXTO7ELKoeT7FiLY0VqCbenwux693LExFJtH6RQDTJKHkXtxub2u82ZXHih0HnugHOJS_dMou74RiLBRskUCIYep8ghATcjXXId92trp9fQJ-gPzN
-QjAwZUKHEAzbLnALkdVAceNK1AoE9kbf6-e_0PHAgB_vxEabr2oN7wDfQJ-xZ3ensuh8of5n2-YPFbxAhcKt1mit-IyYfAbRwhaKZ9pKr8-zCghA5blgkHI
yjEf2hFu42vEKn8lOzJYUwVkfQGmRgZaPjVPIkfi_dnF9PUIcOy_wwTTURAIIDxnJj1IylZBcmmHA-rStc3Inoc91OwtL78fgUKF9QMoSHC89pCvMaa_eCBg
Z_moN8LZ0Uscg9hgKl8br5HLckGVBpgtoZ5hFr99h30rgAO6HUyMfq6xzEVD-I2sbIaVv32XC3gO_UpnS78zK4dFZUaMZ_zJ6ncVs4SUVrK4SDWI-S0UcmVV
nDI3hRNHLtvG5D64VpvQITogJTEW6MkgoThXR9rFKHDRRDXKIKlmtmGOfHN7ASc3-D-tp5OT90s1MvwAOc1Fenxsmh8BUApXK2KJziODCXuQKT8b87MiPDP6
qZq5AjdFdgTbjrVIeSTib5AXO14HhSLfm8_EahPdMlBopWN8UJjKCc6NOwUJACcoYb4D4RkvaZQeRJH-GpPOmdir9QCOsZ8IKyzvErGodhpZ6ULGIPvzOWb7
s0sK3AxaeBHvmAB4KvLKSbGHC2u7ZAGeAgcW4S_8KKdS6tUIwt1h9GEKdDSZhgba43a8IMUPp8IMGyCZ0WH39HsZSFVjgvBHovuFLTnPoK8bv_E1Nr590pV0
j7GpywpQcOv2_rocO_8w-4wjYVKNdqXK74pBlcQFpHe7tcbAPZuVoVd9QqeYXaTek9b5Q_sNHuRkAAcHuJjAAWGYIiv_v4Q3K3KTZAcEyig7kI04-RI3Ycwg
PkwuAUqpyHWhETBFSb2imQVLJrQItoh_bf9XgceUkeN6UXIE4Sanfahcv5Ov1keggPurcwri62DXP22imhysY3TmCb19Q3hUe2Cb0vF2VnsmUn0XxwzaZ6Fa
vCOVJJ4xFoWwLp8Wq42dy7YGMOX2zunw3QefQUZFlO_fbrYdbo7EvKUjK1TkI1NreAza3F5VLT9XBCPE97C52kjKIOT1GIKn42hP8L4eLWSNfXeKA21FEhGE
uhKMAutEIaw_ea13AvP-LqbE_AQIBgqGshpYBQeaTXY76WEzekJkuVFSiderTwgunDFHu0tnWjVEyMW0ZDvLmeQtLZ99gaP3-Bo3IfHKK0UK987-cPB6Eu6z
K3Wb01eRJtLLTdv0TvCweZjd6EKoqGFA1SWxAscaTFpadAyfQJ-lfCyw0TiCSfnH3KlWjrdZaodNn_5hEJ-WTjBoEolvmbJu_LaoEqeIbpWslKI2NPBP3u0q
Os99ENmD9DfDz74O0jxKOOv7z9PAzi_R64E__LtI6zybiwqahWh9ZfBPNyTgrR6a0aPgR83kXM_jB51bvCPA1ibK9qhQzFH5bRJPzJK9r5VIc-KUAfbD9Mss
CLjA2e0IzhFtMLfvNoKTvf0EFXcO4AOaEerAOY0-zF60fLGj-ahwTCL7HqdjAwbj9MEMLjptlgJ3k7S8lhBPPQ0aT2HrDbAAUV6pftzJIOKUVLF9wYYPLrCo
XN139H5rjzrb5-QkP3X98A8aklTcIXQEDk8_gwITfgJtbFpTbK0-EeByW1FtRPNKAoYvb4JvtkkxP3LFtFTNqcwcf45IM6wVyEJk4LVSSR2IuHFkhwJ_KoLz
Wbr1IUnnwMY8vy276Tg-Bndjcq0yV2-dvasW-okfqAp9kG_D-ZX2VYr3l9PZV_nmrLuSUQlSsae6IVd-LznuYFOvxzK2lCjbj98CvmEZle5rvRB1db_yGJ5v
o_uranwifEAMxokPVINHemwdle35PMUQj6vKxIvEusKnSiNHbr-glUoYF_NwmKeQtNLRIUKXk99upkjpwckgdEodx1jV9eCTmzbTmXkWvCkBqxXe_Qct3b7I
MNcihMIm7Bshf4Ex9gU-pCzfzSavWPwGnPiFEbIZi3fJKeewaFqbl68iUsntY9ByGAg-aYoHwYY96v365VSfhppbLlXWJrG0IA3uEP6hgs0QLpBu2bN-e8Fn
LNBpfUfrZ99A3gJWIc8kHdBClfBPUF_oLPJaXomTAuSeqNneTj0CZBQvalRIus0s7vmaBUC09R7RmPysmxR4wdAupcLATkPgrETQIZhK3HxoLNeQGID28I0i
YSV1yK9rkPAIN7xicKDA3pJH8sCFpHwY9Bfja1rLqc17E1Ow3D5wQiF917mT9UaKbl20luYg1OpWeC0HaOMcOS3AS7zkLxgdf0tar_rN2rIwgeYQvrutGPaZ
bBHw8YEoM7ZedexJIOZGK1Bc3NlK0o9SIqah5fdJVltKHasn_JkYe5zc5kBDxAFnHgCZbEJLiQ_Xeu1vuT8wIeBM1BkKabWuxOsgyggZ8vs0BaJ9pl0E1iDg
HkuFbli1Il9UXqBuKSuwJL7xIgBkICZrb3HolvoY3LLmJzembol90nWCnZnxb2X8aoEKv4A9DbvtwBFwkZIKx3aPSXKbYLNMK4Xx_NLGAej9HPJiEEdZmU1E
PYDvFK997b-7IYfJ9OSQpPL4l67aPPJaznUzsmSZJpmYJjeH9JlZwtGmeldWauqoEav9yK5uK99amhiIqb2oDo6O7Aga7AMan73CD0P2Qg_krX-Vlf9Y2Pyc
Wy6ozuReViIgSfI1lvA3Eyasf4fJILuxtfRZfogfHK9PyFzC3NqfO3fuImA6KpduVYBhGTZUOC2B2aq8dj33WvJ4scJOV1LZi0dC8g6sRIKnZuqCbIwOD5So
uD_Ci8rX8cf_66npTySFiYZQQFRHRfh5_cwQFLFxp5uRkQksCk7xxACR0dZyPI-Y90JDg5MFFWdIZvGKqFOdMImIz1ifgSbE7iUpM5Y4gn0bDzHDvMmM2rJo
pYoMael5KdAnb5mibfAB1TpM_sqMYu3Vi7wRnI8lPkHYOPbXykCi5ly5
}

sprite $recorded [85x80/8z] {
xTa5RWKn30JGZEd-DovtuaeAIIvdH1_VOXBBspQZ7c6jDXulGQLfyPPADDuZTQOGjL-8NXGuKjJ3TO7QsPxZ5V0fwlpHNYXCK8unFJs34pIOmu4UyhKe_WDw
qOjcGklGvXJgK1fQYJOutrUXN3pgKEQRqOkgkM61mjnqWQ93ob4zGNrzysT8uos-CqnrZ1gX_AqEKGq68pH35Zr3D7fiX6Oe1mCKaJ92un2L6dIyfxw3dfvJ
tJYddluWGrGICK8prFzWRO3cZsI8VeJWFAu1oZlLCHjHY0n1LPOJYgXYClO9VVVKTr6W66KnyUFB7gVmGqh9MvvVzABrxGwjH_EXxRIGxAnN73f1s_QEKYKm
Hk6x3JGgPefL0n4g-FlzqulMFpp8uyTRPPncPSJTje_z4G
}

sprite $snowflakelogo [335x80/8z] {
xDRLeOGm04JHaVvhVYwBHbQmkPyu1qdmgf9i4RVHjj1JybSQ-7w5zf9_uk3TxFDCz0JF0-6Mabx56KxXIOKpXJESuSpCI6sSBE1cdga6JYrDwvF_OYMdZlBn
avBmdOZA9FH7tyGovt270tns-hq5Lk-c1t5Q9KvwqFurxNPEFuhJrYgdV1XEVoO9B-M45slOP7zf0FWwJjx1IUokeT_hES4Yvw4qXoYlvmJKnIaWdBEndLD0
E1TZ8oSHpjNKm4aWdALKoIaWd1MnmDc8IN9bNM5FehjtMir3HtOGYg6ov_-_-NNa6PqhxzMIrvTYC2UqG6pxtnxU7d3E1jLmMf0YncIZBt5gA4Jbd4gVtVze
ofpXiIha7eKSP9fnneGLCN5IJMbSqwG13d7CxG7cN8wGrcOSBuTW6WsS1C9ng6GOQufJI8tO1Q9e2tgMa9A2KtKULbiEjPpqPDl_1hiWdrO9Lvpn2IcFDKb9
7W3rBcZGj9B97COPCopISH4VBhDsSjIb20PJZO6pqXGSNgxLxQIEN-HWVi5J8lkJN-HJndh5oM9JAt6IPgG8xtQIihQRgYHndiAZdVF2Y33xzMrUtoZn6U8n
GodGD7iLUSnUGwh1J1ri5sL23IFRkFLkj2Tdnwbn4I3Eq1BTqE7YBHmzZ-CSMLgxFQyzme_ilWIav4Pompds4E8apKZf4508DC2vKB5dzzx95CA7WSHYjBDj
NkBKlA4VSIQMKZfiN48Jjl7BXEQE4-s6MQPpSkHnUyVP7ZPmeWeEEphS7YD5kfqZDEASSxET135lTj2cXhEjQ09Eq8IKyHfvXgRbn3BxN86ETi2fXjEZsNan
YYscTPppJ0ISe2csbdLhxctv-PrdWGcU9DfnDhD4v1Y4kk7K5gTUBBBywbj8uwCF3GLwSTPdNU8KjfxdHoS5b6vnwlKzdCp7ZHXneZ9ICA1VucH7ZIJLF8DJ
GnDTQFhPtjc9wXAdFnW5N_02qXrElSu_stFbX-VEJbJNSoUXwAs1VX1dEcPuRd7A-vMzxrJxuxfRsHMq6JpffCbplL4AJd47NN0-lk_ibQZY1022IE341Ikb
7QURoImLu0afgdp-hMW6ueeJtCOtgNHXVsZGiI_VYl9ZeY7biTjttzbV_7M9asxxGL7YVCBQu6I18OMNUl8KfIVFmoTAbpZZbgd4eiGfuIrEJ_3xUITc15Xy
-hpp4YTcAZGW4IVRKTi9Tvnf53mG9tb6Ieix7jB-D3u6pAVNSV8UOGQSTHVX9SxvPPmuwO7IUFwVTqKURc8wplnCL7D7GdY3auTH2GeuoJDIjixjKmJ4QNcJ
cHPQah9hBJW9nv1oqPZ3ovjCEDHN5yFwbBvhlRjdPzJ-dXrTTuMJKi_pUGalS78nLVzieUwyLH4z_nL84ZjEIgsoiFKpSd742CPZiECKQ4Jxy3TAY4lf8AAf
7nctSUU3BMIT2vctQJXTSp6OOg5C8gIld-tTHm73K103qKZyGGU1UxVVGFXbJzBiHFKhNP2WmtdvJcHH-XWxPUEdfmQwGtC3Itf5Vlm9hJVisid4herXdDPd
TvpDGji2pd61c9szn5J3evG9ZvBpR7QpV24h77JvtHfAFyS9n-aucRd16s-hWPqRDiACrv_n1m
}

sprite $snowflake [80x80/8z] {
xPbPMWGn28HJnVtFxAumCqsH5joj9pyQVhE7C4i8PiPB4yqCwtsYFIcQdYtiuCmYhW6qLy7x_weP7ZiyRmo_XFVFeyTkyy1qENhqFe_v-dPdxF9eOiDO47Pu
iA1a-1rHyM1Myg8eUQ0Ll6Mfd5UxkD3XGKtmUHx4ZZZFezfZvtbOGYnuDQqcKdsg1StJD4tKF6JX14IdFGwA1XA-CIY8RioxYZTNuN7J45Q-jYXw4AqHAFf2
ES80LccYvU8gL9zpaXY3zjOgz0wAKJjx2Mvp8Mb4IJEwUnIJFbLd4SG_EepJZPDV7LTQ8ortY7PUPTD9LoKHLmbu05BIr74K6vNok5QFPnLllh_ipGUTEBzU
S7uzmvAOwVqsVHxWrjOwhwRFqsj-zxoVlezOtT6uDGaYf-_prx-R-GO31UHaFjJFrxJ0iNnoFjz5Cn_llnUO4pdrdfb_Rys_1wt3u_XxMlE8rdj_lXuHdTci
b_JhEPRNcx1sUUx57rPV--VrwyNzUlPylNt-zm0jy2QMPeIAkGS
}

sprite $tailscalelogo [444x80/8z] {
xD750OHG00FHuFrNlEu2VBUPQsvvyX0H4H4H4H4HqRIyf1QgtMvvDYktbcTJ73kjhjP_TzZvm5CDTjYf8ZlijBx6jCDEw__dR8UTLk_l7DRWTjXfzVxEOGrj
XzshWCFgzZTsRdoMwukSgnrs-UVVRfXUojaEk_MmmmuxxB33BeEw_jghtT0_qi-wxjZEcIwvheD0MAnw_oU--vtZwPBR8iHLdZhflt4Gy6abYbLLHOZDBrNO
YO1PBX4XZnFRd1st8I9FOUUJQg3K8myGmlGzPmIro8DPrmiIvlWuVnOUhhFJOuEkFuwTnLp8fSjEFET4nNb-B8aNn3JOtcUdGKmycnrc31NIOISnrqejk0n9
HzFSDcUdMN2FJwb2OSWjx90Sochig0SSXt4le1CHEM67LdYVnII5iIaWZCt9eUzd5vFBNsN73IUTZpaFpKaLXDsk5LrtgpIMwLGsGOIybvtal9AzneuQnWFB
jHy1cQIA3NRsOjW-G4ac28XBtyCEJ3DfWHqyofGS7SeXwLJEsQ4L3Y_0Da67y30kUIExd1lA0ZkI6Z9fojoGyMSnIPoTxJTe4wGqpKB0phnztA6qpgw4RcI5
XyyD1M5Nx0199mowsEf4sMthNVhV2lJMo-mCeer_3TCDAJuVPpdpXUcS8A7iSjdWSfGetSSuFNt59Do9rDqnAl-bWV2cww5WyHrfaHsktu97uHc3z4wNavsW
Oi8IJ1zaZ9rZWmSZs6c3RdgJRdB8PDwgHGCyPrjsgRA3ZEFEtDUhFTzHEFPst94hc3bb9wUpD_QNDPsaT1mS0h9jTWWlPR2jhnRP2JqHW__6OfF4Z7p1Stgw
Jy8k0F9vuBwaatJTZ7lPONw2h9TTTdvL84eUMYwD-389U-o4e4E7digELzkipuwlpYIJa4edFfEidx5pY0AbtrATXCwIh5EoscDN_vvsrhlaxZhbZ9IuvXOx
60Oqz1ZEIowK3gb5tidEPeTTxl-gaf2KXdABdTBEWayCeNj5OtGMtEDsTc8vM-mmf7JPcJ8xu1GIjMI72GrVwbleGVEVP50kkEijx4JL38xcBx73aFXFqjgv
KABsdylWCsMNio8309X5fOTl9zZVnSuW-3OxdIk5AvkRhSIDk4pPpP82Oy6Xu_IdhI1Ws-omcD1dXo7nwTFHlNwrbhEJMLBY2abxNmfpDCQRsGaXrs37ifks
Tg-oaNgPdTRP3N4u0406sSIXkOYwpOw4qcV74vpQOHVpVdPenpp2px8l5d5-fKsSVDfWf_CsTdn4--euNJyAtC_kiVUYTTx8Zby9YLV7NSmFEzw5C_hi-3ue
5kxrrZhF3NRoyzdn2v4kZNecoCxm6RgWZHapmyRuVTXX7jBjSBE_mmwbvWk0YSrOVTY5wS7dh9xlGY_rK7PAIiPzTYWnv6ULkWg_RrTWbxKM7yhE8Ukti4EZ
cBdYXG1aNsSNuE_FP1SiRNu3EzpbeKqVLn9WKVqD2FkF_5HsoP8UVNPYt9svbKhL4_P6m19sCYzxYpq172yOJiPkTjc9htQEZgZ6LR4sPogToHSVCdOZqGLK
p93wFrNbNdQspywRxCJNgGb87BGKwu6Q2dZuSiVP6MzmnCAu_Al1YldfzAL8JNR1bmUOcnhin4yAwx8uEy7-PSqwb5pwWqW9Ez8Wj1ZhjzEoKZGIvz-j7eXi
yxg1p0uxSSWmD0ca3SlKww9QAFOfWewmmoVZx7wcxRt7B-dwATA0fwihmEg8OWgaeS4ElkqAe_6i7estdJN03NAhJ79kiyC6uyj1omLL0T4wZoEw5Zo8AJFp
kCL3h4EzMukEYSgCp5EpCYVgwtdCVQv-21IWVCLEDnqCocuTgo2w_WiqKSUS8TS6Es115JlrPRJjnEKzTcW5XHo40L0ILOCTJqpfseqLsD7KyAjoN4BwHPNT
YEsmEJkdOObquULfQ7eJkn45emGU6VjDTYCgw50qj_PETdeUcj_4RaG17S3Zw8QqsMs6ReEmetVQ--oucvSvTd2dVKyCMO0aDnxdaqKaJ5t0hj9RKWTXn_zB
mjdruLqD48Meg-o6CXOXn4loEBKSK8CbxE1GpG1mTZUDEzx7-AjnGhw1oYexVjyXT2mbpgy4yiNAeVv7s04zrbVgSwQrsQ4yaTqvlL2Scqhi-3k_qfd_5WGq
ePmkuB9pTd0Q9rs5vZzksMVo5-fDYC0ZZo_3Gx-aznw_d5_6vTfFZvpe3BERONhc2cU7mIyQB9_lykAxBTLCVCJJdtJ_t4BNrqSq_yB_wVCeT1zuT1kO0_GW
TXzurNyGFeNSXnuzFgTIyEE9-aZDtPu6vwC_0G
}

sprite $tailscale [80x80/8z] {
xLW7SiCm33CufF-_kBkLOoAug5PtSPimeCqmt5u00DirO9B52ufeXYqXBi4q2oN1D0ibqIm8YmAXMEy7IU8T2is2u5Fzy8tzFlyyFlM-pD_drUzjSJvOdg_M
vrETxoT-3Nup_l4FGBBR5EkjFo2TVnsAjHVMTcxz5OreOh1MIEGRctY9PTyXZegsP_reTy5QiQk6Gq0CSM0n5ZjWPB4348FrDcBxu03w4RbZhR0-OdI2KTbj
80lPIAn7NH3VmLu1ecXI4MIv0zwL7mYRd-lNb4Al5uIra3kUH257OuDWA5pUbs1BIn8J5yRbRJSInDxFwbc92IQHs2Oa3PTiri668KznJkpuS3aISBaCD6Kw
OQtHLEoH6Rvnm3Cpx1eRXVrJ-CS_O8Qfxv_1ISld1nfIMoFS4LcJgTRgVv1DLbz4YWDaVHKd-rVP3y1ylqbMK7dABth1gVwBhg_c_Nf5pFlfUcYnNonUhv_f
3sKlm1a_KyKmrzQGhg_EzQyWdaVLtf1VdArsOBv_PNnsEdUM4Al9catqhoJC8_msmJq
}

sprite $wizlogo [167x80/8z] {
rDC50GG124JHGN__nEUwMm1U0NGqLsa5J0iOgGM2rW8Dfl4Sg1NBNB3EvAvNT0bjcYluAjD45iM_JjSqtfnrQXulVdLCJj263Cbu2irctAMc2m3Drn2QBq0R
KDgWGn-HlwwrcGUkw20G0s61vVud_htn7xFHA7fMJHyCjf0oe6_xlTqEnOzRZrFz-0GA46R_nzbJLvwzysc3y7iFkpwUQji9-lxGX5lY6iL3yHwJ2xq_Z-Mo
FwKdtsEU7s9FO6xxupoymkJlymexXUTFTSHqPf8UPZqWN75v_tlCZfYhNi9v2HS_vZ5vBcjRwEh390XCOoOlCZ1jbalw7IRN8KUMMgSk2CRqpQwhSy6gfMSy
9dn0XUYaAMU0CMqP-H1Du8Vr39YosNs8W1y61fWnBbfefW_HfF4kyc696WHpV8XWm72_mapHx0_rCc34uBx1z6PoMUU68SCN16P2ixiGmOZtxX0WYHdOxBuw
yu8vuMQ9cTJilZfZtmJM0wOsqrVdWjq1B6I3cT3iEaIpzNqNr8B17DZiFaGBC0UKfi34Cl8Xcflq_uqQSq3DYH1vTO4fpSIdlR9Pp26Q7VOVNg4nHHdH_iEh
MSmXcXtQp6iAJ39JQY1BNnWWYpb4ixiGPNN9Oefc9u5dmVaQ0bEPwQip2wURnOHcTo8poSvbCQTeTXUYB8OG5XEAmWfGoCucCQSe8nUYB8OmBQPeTXcYO2js
5vXlp1Ir1jSKvjiouW57TKrYJj7iRl-HvGPVO1ep_VuZ2Zkcn9oYsLrrPhLokyFiLG2zgccPC0J6z2lJLsTMOnW2yxxfphl2LcTKIw8vp2LssYv4MIs9vJ3x
5fWkH55UT9XBOBeGPPcmfZ3x5fWkH55vFHtcSfWYH5bwtGMcCDDWjkV_xzaKvleKpFdu_pq4fZ3JOVQ_861dKvZh9IPNPvPhOWfCOQR573lAgrrXhfUOhEMl
yhzOWOYRXQy
}

sprite $wiz [84x80/8z] {
hTU5iMGn34HHoOBEF-CjtFxiUJNt1E2oo12lIdNGIXkqaO8cAOELaWfFfpHyEYK-dLBYwPGAJwUqV3ebFftImKENXWzTuaENYWqThlpglmp6aJLN8UFcqehR
fd7RjEAsQLpHhRdUv7gqPT0mbSo6IwOrrqPMt2wjWV8WXShLnU4sQPEFMmXTjMJ8gZbwPizbmLhfkJxN1Q5biqRlcafmFPi-RaJGnWWNaQTNbErACgVxG-rF
lrNqC6BPkOpIUJoR5NVPu1QjmLF9HdUR-DrH_1sNq2F4Xh_Wct_R3Fy6M_wjAF9DY_sEkMHQNI8dec_-WoJ-lwdYFvmAo63PjEJ-MxQUIinnXJYk46SybdJm
5II73WU_WIetF2RTy6n20pRI1Aoa2jXvVBVbAqMA5_q3
}

@enduml
