@startuml
!define criblPuml https://raw.githubusercontent.com/criblio/cribl-plantuml/main

!include criblPuml/common.puml
!include criblPuml/cribl-product-logos.puml

!include criblPuml/activity-badges.puml

!include criblPuml/infrastructure-shapes.puml

!include criblPuml/logical-data-flow-shapes.puml

listsprites
@enduml
